function audit = auditBoundaryCompleteVerticalModeCompression(self,options)
% Audit boundary-complete vertical-mode compression against the primitive oracle.
%
% This Milestone-9.2 diagnostic constructs fixed-wavenumber nonhydrostatic
% waves, Robin APV-bearing geostrophic modes, an explicit zero-APV bottom
% inversion, and the compatible zero-wavenumber sector. The resulting
% vertical coordinates are represented in the existing primitive
% polynomial oracle before the unmodified finite-terrain forms are
% restricted to their span.
%
% ```matlab
% audit = problem.auditBoundaryCompleteVerticalModeCompression( ...
%     trustedModeBounds=[1 0], ...
%     supportModeBounds=[1 2;1 3;1 4], ...
%     stationaryPolynomialDegree=4, ...
%     primitivePolynomialDegrees=[4;6;8], ...
%     comparisonPolynomialDegree=12, ...
%     modalCounts=[1;2;4;8], ...
%     robinLengthRatios=[-1/8;-1/4;-1/2;Inf], ...
%     paddingFactors=[2;3], ...
%     terrainScales=[0.125;0.25;0.5;1], ...
%     internalModesEVPOrders=[128;256]);
% ```
%
% The main InternalModes checkout used by WaveVortexModel is not replaced.
% The general EVP classes are resolved from the isolated
% `internal-modes-evp` checkout already required by this repository.
%
% - Topic: Audit boundary-complete vertical-mode compression
% - Declaration: audit = auditBoundaryCompleteVerticalModeCompression(options)
% - Parameter trustedModeBounds: nonnegative integer `[kMax lMax]`
% - Parameter supportModeBounds: nested signed Fourier bounds for the primitive reference
% - Parameter stationaryPolynomialDegree: trusted stationary-space degree
% - Parameter primitivePolynomialDegrees: nested degrees used to classify the primitive reference
% - Parameter comparisonPolynomialDegree: primitive degree used for the modal comparison
% - Parameter modalCounts: total wave and Robin vertical counts
% - Parameter robinLengthRatios: signed bottom Robin lengths divided by depth
% - Parameter paddingFactors: horizontal oversampling factors
% - Parameter terrainScales: positive terrain multipliers ending at one
% - Parameter internalModesEVPOrders: increasing spectral EVP orders
% - Parameter quadratureOrder: optional common primitive quadrature order
% - Returns audit: modal compression, physical projector, and outcome diagnostics
arguments
    self (1,1) WVTerrainEnergyGalerkin
    options.trustedModeBounds (1,2) double {mustBeInteger,mustBeNonnegative}
    options.supportModeBounds (:,2) double {mustBeInteger,mustBeNonnegative}
    options.stationaryPolynomialDegree (1,1) double {mustBeInteger,mustBePositive}
    options.primitivePolynomialDegrees (:,1) double {mustBeInteger,mustBePositive}
    options.comparisonPolynomialDegree (1,1) double ...
        {mustBeInteger,mustBePositive} = 12
    options.modalCounts (:,1) double {mustBeInteger,mustBePositive} = [1;2;4;8]
    options.robinLengthRatios (:,1) double {mustBeReal} = [-1/8;-1/4;-1/2;Inf]
    options.paddingFactors (:,1) double {mustBeInteger,mustBePositive} = [2;3]
    options.terrainScales (:,1) double {mustBePositive} = [0.125;0.25;0.5;1]
    options.internalModesEVPOrders (:,1) double {mustBeInteger,mustBePositive} = [128;256]
    options.quadratureOrder double {mustBeInteger} = []
end

if numel(options.primitivePolynomialDegrees) < 3 ...
        || any(diff(options.primitivePolynomialDegrees) <= 0)
    error("WVTerrainEnergyGalerkin:InvalidModalCompressionDegrees", ...
        "primitivePolynomialDegrees must contain at least three strictly increasing values.")
end
if options.comparisonPolynomialDegree ...
        <=max(options.primitivePolynomialDegrees)
    error("WVTerrainEnergyGalerkin:InvalidModalComparisonDegree", ...
        "comparisonPolynomialDegree must exceed every primitivePolynomialDegrees entry.")
end
if size(options.supportModeBounds,1) ...
        ~= numel(options.primitivePolynomialDegrees) ...
        || any(diff(options.supportModeBounds,1,1) < 0,"all") ...
        || any(~any(diff(options.supportModeBounds,1,1) > 0,2))
    error("WVTerrainEnergyGalerkin:InvalidModalCompressionSupports", ...
        "supportModeBounds must have one strictly expanding nested row per primitive polynomial degree.")
end
if any(options.trustedModeBounds > options.supportModeBounds(1,:))
    error("WVTerrainEnergyGalerkin:ModalCompressionTrustedBandOutsideSupport", ...
        "trustedModeBounds must lie inside every supportModeBounds row.")
end
if numel(options.modalCounts) < 2 || any(diff(options.modalCounts) <= 0)
    error("WVTerrainEnergyGalerkin:InvalidModalCompressionCounts", ...
        "modalCounts must contain at least two strictly increasing positive integers.")
end
if any(isnan(options.robinLengthRatios)) ...
        || any(isinf(options.robinLengthRatios) ...
        & options.robinLengthRatios < 0) ...
        || any(options.robinLengthRatios == 0) ...
        || numel(unique(options.robinLengthRatios)) ...
        ~= numel(options.robinLengthRatios)
    error("WVTerrainEnergyGalerkin:InvalidModalCompressionRobinLengths", ...
        "robinLengthRatios must contain unique finite nonzero values or Inf.")
end
if numel(options.paddingFactors) < 2 ...
        || any(options.paddingFactors < 2) ...
        || numel(unique(options.paddingFactors)) ...
        ~= numel(options.paddingFactors)
    error("WVTerrainEnergyGalerkin:InvalidModalCompressionPadding", ...
        "paddingFactors must contain at least two unique values of two or greater.")
end
if numel(options.terrainScales) < 4 ...
        || any(~isfinite(options.terrainScales)) ...
        || any(diff(options.terrainScales) <= 0) ...
        || options.terrainScales(end) ~= 1
    error("WVTerrainEnergyGalerkin:InvalidModalCompressionTerrainScales", ...
        "terrainScales must contain at least four finite increasing positive values ending at one.")
end
if numel(options.internalModesEVPOrders) < 2 ...
        || any(options.internalModesEVPOrders < 16) ...
        || any(diff(options.internalModesEVPOrders) <= 0)
    error("WVTerrainEnergyGalerkin:InvalidModalCompressionEVPOrders", ...
        "internalModesEVPOrders must contain at least two strictly increasing integers of 16 or greater.")
end
if any(ismember(options.internalModesEVPOrders,[96;192]))
    error("WVTerrainEnergyGalerkin:UnqualifiedModalCompressionEVPOrder", ...
        "InternalModesEVP orders 96 and 192 are unqualified because commit df86687 returns spurious large-negative Robin eigenvalues at those orders.")
end
if ~isempty(options.quadratureOrder) ...
        && (~isscalar(options.quadratureOrder) ...
        || options.quadratureOrder ...
        < 2*options.comparisonPolynomialDegree+3)
    error("WVTerrainEnergyGalerkin:InsufficientModalCompressionQuadrature", ...
        "quadratureOrder must be empty or at least 2*comparisonPolynomialDegree+3.")
end

audit = buildBoundaryCompleteVerticalModeCompressionAudit(self, ...
    options.trustedModeBounds,options.supportModeBounds, ...
    options.stationaryPolynomialDegree, ...
    options.primitivePolynomialDegrees, ...
    options.comparisonPolynomialDegree,options.modalCounts, ...
    options.robinLengthRatios,options.paddingFactors, ...
    options.terrainScales,options.internalModesEVPOrders, ...
    options.quadratureOrder);
audit = rmfield(audit,"sharedSetup");
end
