function audit = auditDensePhysicalEnergyTerrainModes(self,options)
% Audit the dense physical-energy finite-terrain modes.
%
% This diagnostic uses the Milestone-8 stationary balanced sector defined
% by bottom tangency, solves the unmodified physical-energy eigenproblem
% on its orthogonal complement, and assesses low-frequency bottom
% candidates by backward error rather than by a frequency cutoff. Every
% non-tangent bottom direction remains in the returned complement.
%
% ```matlab
% audit = problem.auditDensePhysicalEnergyTerrainModes( ...
%     trustedModeBounds=[1 1], ...
%     supportModeBounds=[1 2;1 3;1 4], ...
%     stationaryPolynomialDegree=2, ...
%     primitivePolynomialDegrees=[2;3;4], ...
%     paddingFactors=[2;3], ...
%     terrainScales=[0.25;0.5;1]);
% ```
%
% - Topic: Audit dense physical-energy terrain modes
% - Declaration: audit = auditDensePhysicalEnergyTerrainModes(options)
% - Parameter trustedModeBounds: nonnegative integer `[kMax lMax]`
% - Parameter supportModeBounds: retained signed Fourier bounds by refinement
% - Parameter stationaryPolynomialDegree: minimum stationary-space degree
% - Parameter primitivePolynomialDegrees: increasing primitive support degrees
% - Parameter paddingFactors: horizontal oversampling factors
% - Parameter terrainScales: positive increasing terrain multipliers including one
% - Parameter quadratureOrder: optional common Gauss--Legendre order
% - Returns audit: dense modes, classifications, uncertainty bounds, and residuals
arguments
    self (1,1) WVTerrainEnergyGalerkin
    options.trustedModeBounds (1,2) double {mustBeInteger,mustBeNonnegative}
    options.supportModeBounds (:,2) double {mustBeInteger,mustBeNonnegative}
    options.stationaryPolynomialDegree (1,1) double ...
        {mustBeInteger,mustBePositive}
    options.primitivePolynomialDegrees (:,1) double ...
        {mustBeInteger,mustBePositive}
    options.paddingFactors (:,1) double ...
        {mustBeInteger,mustBePositive} = [2;3]
    options.terrainScales (:,1) double {mustBePositive} = [0.25;0.5;1]
    options.quadratureOrder double {mustBeInteger} = []
end

degrees = options.primitivePolynomialDegrees;
supports = options.supportModeBounds;
if numel(degrees) < 3 || any(diff(degrees) <= 0) ...
        || any(degrees < options.stationaryPolynomialDegree)
    error("WVTerrainEnergyGalerkin:InvalidDenseModeDegrees", ...
        "primitivePolynomialDegrees must contain at least three strictly increasing values no smaller than stationaryPolynomialDegree.")
end
if size(supports,1) ~= numel(degrees) ...
        || any(diff(supports,1,1) < 0,"all")
    error("WVTerrainEnergyGalerkin:InvalidDenseModeSupports", ...
        "supportModeBounds must have one nondecreasing row per primitivePolynomialDegrees entry.")
end
if any(options.trustedModeBounds > supports(1,:))
    error("WVTerrainEnergyGalerkin:DenseModeTrustedBandOutsideSupport", ...
        "trustedModeBounds must lie inside every supportModeBounds row.")
end
if numel(options.paddingFactors) < 2 ...
        || any(options.paddingFactors < 2) ...
        || numel(unique(options.paddingFactors)) ...
        ~= numel(options.paddingFactors)
    error("WVTerrainEnergyGalerkin:InvalidDenseModePadding", ...
        "paddingFactors must contain at least two unique values of two or greater.")
end
scales = options.terrainScales;
if any(~isfinite(scales)) || any(diff(scales) <= 0) ...
        || ~any(scales == 1)
    error("WVTerrainEnergyGalerkin:InvalidDenseModeScales", ...
        "terrainScales must be finite, positive, strictly increasing, and include one.")
end
if any(1-scales*max(self.topographicHeight,[],"all") ...
        /self.originatingTransform.Lz <= 0)
    error("WVTerrainEnergyGalerkin:NonpositiveDenseModeGamma", ...
        "Every requested terrain scale must satisfy gamma>0.")
end
if ~isempty(options.quadratureOrder) ...
        && (~isscalar(options.quadratureOrder) ...
        || options.quadratureOrder < 2*max(degrees)+3)
    error("WVTerrainEnergyGalerkin:InsufficientDenseModeQuadrature", ...
        "quadratureOrder must be empty or at least 2*max(primitivePolynomialDegrees)+3.")
end

audit = buildDensePhysicalEnergyTerrainModeAudit(self, ...
    options.trustedModeBounds,supports, ...
    options.stationaryPolynomialDegree,degrees, ...
    options.paddingFactors,scales,options.quadratureOrder);
end
