function audit = auditAnalyticGlobalTangentStationaryCompression( ...
    self,options)
% Audit the exact constant-N mixed-boundary attribution control.
%
% This Milestone-10.2.5.1 diagnostic replaces only the zero-bottom-trace
% geostrophic provider family by its analytic constant-stratification
% sine modes. The exact terrain forms and all other production coordinates
% remain unchanged.
%
% - Topic: Audit analytic terrain-energy coordinates
% - Declaration: audit = auditAnalyticGlobalTangentStationaryCompression(options)
% - Parameter trustedModeBounds: nonnegative integer `[kMax lMax]`
% - Parameter supportModeBounds: increasing retained support bounds
% - Parameter targetWaveModeIndices: positive production wave labels
% - Parameter interiorGeostrophicModeCounts: increasing analytic counts
% - Parameter stationaryReferenceDegree: polynomial stationary degree
% - Parameter primitiveReferenceDegrees: increasing oracle degrees
% - Parameter paddingFactors: horizontal oversampling factors
% - Parameter terrainScales: increasing terrain multipliers zero to one
% - Parameter comparisonEVPOrder: pinned-provider comparison order
% - Parameter cacheDirectory: optional untracked audit-cache directory
% - Parameter quadratureOrder: optional common vertical quadrature order
% - Returns audit: analytic controls, provider sensitivity, and classification
arguments
    self (1,1) WVTerrainEnergyGalerkin
    options.trustedModeBounds (1,2) double ...
        {mustBeInteger,mustBeNonnegative} = [1 0]
    options.supportModeBounds (:,2) double ...
        {mustBeInteger,mustBeNonnegative} = [1 2;1 3;1 4]
    options.targetWaveModeIndices (:,1) double ...
        {mustBeInteger,mustBePositive} = [1;2]
    options.interiorGeostrophicModeCounts (:,1) double ...
        {mustBeInteger,mustBePositive} = [2;4;8;12;16]
    options.stationaryReferenceDegree (1,1) double ...
        {mustBeInteger,mustBePositive} = 4
    options.primitiveReferenceDegrees (:,1) double ...
        {mustBeInteger,mustBePositive} = [16;18;20]
    options.paddingFactors (:,1) double ...
        {mustBeInteger,mustBePositive} = [2;3]
    options.terrainScales (:,1) double ...
        {mustBeNonnegative} = [0;1/8;1/4;1/2;3/4;1]
    options.comparisonEVPOrder (1,1) double ...
        {mustBeInteger,mustBePositive} = 128
    options.cacheDirectory (1,1) string = ""
    options.quadratureOrder double {mustBeInteger} = []
end

if size(options.supportModeBounds,1) < 3 ...
        || any(any(diff(options.supportModeBounds,1,1) < 0)) ...
        || any(all(diff(options.supportModeBounds,1,1) == 0,2))
    error("WVTerrainEnergyGalerkin:InvalidAnalyticGlobalTangentSupport", ...
        "supportModeBounds must contain at least three distinct componentwise-nondecreasing rows.")
end
if any(options.supportModeBounds(1,:) < options.trustedModeBounds)
    error("WVTerrainEnergyGalerkin:InsufficientAnalyticGlobalTangentSupport", ...
        "Every support bound must contain trustedModeBounds.")
end
if isempty(options.targetWaveModeIndices) ...
        || ~issorted(options.targetWaveModeIndices) ...
        || numel(unique(options.targetWaveModeIndices)) ...
        ~= numel(options.targetWaveModeIndices) ...
        || any(~ismember(options.targetWaveModeIndices, ...
        self.verticalModeIndices))
    error("WVTerrainEnergyGalerkin:InvalidAnalyticGlobalTangentWaves", ...
        "targetWaveModeIndices must be sorted unique labels retained by the originating transform.")
end
if numel(options.interiorGeostrophicModeCounts) < 3 ...
        || any(diff(options.interiorGeostrophicModeCounts) <= 0)
    error("WVTerrainEnergyGalerkin:InvalidAnalyticGlobalTangentCounts", ...
        "interiorGeostrophicModeCounts must contain at least three increasing values.")
end
if numel(options.primitiveReferenceDegrees) < 3 ...
        || any(diff(options.primitiveReferenceDegrees) <= 0) ...
        || options.stationaryReferenceDegree ...
        > options.primitiveReferenceDegrees(1)
    error("WVTerrainEnergyGalerkin:InvalidAnalyticGlobalTangentDegrees", ...
        "primitiveReferenceDegrees must contain at least three increasing values not smaller than stationaryReferenceDegree.")
end
if numel(options.paddingFactors) < 2 ...
        || numel(unique(options.paddingFactors)) ...
        ~= numel(options.paddingFactors) ...
        || ~all(ismember([2;3],options.paddingFactors))
    error("WVTerrainEnergyGalerkin:InvalidAnalyticGlobalTangentPadding", ...
        "paddingFactors must contain unique values including two and three.")
end
if numel(options.terrainScales) < 5 ...
        || options.terrainScales(1) ~= 0 ...
        || options.terrainScales(end) ~= 1 ...
        || any(diff(options.terrainScales) <= 0)
    error("WVTerrainEnergyGalerkin:InvalidAnalyticGlobalTangentScales", ...
        "terrainScales must contain at least five increasing values beginning at zero and ending at one.")
end
if options.comparisonEVPOrder < 16 ...
        || ismember(options.comparisonEVPOrder,[96 192])
    error("WVTerrainEnergyGalerkin:InvalidAnalyticGlobalTangentEVPOrder", ...
        "comparisonEVPOrder must be a qualified order of at least 16; orders 96 and 192 are excluded.")
end
if isempty(options.quadratureOrder)
    quadratureOrder = max( ...
        2*max(options.primitiveReferenceDegrees)+7, ...
        2*max(options.interiorGeostrophicModeCounts)+15);
elseif ~isscalar(options.quadratureOrder) ...
        || options.quadratureOrder ...
        < 2*max(options.primitiveReferenceDegrees)+3
    error("WVTerrainEnergyGalerkin:InsufficientAnalyticGlobalTangentQuadrature", ...
        "quadratureOrder must be empty or at least 2*max(primitiveReferenceDegrees)+3.")
else
    quadratureOrder = options.quadratureOrder;
end
if max(abs(self.topographicHeight),[],"all") == 0
    error("WVTerrainEnergyGalerkin:AnalyticGlobalTangentRequiresTerrain", ...
        "topographicHeight must provide a nonzero terrain direction.")
end
if any(1-options.terrainScales ...
        *max(self.topographicHeight,[],"all") ...
        /self.originatingTransform.Lz <= 0)
    error("WVTerrainEnergyGalerkin:NonpositiveAnalyticGlobalTangentGamma", ...
        "Every requested terrain scale must satisfy gamma>0.")
end
z = linspace(-self.originatingTransform.Lz,0,33).';
N2 = self.originatingTransform.N2Function(z);
if isscalar(N2)
    N2 = repmat(N2,size(z));
end
if max(abs(N2-mean(N2)),[],"all") ...
        /max(abs(mean(N2)),realmin) > 1e-12
    error("WVTerrainEnergyGalerkin:AnalyticGlobalTangentRequiresConstantN", ...
        "The analytic attribution control requires constant N2.")
end
cacheDirectory = validatedCacheDirectory(options.cacheDirectory);

audit = buildGlobalTangentStationaryCompressionAudit(self, ...
    options.trustedModeBounds,options.supportModeBounds, ...
    options.targetWaveModeIndices, ...
    options.interiorGeostrophicModeCounts, ...
    options.stationaryReferenceDegree, ...
    options.primitiveReferenceDegrees,options.paddingFactors, ...
    options.terrainScales,options.comparisonEVPOrder, ...
    false,cacheDirectory,quadratureOrder,"analytic");
end

function directory = validatedCacheDirectory(directory)
if directory == ""
    return
end
repositoryRoot = string(fileparts(fileparts(mfilename("fullpath"))));
outputRoot = string(java.io.File(char( ...
    fullfile(repositoryRoot,"output"))).getCanonicalPath());
candidate = java.io.File(char(directory));
if ~candidate.isAbsolute()
    candidate = java.io.File(char(fullfile(repositoryRoot,directory)));
end
directory = string(candidate.getCanonicalPath());
if directory ~= outputRoot ...
        && ~startsWith(directory,outputRoot+filesep)
    error("WVTerrainEnergyGalerkin:InvalidAnalyticGlobalTangentCache", ...
        "cacheDirectory must lie inside the repository's untracked output directory.")
end
if isfile(directory)
    error("WVTerrainEnergyGalerkin:InvalidAnalyticGlobalTangentCacheDirectory", ...
        "cacheDirectory must be empty or name a directory.")
end
end
