function audit = auditGlobalTangentStationaryCompression(self,options)
% Audit global tangent-scalar stationary compression.
%
% This Milestone-10.2.5 diagnostic first factors the independent
% polynomial stationary oracle into zero-bottom-trace states and
% energy-minimal lifts of globally terrain-tangent traces. It then tests a
% mixed Dirichlet--Neumann modal compression of the homogeneous interior.
%
% - Topic: Audit global tangent stationary compression
% - Declaration: audit = auditGlobalTangentStationaryCompression(options)
% - Parameter trustedModeBounds: nonnegative integer `[kMax lMax]`
% - Parameter supportModeBounds: increasing retained support bounds
% - Parameter targetWaveModeIndices: positive production wave labels
% - Parameter interiorGeostrophicModeCounts: increasing modal counts
% - Parameter stationaryReferenceDegree: polynomial stationary control degree
% - Parameter primitiveReferenceDegrees: increasing primitive oracle degrees
% - Parameter paddingFactors: horizontal oversampling factors
% - Parameter terrainScales: increasing terrain multipliers from zero to one
% - Parameter internalModesEVPOrders: qualified isolated-provider orders
% - Parameter shouldRunTwoDimensionalControl: run an independent 2-D control
% - Parameter cacheDirectory: optional untracked directory for audit artifacts
% - Parameter quadratureOrder: optional common vertical quadrature order
% - Returns audit: factorization, training, validation, and classification
arguments
    self (1,1) WVTerrainEnergyGalerkin
    options.trustedModeBounds (1,2) double ...
        {mustBeInteger,mustBeNonnegative} = [1 0]
    options.supportModeBounds (:,2) double ...
        {mustBeInteger,mustBeNonnegative} = [1 2;1 3;1 4]
    options.targetWaveModeIndices (:,1) double ...
        {mustBeInteger,mustBePositive} = [1;2]
    options.interiorGeostrophicModeCounts (:,1) double ...
        {mustBeInteger,mustBePositive} = [2;4;6;8;12]
    options.stationaryReferenceDegree (1,1) double ...
        {mustBeInteger,mustBePositive} = 4
    options.primitiveReferenceDegrees (:,1) double ...
        {mustBeInteger,mustBePositive} = [16;18;20]
    options.paddingFactors (:,1) double ...
        {mustBeInteger,mustBePositive} = [2;3]
    options.terrainScales (:,1) double ...
        {mustBeNonnegative} = [0;1/8;1/4;1/2;3/4;1]
    options.internalModesEVPOrders (:,1) double ...
        {mustBeInteger,mustBePositive} = [128;256]
    options.shouldRunTwoDimensionalControl (1,1) logical = true
    options.cacheDirectory (1,1) string = ""
    options.quadratureOrder double {mustBeInteger} = []
end

if size(options.supportModeBounds,1) < 3 ...
        || any(any(diff(options.supportModeBounds,1,1) < 0)) ...
        || any(all(diff(options.supportModeBounds,1,1) == 0,2))
    error("WVTerrainEnergyGalerkin:InvalidGlobalTangentSupport", ...
        "supportModeBounds must contain at least three distinct componentwise-nondecreasing rows.")
end
if any(options.supportModeBounds(1,:) < options.trustedModeBounds)
    error("WVTerrainEnergyGalerkin:InsufficientGlobalTangentSupport", ...
        "Every support bound must contain trustedModeBounds.")
end
if isempty(options.targetWaveModeIndices) ...
        || ~issorted(options.targetWaveModeIndices) ...
        || numel(unique(options.targetWaveModeIndices)) ...
        ~= numel(options.targetWaveModeIndices) ...
        || any(~ismember(options.targetWaveModeIndices, ...
        self.verticalModeIndices))
    error("WVTerrainEnergyGalerkin:InvalidGlobalTangentTargetWaves", ...
        "targetWaveModeIndices must be sorted unique labels retained by the originating transform.")
end
if numel(options.interiorGeostrophicModeCounts) < 3 ...
        || any(diff(options.interiorGeostrophicModeCounts) <= 0)
    error("WVTerrainEnergyGalerkin:InvalidGlobalTangentModeCounts", ...
        "interiorGeostrophicModeCounts must contain at least three increasing values.")
end
if numel(options.primitiveReferenceDegrees) < 3 ...
        || any(diff(options.primitiveReferenceDegrees) <= 0) ...
        || options.stationaryReferenceDegree ...
        > options.primitiveReferenceDegrees(1)
    error("WVTerrainEnergyGalerkin:InvalidGlobalTangentReferenceDegrees", ...
        "primitiveReferenceDegrees must contain at least three increasing values not smaller than stationaryReferenceDegree.")
end
if numel(options.paddingFactors) < 2 ...
        || any(options.paddingFactors < 2) ...
        || numel(unique(options.paddingFactors)) ...
        ~= numel(options.paddingFactors) ...
        || ~all(ismember([2;3],options.paddingFactors))
    error("WVTerrainEnergyGalerkin:InvalidGlobalTangentPadding", ...
        "paddingFactors must contain unique values including two and three.")
end
if numel(options.terrainScales) < 5 ...
        || options.terrainScales(1) ~= 0 ...
        || options.terrainScales(end) ~= 1 ...
        || any(diff(options.terrainScales) <= 0)
    error("WVTerrainEnergyGalerkin:InvalidGlobalTangentTerrainScales", ...
        "terrainScales must contain at least five increasing values beginning at zero and ending at one.")
end
if numel(options.internalModesEVPOrders) < 2 ...
        || any(options.internalModesEVPOrders < 16) ...
        || any(diff(options.internalModesEVPOrders) <= 0) ...
        || any(ismember(options.internalModesEVPOrders,[96;192]))
    error("WVTerrainEnergyGalerkin:InvalidGlobalTangentEVPOrders", ...
        "internalModesEVPOrders must contain increasing qualified values; orders 96 and 192 are excluded.")
end
if isempty(options.quadratureOrder)
    quadratureOrder = max( ...
        2*max(options.primitiveReferenceDegrees)+7, ...
        2*max(options.interiorGeostrophicModeCounts)+15);
elseif ~isscalar(options.quadratureOrder) ...
        || options.quadratureOrder ...
        < 2*max(options.primitiveReferenceDegrees)+3
    error("WVTerrainEnergyGalerkin:InsufficientGlobalTangentQuadrature", ...
        "quadratureOrder must be empty or at least 2*max(primitiveReferenceDegrees)+3.")
else
    quadratureOrder = options.quadratureOrder;
end
if max(abs(self.topographicHeight),[],"all") == 0
    error("WVTerrainEnergyGalerkin:GlobalTangentRequiresTerrain", ...
        "topographicHeight must provide a nonzero terrain direction.")
end
if any(1-options.terrainScales ...
        *max(self.topographicHeight,[],"all") ...
        /self.originatingTransform.Lz <= 0)
    error("WVTerrainEnergyGalerkin:NonpositiveGlobalTangentGamma", ...
        "Every requested terrain scale must satisfy gamma>0.")
end
cacheDirectory = validatedCacheDirectory(options.cacheDirectory);

audit = buildGlobalTangentStationaryCompressionAudit(self, ...
    options.trustedModeBounds,options.supportModeBounds, ...
    options.targetWaveModeIndices, ...
    options.interiorGeostrophicModeCounts, ...
    options.stationaryReferenceDegree, ...
    options.primitiveReferenceDegrees,options.paddingFactors, ...
    options.terrainScales,options.internalModesEVPOrders, ...
    options.shouldRunTwoDimensionalControl,cacheDirectory, ...
    quadratureOrder,"provider");
end

function directory = validatedCacheDirectory(directory)
if directory == ""
    return
end
repositoryRoot = string(fileparts(fileparts(mfilename("fullpath"))));
outputRoot = string(java.io.File(char( ...
    fullfile(repositoryRoot,"output"))).getCanonicalPath());
candidate = java.io.File(char(directory));
if ~candidate.isAbsolute()
    candidate = java.io.File(char(fullfile(repositoryRoot,directory)));
end
directory = string(candidate.getCanonicalPath());
if directory ~= outputRoot ...
        && ~startsWith(directory,outputRoot+filesep)
    error("WVTerrainEnergyGalerkin:InvalidGlobalTangentCacheLocation", ...
        "cacheDirectory must lie inside the repository's untracked output directory.")
end
if isfile(directory)
    error("WVTerrainEnergyGalerkin:InvalidGlobalTangentCacheDirectory", ...
        "cacheDirectory must be empty or name a directory.")
end
end
