function audit = auditCompleteInternalWaveCoverage(self,options)
% Audit complete finite-terrain coverage of the production internal waves.
%
% The diagnostic constructs every declared native flat wave coordinate,
% globally dresses complete signed-frequency blocks, and applies joint
% exact-residual enrichment using the unchanged primitive physical-energy
% forms. An independent-block control measures correction reuse.
%
% ```matlab
% audit = problem.auditCompleteInternalWaveCoverage( ...
%     trustedModeBounds=[1 0], ...
%     supportModeBounds=[1 2;1 3;1 4], ...
%     waveModeIndices=[1;2], ...
%     apvModeIndices=[0;1;2], ...
%     primitivePolynomialDegrees=[4;6;8], ...
%     comparisonPolynomialDegree=12, ...
%     paddingFactors=[2;3]);
% ```
%
% - Topic: Audit complete production internal-wave coverage
% - Declaration: audit = auditCompleteInternalWaveCoverage(options)
% - Parameter trustedModeBounds: nonnegative integer `[kMax lMax]`
% - Parameter supportModeBounds: nested signed-Fourier primitive bounds
% - Parameter waveModeIndices: retained positive native wave labels
% - Parameter apvModeIndices: retained balanced labels including zero
% - Parameter stationaryPolynomialDegree: stationary-space polynomial degree
% - Parameter primitivePolynomialDegrees: increasing primitive audit degrees
% - Parameter comparisonPolynomialDegree: independent dense comparison degree
% - Parameter paddingFactors: horizontal oversampling factors
% - Parameter terrainScales: positive increasing terrain multipliers ending at one
% - Parameter tangentStep: positive centered terrain-derivative step
% - Parameter maximumIterations: maximum exact-residual corrections
% - Parameter quadratureOrder: optional common primitive quadrature order
% - Returns audit: coverage, enrichment, recycling, and physical diagnostics
arguments
    self (1,1) WVTerrainEnergyGalerkin
    options.trustedModeBounds (1,2) double {mustBeInteger,mustBeNonnegative} = [1 0]
    options.supportModeBounds (:,2) double {mustBeInteger,mustBeNonnegative} = [1 2;1 3;1 4]
    options.waveModeIndices (:,1) double {mustBeInteger} = self.verticalModeIndices(self.verticalModeIndices > 0)
    options.apvModeIndices (:,1) double {mustBeInteger} = self.verticalModeIndices
    options.stationaryPolynomialDegree (1,1) double {mustBeInteger,mustBePositive} = 4
    options.primitivePolynomialDegrees (:,1) double {mustBeInteger,mustBePositive} = [4;6;8]
    options.comparisonPolynomialDegree (1,1) double {mustBeInteger,mustBePositive} = 12
    options.paddingFactors (:,1) double {mustBeInteger,mustBePositive} = [2;3]
    options.terrainScales (:,1) double {mustBePositive} = [1/16;1/8;1/4;1/2;1]
    options.tangentStep (1,1) double {mustBePositive} = 1e-3
    options.maximumIterations (1,1) double {mustBeInteger,mustBePositive} = 8
    options.quadratureOrder double {mustBeInteger} = []
end

if isempty(options.waveModeIndices) || any(options.waveModeIndices <= 0) ...
        || ~issorted(options.waveModeIndices) ...
        || numel(unique(options.waveModeIndices)) ~= numel(options.waveModeIndices) ...
        || any(~ismember(options.waveModeIndices,self.verticalModeIndices))
    error("WVTerrainEnergyGalerkin:InvalidCompleteInternalWaveIndices", ...
        "waveModeIndices must be sorted unique positive labels retained by the originating transform.")
end
if isempty(options.apvModeIndices) || options.apvModeIndices(1) ~= 0 ...
        || ~issorted(options.apvModeIndices) ...
        || numel(unique(options.apvModeIndices)) ~= numel(options.apvModeIndices) ...
        || any(~ismember(options.apvModeIndices,self.verticalModeIndices))
    error("WVTerrainEnergyGalerkin:InvalidCompleteInternalAPVIndices", ...
        "apvModeIndices must be sorted unique retained labels and include zero.")
end

contractSupports = options.trustedModeBounds+[0 0;0 1;0 2];
contract = self.auditProductionPhysicalStateContract( ...
    trustedModeBounds=options.trustedModeBounds, ...
    supportModeBounds=contractSupports, ...
    waveModeIndices=options.waveModeIndices, ...
    apvModeIndices=options.apvModeIndices, ...
    primitivePolynomialDegrees=[8;16;24], ...
    paddingFactors=options.paddingFactors);
if ~contract.isCompatible
    error("WVTerrainEnergyGalerkin:IncompleteProductionContract", ...
        "Milestone 10.2 requires a passing Milestone-10.1 production contract.")
end

audit = buildResidualEnrichedTerrainModeAudit(self, ...
    options.trustedModeBounds,options.supportModeBounds, ...
    options.stationaryPolynomialDegree, ...
    options.primitivePolynomialDegrees, ...
    options.comparisonPolynomialDegree,options.paddingFactors, ...
    options.terrainScales,options.tangentStep, ...
    options.maximumIterations,options.quadratureOrder,contract);
end
