function audit = auditSlopeCompatibleWaveModeCompression(self,options)
% Audit trained slope-compatible wave coordinates against the primitive oracle.
%
% This Milestone-9.3 diagnostic compares hydrostatic and nonhydrostatic
% wave coordinates that retain a constant reference slope only in the
% active bottom-displacement row. Robin APV modes, the explicit zero-APV
% bottom inversion, stationary completion, and the final finite-terrain
% physical forms are unchanged from the validated primitive construction.
%
% ```matlab
% audit = problem.auditSlopeCompatibleWaveModeCompression( ...
%     trustedModeBounds=[1 0], ...
%     supportModeBounds=[1 2;1 3;1 4], ...
%     stationaryPolynomialDegree=4, ...
%     primitivePolynomialDegrees=[4;6;8], ...
%     comparisonPolynomialDegree=12, ...
%     modalCounts=[1;2;4;8], ...
%     robinLengthRatios=[-1/8;-1/4;-1/2;-1;Inf], ...
%     referenceSlopeFactors=[0;0.5;1;sqrt(2)], ...
%     dynamics=["hydrostatic";"nonhydrostatic"], ...
%     paddingFactors=[2;3], ...
%     terrainScales=[0.125;0.25;0.5;1], ...
%     internalModesEVPOrders=[128;256]);
% ```
%
% The Robin length and reference slope are selected on the padding-two
% training calculation and then frozen for every independent validation.
% Neither InternalModes checkout is modified.
%
% - Topic: Audit slope-compatible wave-coordinate compression
% - Declaration: audit = auditSlopeCompatibleWaveModeCompression(options)
% - Parameter trustedModeBounds: nonnegative integer `[kMax lMax]`
% - Parameter supportModeBounds: nested signed Fourier bounds
% - Parameter stationaryPolynomialDegree: trusted stationary-space degree
% - Parameter primitivePolynomialDegrees: primitive classification degrees
% - Parameter comparisonPolynomialDegree: primitive comparison degree
% - Parameter modalCounts: paired wave and Robin vertical counts
% - Parameter robinLengthRatios: signed Robin lengths divided by depth
% - Parameter referenceSlopeFactors: nonnegative RMS-slope multipliers
% - Parameter dynamics: hydrostatic and/or nonhydrostatic reference dynamics
% - Parameter paddingFactors: training and validation oversampling factors
% - Parameter terrainScales: terrain-amplitude validation multipliers
% - Parameter internalModesEVPOrders: isolated provider orders
% - Parameter quadratureOrder: optional common primitive quadrature order
% - Returns audit: training, frozen validation, and outcome diagnostics
arguments
    self (1,1) WVTerrainEnergyGalerkin
    options.trustedModeBounds (1,2) double {mustBeInteger,mustBeNonnegative}
    options.supportModeBounds (:,2) double {mustBeInteger,mustBeNonnegative}
    options.stationaryPolynomialDegree (1,1) double {mustBeInteger,mustBePositive}
    options.primitivePolynomialDegrees (:,1) double {mustBeInteger,mustBePositive}
    options.comparisonPolynomialDegree (1,1) double ...
        {mustBeInteger,mustBePositive} = 12
    options.modalCounts (:,1) double {mustBeInteger,mustBePositive} = [1;2;4;8]
    options.robinLengthRatios (:,1) double {mustBeReal} = ...
        [-1/8;-1/4;-1/2;-1;Inf]
    options.referenceSlopeFactors (:,1) double {mustBeReal,mustBeNonnegative} = ...
        [0;0.5;1;sqrt(2)]
    options.dynamics (:,1) string = ["hydrostatic";"nonhydrostatic"]
    options.paddingFactors (:,1) double {mustBeInteger,mustBePositive} = [2;3]
    options.terrainScales (:,1) double {mustBePositive} = [0.125;0.25;0.5;1]
    options.internalModesEVPOrders (:,1) double ...
        {mustBeInteger,mustBePositive} = [128;256]
    options.quadratureOrder double {mustBeInteger} = []
end

if numel(options.primitivePolynomialDegrees) < 3 ...
        || any(diff(options.primitivePolynomialDegrees) <= 0)
    error("WVTerrainEnergyGalerkin:InvalidSlopeCompatibleDegrees", ...
        "primitivePolynomialDegrees must contain at least three strictly increasing values.")
end
if options.comparisonPolynomialDegree ...
        <=max(options.primitivePolynomialDegrees)
    error("WVTerrainEnergyGalerkin:InvalidSlopeCompatibleComparisonDegree", ...
        "comparisonPolynomialDegree must exceed every primitivePolynomialDegrees entry.")
end
if size(options.supportModeBounds,1) ...
        ~=numel(options.primitivePolynomialDegrees) ...
        || any(diff(options.supportModeBounds,1,1) < 0,"all") ...
        || any(~any(diff(options.supportModeBounds,1,1) > 0,2))
    error("WVTerrainEnergyGalerkin:InvalidSlopeCompatibleSupports", ...
        "supportModeBounds must contain one strictly expanding row per primitive degree.")
end
if any(options.trustedModeBounds > options.supportModeBounds(1,:))
    error("WVTerrainEnergyGalerkin:SlopeCompatibleTrustedBandOutsideSupport", ...
        "trustedModeBounds must lie inside every supportModeBounds row.")
end
if numel(options.modalCounts) < 2 || any(diff(options.modalCounts) <= 0)
    error("WVTerrainEnergyGalerkin:InvalidSlopeCompatibleCounts", ...
        "modalCounts must contain at least two strictly increasing positive integers.")
end
if any(isnan(options.robinLengthRatios)) ...
        || any(isinf(options.robinLengthRatios) ...
        &options.robinLengthRatios < 0) ...
        || any(options.robinLengthRatios == 0) ...
        || numel(unique(options.robinLengthRatios)) ...
        ~=numel(options.robinLengthRatios)
    error("WVTerrainEnergyGalerkin:InvalidSlopeCompatibleRobinLengths", ...
        "robinLengthRatios must contain unique finite nonzero values or Inf.")
end
if isempty(options.referenceSlopeFactors) ...
        || any(~isfinite(options.referenceSlopeFactors)) ...
        || numel(unique(options.referenceSlopeFactors)) ...
        ~=numel(options.referenceSlopeFactors)
    error("WVTerrainEnergyGalerkin:InvalidReferenceSlopeFactors", ...
        "referenceSlopeFactors must contain unique finite nonnegative values.")
end
if ~all(ismember(options.dynamics,["hydrostatic","nonhydrostatic"])) ...
        || numel(unique(options.dynamics)) ~= numel(options.dynamics)
    error("WVTerrainEnergyGalerkin:InvalidSlopeCompatibleDynamics", ...
        "dynamics may contain unique hydrostatic and nonhydrostatic values.")
end
if numel(options.paddingFactors) < 2 ...
        || options.paddingFactors(1) ~= 2 ...
        || any(options.paddingFactors < 2) ...
        || numel(unique(options.paddingFactors)) ...
        ~=numel(options.paddingFactors)
    error("WVTerrainEnergyGalerkin:InvalidSlopeCompatiblePadding", ...
        "paddingFactors must begin at two and contain at least two unique values.")
end
if numel(options.terrainScales) < 4 ...
        || any(~isfinite(options.terrainScales)) ...
        || any(diff(options.terrainScales) <= 0) ...
        || options.terrainScales(end) ~= 1
    error("WVTerrainEnergyGalerkin:InvalidSlopeCompatibleTerrainScales", ...
        "terrainScales must contain at least four increasing values ending at one.")
end
if numel(options.internalModesEVPOrders) < 2 ...
        || any(options.internalModesEVPOrders < 16) ...
        || any(diff(options.internalModesEVPOrders) <= 0) ...
        || any(ismember(options.internalModesEVPOrders,[96;192]))
    error("WVTerrainEnergyGalerkin:InvalidSlopeCompatibleEVPOrders", ...
        "Use at least two increasing qualified EVP orders; 96 and 192 are excluded at provider commit df86687.")
end
if ~isempty(options.quadratureOrder) ...
        &&(~isscalar(options.quadratureOrder) ...
        ||options.quadratureOrder ...
        <2*options.comparisonPolynomialDegree+3)
    error("WVTerrainEnergyGalerkin:InsufficientSlopeCompatibleQuadrature", ...
        "quadratureOrder must be empty or at least 2*comparisonPolynomialDegree+3.")
end

audit = buildSlopeCompatibleWaveModeCompressionAudit(self, ...
    options.trustedModeBounds,options.supportModeBounds, ...
    options.stationaryPolynomialDegree, ...
    options.primitivePolynomialDegrees, ...
    options.comparisonPolynomialDegree,options.modalCounts, ...
    options.robinLengthRatios,options.referenceSlopeFactors, ...
    options.dynamics,options.paddingFactors,options.terrainScales, ...
    options.internalModesEVPOrders,options.quadratureOrder);
end
