function audit = auditConvergedPhysicalSubspaces(self,options)
% Audit convergence of physical stationary and dynamical terrain subspaces.
%
% This Milestone-9.1 diagnostic preserves the complete dense
% physical-energy eigensystem while comparing nested stationary and
% dynamical spectral subspaces through physical-energy projectors and
% principal angles. Modes that do not pass the physical convergence gates
% remain in the unresolved algebraic completion.
%
% ```matlab
% audit = problem.auditConvergedPhysicalSubspaces( ...
%     trustedModeBounds=[1 0], ...
%     supportModeBounds=[1 2;1 3;1 4], ...
%     stationaryPolynomialDegree=4, ...
%     primitivePolynomialDegrees=[4;6;8], ...
%     paddingFactors=[2;3], ...
%     terrainScales=[0.125;0.25;0.5;1]);
% ```
%
% For coefficient columns `A`, the unresolved physical-energy fraction is
% obtained from
%
% ```matlab
% forms = audit.classification.energyForms;
% unresolvedFraction = real(sum(conj(A).*(forms.remainder*A),1)) ...
%     ./real(sum(conj(A).*(audit.finest.energyMatrix*A),1));
% ```
%
% - Topic: Audit converged physical terrain subspaces
% - Declaration: audit = auditConvergedPhysicalSubspaces(options)
% - Parameter trustedModeBounds: nonnegative integer `[kMax lMax]`
% - Parameter supportModeBounds: retained signed Fourier bounds by refinement
% - Parameter stationaryPolynomialDegree: fixed trusted stationary-space degree
% - Parameter primitivePolynomialDegrees: increasing primitive support degrees
% - Parameter paddingFactors: horizontal oversampling factors
% - Parameter terrainScales: positive increasing terrain multipliers including one
% - Parameter quadratureOrder: optional common Gauss--Legendre order
% - Returns audit: converged physical projectors and unresolved-remainder diagnostics
arguments
    self (1,1) WVTerrainEnergyGalerkin
    options.trustedModeBounds (1,2) double {mustBeInteger,mustBeNonnegative}
    options.supportModeBounds (:,2) double {mustBeInteger,mustBeNonnegative}
    options.stationaryPolynomialDegree (1,1) double ...
        {mustBeInteger,mustBePositive}
    options.primitivePolynomialDegrees (:,1) double ...
        {mustBeInteger,mustBePositive}
    options.paddingFactors (:,1) double ...
        {mustBeInteger,mustBePositive} = [2;3]
    options.terrainScales (:,1) double ...
        {mustBePositive} = [0.125;0.25;0.5;1]
    options.quadratureOrder double {mustBeInteger} = []
end

degrees = options.primitivePolynomialDegrees;
supports = options.supportModeBounds;
if numel(degrees) < 3 || any(diff(degrees) <= 0) ...
        || any(degrees < options.stationaryPolynomialDegree)
    error("WVTerrainEnergyGalerkin:InvalidPhysicalSubspaceDegrees", ...
        "primitivePolynomialDegrees must contain at least three strictly increasing values no smaller than stationaryPolynomialDegree.")
end
if size(supports,1) ~= numel(degrees) ...
        || any(diff(supports,1,1) < 0,"all") ...
        || any(~any(diff(supports,1,1) > 0,2))
    error("WVTerrainEnergyGalerkin:InvalidPhysicalSubspaceSupports", ...
        "supportModeBounds must have one strictly expanding nested row per primitivePolynomialDegrees entry.")
end
if any(options.trustedModeBounds > supports(1,:))
    error("WVTerrainEnergyGalerkin:PhysicalSubspaceTrustedBandOutsideSupport", ...
        "trustedModeBounds must lie inside every supportModeBounds row.")
end
if numel(options.paddingFactors) < 2 ...
        || any(options.paddingFactors < 2) ...
        || numel(unique(options.paddingFactors)) ...
        ~= numel(options.paddingFactors)
    error("WVTerrainEnergyGalerkin:InvalidPhysicalSubspacePadding", ...
        "paddingFactors must contain at least two unique values of two or greater.")
end
scales = options.terrainScales;
if numel(scales) < 4 || any(~isfinite(scales)) ...
        || any(diff(scales) <= 0) || scales(end) ~= 1
    error("WVTerrainEnergyGalerkin:InvalidPhysicalSubspaceScales", ...
        "terrainScales must contain at least four finite, positive, strictly increasing values ending at one.")
end
if any(1-scales*max(self.topographicHeight,[],"all") ...
        /self.originatingTransform.Lz <= 0)
    error("WVTerrainEnergyGalerkin:NonpositivePhysicalSubspaceGamma", ...
        "Every requested terrain scale must satisfy gamma>0.")
end
if ~isempty(options.quadratureOrder) ...
        && (~isscalar(options.quadratureOrder) ...
        || options.quadratureOrder < 2*max(degrees)+3)
    error("WVTerrainEnergyGalerkin:InsufficientPhysicalSubspaceQuadrature", ...
        "quadratureOrder must be empty or at least 2*max(primitivePolynomialDegrees)+3.")
end

dense = buildDensePhysicalEnergyTerrainModeAudit(self, ...
    options.trustedModeBounds,supports, ...
    options.stationaryPolynomialDegree,degrees, ...
    options.paddingFactors,scales,options.quadratureOrder,true);
flatProblem = WVTerrainEnergyGalerkin.fromTopography( ...
    self.originatingTransform, ...
    topographicHeight=zeros(size(self.topographicHeight)), ...
    verticalModeIndices=self.verticalModeIndices, ...
    horizontalOversamplingFactor=self.horizontalOversamplingFactor);
flat = buildDensePhysicalEnergyTerrainModeAudit(flatProblem, ...
    options.trustedModeBounds,supports, ...
    options.stationaryPolynomialDegree,degrees, ...
    options.paddingFactors,1,options.quadratureOrder,true);
guardSupports = supports(end-1:end,:);
guardDegrees = repmat(degrees(end),2,1);
guard = buildDensePhysicalEnergyTerrainModeAudit(self, ...
    options.trustedModeBounds,guardSupports, ...
    options.stationaryPolynomialDegree,guardDegrees, ...
    options.paddingFactors(1),1,options.quadratureOrder,true);

audit = buildConvergedPhysicalSubspaceClassificationAudit( ...
    dense,flat,guard);
end
