function audit = auditWKBPrimitiveForwardState(self,options)
% Compare complete WKB--Chebyshev and Legendre primitive states.
%
% This Milestone-10.2.6 diagnostic retains every admissible primitive
% coordinate and changes only the horizontally independent vertical
% coordinate used to represent it. Both representations use the same
% finite-terrain physical forms and dealiased horizontal projection.
%
% ```matlab
% audit = problem.auditWKBPrimitiveForwardState( ...
%     trustedModeBounds=[1 0], ...
%     supportModeBounds=[1 2;1 3;1 4], ...
%     verticalDegrees=[6;8;12;16;24], ...
%     legendreReferenceDegrees=[12;16;20;24], ...
%     paddingFactors=[2;3], ...
%     terrainScales=[0;1/8;1/4;1/2;3/4;1], ...
%     cacheDirectory="output/milestone-10.2.6-cache");
% ```
%
% - Topic: Audit a complete WKB primitive state
% - Declaration: audit = auditWKBPrimitiveForwardState(options)
% - Parameter trustedModeBounds: nonnegative integer `[kMax lMax]`
% - Parameter supportModeBounds: nested retained Fourier bounds
% - Parameter verticalDegrees: increasing WKB--Chebyshev degrees
% - Parameter legendreReferenceDegrees: increasing Legendre degrees
% - Parameter paddingFactors: horizontal oversampling factors
% - Parameter terrainScales: increasing terrain multipliers zero to one
% - Parameter cacheDirectory: optional untracked resumable cache directory
% - Returns audit: complete-state convergence, selection, and classification
arguments
    self (1,1) WVTerrainEnergyGalerkin
    options.trustedModeBounds (1,2) double ...
        {mustBeInteger,mustBeNonnegative} = [1 0]
    options.supportModeBounds (:,2) double ...
        {mustBeInteger,mustBeNonnegative} = [1 2;1 3;1 4]
    options.verticalDegrees (:,1) double ...
        {mustBeInteger,mustBePositive} = [6;8;12;16;24]
    options.legendreReferenceDegrees (:,1) double ...
        {mustBeInteger,mustBePositive} = [12;16;20;24]
    options.paddingFactors (:,1) double ...
        {mustBeInteger,mustBePositive} = [2;3]
    options.terrainScales (:,1) double ...
        {mustBeNonnegative} = [0;1/8;1/4;1/2;3/4;1]
    options.cacheDirectory (1,1) string = ""
end

validateNestedControls(self,options);
cacheDirectory = validatedCacheDirectory(options.cacheDirectory);
audit = buildWKBPrimitiveForwardStateAudit(self, ...
    options.trustedModeBounds,options.supportModeBounds, ...
    options.verticalDegrees,options.legendreReferenceDegrees, ...
    options.paddingFactors,options.terrainScales,cacheDirectory);
end

function validateNestedControls(self,options)
if size(options.supportModeBounds,1) < 2 ...
        || any(diff(options.supportModeBounds,1,1) < 0,"all") ...
        || any(~any(diff(options.supportModeBounds,1,1) > 0,2))
    error("WVTerrainEnergyGalerkin:InvalidWKBPrimitiveSupport", ...
        "supportModeBounds must contain at least two strictly expanding nested rows.")
end
if any(options.trustedModeBounds > options.supportModeBounds(1,:))
    error("WVTerrainEnergyGalerkin:WKBPrimitiveTrustedBandOutsideSupport", ...
        "trustedModeBounds must lie inside every supportModeBounds row.")
end
if numel(options.verticalDegrees) < 3 ...
        || options.verticalDegrees(1) < 2 ...
        || any(diff(options.verticalDegrees) <= 0)
    error("WVTerrainEnergyGalerkin:InvalidWKBPrimitiveDegrees", ...
        "verticalDegrees must contain at least three increasing values.")
end
if numel(options.legendreReferenceDegrees) < 3 ...
        || options.legendreReferenceDegrees(1) < 2 ...
        || any(diff(options.legendreReferenceDegrees) <= 0)
    error("WVTerrainEnergyGalerkin:InvalidWKBPrimitiveReferenceDegrees", ...
        "legendreReferenceDegrees must contain at least three increasing values.")
end
if isempty(intersect(options.verticalDegrees, ...
        options.legendreReferenceDegrees))
    error("WVTerrainEnergyGalerkin:MissingWKBPrimitiveCommonDegree", ...
        "At least one vertical degree must be shared for the constant-N equivalence control.")
end
if numel(options.paddingFactors) < 2 ...
        || numel(unique(options.paddingFactors)) ~= numel(options.paddingFactors) ...
        || ~all(ismember([2;3],options.paddingFactors))
    error("WVTerrainEnergyGalerkin:InvalidWKBPrimitivePadding", ...
        "paddingFactors must contain unique values including two and three.")
end
if numel(options.terrainScales) < 3 ...
        || options.terrainScales(1) ~= 0 ...
        || options.terrainScales(end) ~= 1 ...
        || any(diff(options.terrainScales) <= 0)
    error("WVTerrainEnergyGalerkin:InvalidWKBPrimitiveTerrainScales", ...
        "terrainScales must increase from zero through one.")
end
if any(1-options.terrainScales ...
        *max(self.topographicHeight,[],"all") ...
        /self.originatingTransform.Lz <= 0)
    error("WVTerrainEnergyGalerkin:NonpositiveWKBPrimitiveGamma", ...
        "Every requested terrain scale must satisfy gamma>0.")
end
end

function directory = validatedCacheDirectory(directory)
if directory == ""
    return
end
repositoryRoot = string(fileparts(fileparts(mfilename("fullpath"))));
outputRoot = string(java.io.File(char( ...
    fullfile(repositoryRoot,"output"))).getCanonicalPath());
candidate = java.io.File(char(directory));
if ~candidate.isAbsolute()
    candidate = java.io.File(char(fullfile(repositoryRoot,directory)));
end
directory = string(candidate.getCanonicalPath());
if directory ~= outputRoot ...
        && ~startsWith(directory,outputRoot+filesep)
    error("WVTerrainEnergyGalerkin:InvalidWKBPrimitiveCache", ...
        "cacheDirectory must lie inside the repository's untracked output directory.")
end
if isfile(directory)
    error("WVTerrainEnergyGalerkin:InvalidWKBPrimitiveCacheDirectory", ...
        "cacheDirectory must be empty or name a directory.")
end
end
