classdef TestWVTerrainEnergyCompleteInternalWaveCoverage < matlab.unittest.TestCase
    % Verify the Milestone-10.2 split-control oracle and blocker.

    properties
        problem
        zonal
        horizontal
        horizontalLayout
        stateLayout
    end

    methods (TestClassSetup)
        function createSplitControlAudits(testCase)
            addpath(fileparts(fileparts(mfilename("fullpath"))));
            testCase.problem = ...
                TestWVTerrainEnergyCompleteInternalWaveCoverage.createProblem;
            testCase.horizontalLayout = testCase.problem.horizontalLayout;
            testCase.stateLayout = testCase.problem.stateLayout;
            testCase.zonal = testCase.problem. ...
                auditCompleteInternalWaveCoverage( ...
                trustedModeBounds=[1 0],waveModeIndices=[1;2], ...
                apvModeIndices=[0;1;2], ...
                supportModeBounds=[1 2;1 3;1 4], ...
                primitivePolynomialDegrees=[4;5;6], ...
                comparisonPolynomialDegree=8, ...
                paddingFactors=[2;3],maximumIterations=4);
            testCase.horizontal = testCase.problem. ...
                auditCompleteInternalWaveCoverage( ...
                trustedModeBounds=[1 1],waveModeIndices=1, ...
                apvModeIndices=[0;1], ...
                supportModeBounds=[1 2;1 3;1 4], ...
                primitivePolynomialDegrees=[4;5;6], ...
                comparisonPolynomialDegree=8, ...
                paddingFactors=[2;3],maximumIterations=4);
        end
    end

    methods (Test)
        function splitControlsExposeNumericalBlocker(testCase)
            testCase.verifyTrue(ismember(testCase.zonal.classification, ...
                ["internal-wave-isolation-blocker", ...
                "internal-wave-numerical-blocker"]))
            testCase.verifyTrue(ismember(testCase.horizontal.classification, ...
                ["internal-wave-isolation-blocker", ...
                "internal-wave-numerical-blocker"]))
            testCase.verifyFalse(testCase.zonal.isCompatible)
            testCase.verifyFalse(testCase.horizontal.isCompatible)
            testCase.verifyEqual(testCase.zonal.nextScope, ...
                "milestone-10.2-reformulation")
        end

        function declaredCoverageDimensionsAreRetained(testCase)
            testCase.verifyEqual( ...
                testCase.zonal.numberOfDeclaredInternalWaveCoordinates,8)
            testCase.verifyEqual( ...
                testCase.zonal.numberOfValidatedInternalWaveCoordinates,8)
            testCase.verifyEqual( ...
                testCase.horizontal.numberOfDeclaredInternalWaveCoordinates,16)
            testCase.verifyEqual( ...
                testCase.horizontal.numberOfValidatedInternalWaveCoordinates,16)
            testCase.verifyEqual(height(testCase.zonal.coverageTable),8)
            testCase.verifyEqual(height(testCase.horizontal.coverageTable),16)
        end

        function nativeTargetConstructionIsCompatible(testCase)
            for audit = {testCase.zonal,testCase.horizontal}
                value = audit{1};
                testCase.verifyLessThan( ...
                    max(value.productionTargetNativeMatchDefect),5e-10)
                testCase.verifyLessThan( ...
                    value.productionTargetEmbeddingDefect(end),1e-4)
                testCase.verifyLessThan( ...
                    max(value.productionTargetEnergyOrthogonalityDefect),1e-12)
            end
        end

        function zonalControlDoesNotRecycleDirections(testCase)
            economy = testCase.zonal.economy;
            testCase.verifyLessThanOrEqual(economy.savedTrialDirections,0)
            testCase.verifyGreaterThanOrEqual( ...
                economy.jointTrialDimension, ...
                economy.independentTrialDimension)
            testCase.verifyTrue(isfinite(economy.projectorDefect))
        end

        function horizontalControlLocalizesFailedBlock(testCase)
            blocks = testCase.horizontal.independentBlockTable;
            testCase.verifyTrue(any(blocks.passesPhysicalGates))
            testCase.verifyTrue(any(~blocks.passesPhysicalGates))
            testCase.verifyGreaterThan( ...
                max(blocks.projectorDefect),1e-2)
        end

        function exactFiniteTerrainFormsRemainStructured(testCase)
            for audit = {testCase.zonal,testCase.horizontal}
                value = audit{1};
                testCase.verifyLessThan( ...
                    value.primary.energyHermitianDefect,1e-12)
                testCase.verifyLessThan( ...
                    value.primary.exchangeSkewHermitianDefect,1e-12)
                testCase.verifyLessThan( ...
                    value.primary.stationaryRowDefect,1e-10)
            end
        end

        function publicLayoutsRemainUnchanged(testCase)
            testCase.verifyEqual(testCase.problem.horizontalLayout, ...
                testCase.horizontalLayout)
            testCase.verifyEqual(testCase.problem.stateLayout, ...
                testCase.stateLayout)
        end

        function validationRejectsIncompleteInputs(testCase)
            testCase.verifyError(@() ...
                testCase.problem.auditCompleteInternalWaveCoverage( ...
                waveModeIndices=0), ...
                "WVTerrainEnergyGalerkin:InvalidCompleteInternalWaveIndices")
            testCase.verifyError(@() ...
                testCase.problem.auditCompleteInternalWaveCoverage( ...
                apvModeIndices=1), ...
                "WVTerrainEnergyGalerkin:InvalidCompleteInternalAPVIndices")
        end
    end

    methods (Static)
        function problem = createProblem
            N0 = sqrt(2e-5);
            z = linspace(-1200,0,5)';
            wvt = WVTransformBoussinesq( ...
                [24e3 20e3 1200],[6 10 5], ...
                N2Function=@(z)N0^2+0*z,latitude=45, ...
                shouldAntialias=false,z=z);
            [~,y] = ndgrid((0:wvt.Nx-1)'*wvt.Lx/wvt.Nx, ...
                (0:wvt.Ny-1)'*wvt.Ly/wvt.Ny);
            problem = WVTerrainEnergyGalerkin.fromTopography( ...
                wvt,topographicHeight=2.5*cos(2*pi*y/wvt.Ly));
        end
    end
end
