classdef TestWVTerrainEnergyTerrainDressedRobinStationaryAmbient < matlab.unittest.TestCase
    % Verify the Milestone-10.2.4 trained Robin stationary-coordinate audit.

    properties
        problem
        firstAudit
        cachedAudit
        cacheDirectory
        providerPath
        horizontalLayout
        stateLayout
    end

    methods (TestClassSetup)
        function createDressedRobinAudit(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            addpath(repositoryRoot);
            if ~isfolder(fullfile(repositoryRoot,"output"))
                mkdir(fullfile(repositoryRoot,"output"));
            end
            testCase.cacheDirectory = string(tempname( ...
                fullfile(repositoryRoot,"output")));
            testCase.providerPath = string(fullfile( ...
                repositoryRoot,"..","internal-modes-evp"));
            testCase.problem = ...
                TestWVTerrainEnergyTerrainDressedRobinStationaryAmbient. ...
                createProblem(testCase.providerPath);
            testCase.horizontalLayout = testCase.problem.horizontalLayout;
            testCase.stateLayout = testCase.problem.stateLayout;
            args = ...
                TestWVTerrainEnergyTerrainDressedRobinStationaryAmbient. ...
                reducedArguments(testCase.cacheDirectory);
            testCase.firstAudit = testCase.problem. ...
                auditTerrainDressedRobinStationaryAmbient(args{:});
            testCase.cachedAudit = testCase.problem. ...
                auditTerrainDressedRobinStationaryAmbient(args{:});
        end
    end

    methods (TestClassTeardown)
        function removeCache(testCase)
            if isfolder(testCase.cacheDirectory)
                rmdir(testCase.cacheDirectory,"s");
            end
            if contains(path,testCase.providerPath)
                rmpath(testCase.providerPath)
            end
        end
    end

    methods (Test)
        function outcomeUsesApprovedClassification(testCase)
            allowed = ["dressed-robin-acceleration", ...
                "dressed-flat-acceleration","dressed-stationary-equivalent", ...
                "dressed-stationary-seed","dressed-stationary-blocker"];
            testCase.verifyTrue(ismember( ...
                testCase.firstAudit.classification,allowed))
            testCase.verifyEqual(testCase.firstAudit.status, ...
                testCase.firstAudit.classification)
        end

        function trainingUsesStationaryAblationsAndFreezesLength(testCase)
            training = testCase.firstAudit.training;
            testCase.verifySize(training.results,[3 3])
            testCase.verifyEqual(string({training.results(1,:).ablation}), ...
                ["ordinary-flat" "robin-undressed" "robin-dressed"])
            testCase.verifyEqual(testCase.firstAudit. ...
                selectedRobinLengthRatio,training. ...
                selectedRobinLengthRatio)
            selected = training.results(training.selectedIndex,3);
            testCase.verifyGreaterThan( ...
                selected.numberOfTangentCoordinates,0)
            testCase.verifyLessThan(selected.dressedTangentDefect,1e-10)
            testCase.verifyLessThan( ...
                selected.maximumCenteredDerivativeDefect,1e-9)
        end

        function providerAndBoundaryCoordinateRemainIndependent(testCase)
            selected = testCase.firstAudit.training.results( ...
                testCase.firstAudit.training.selectedIndex,3);
            testCase.verifyLessThan(selected.provider.providerDifference,1e-10)
            testCase.verifyLessThan( ...
                selected.provider.maximumEndpointDefect,1e-10)
            testCase.verifyEqual( ...
                selected.provider.negativeRobinModeCountDefect,0)
            testCase.verifyTrue(selected.fullRank)
        end

        function cacheIsOptInAndContentAddressed(testCase)
            first = testCase.firstAudit.cache;
            second = testCase.cachedAudit.cache;
            testCase.verifyTrue(first.enabled)
            testCase.verifyGreaterThan(first.numberOfMisses,0)
            testCase.verifyEqual(second.numberOfMisses,0)
            testCase.verifyEqual(second.numberOfHits,first.numberOfMisses)
            testCase.verifyGreaterThan(second.secondsSaved,0)
            testCase.verifyTrue(all(isfile(string({second.records.path}))))
        end

        function publicLayoutsRemainUnchanged(testCase)
            testCase.verifyEqual(testCase.problem.horizontalLayout, ...
                testCase.horizontalLayout)
            testCase.verifyEqual(testCase.problem.stateLayout, ...
                testCase.stateLayout)
        end

        function validationRejectsForbiddenInputs(testCase)
            testCase.verifyError(@() testCase.problem. ...
                auditTerrainDressedRobinStationaryAmbient( ...
                robinLengthRatios=[-1/4;Inf]), ...
                "WVTerrainEnergyGalerkin:InvalidDressedRobinLengths")
            testCase.verifyError(@() testCase.problem. ...
                auditTerrainDressedRobinStationaryAmbient( ...
                cacheDirectory=tempdir), ...
                "WVTerrainEnergyGalerkin:InvalidDressedRobinCacheLocation")
            testCase.verifyError(@() testCase.problem. ...
                auditTerrainDressedRobinStationaryAmbient( ...
                internalModesEVPOrders=[96;128]), ...
                "WVTerrainEnergyGalerkin:InvalidDressedRobinEVPOrders")
        end
    end

    methods (Static)
        function args = reducedArguments(cacheDirectory)
            args = { ...
                "trustedModeBounds",[1 0], ...
                "supportModeBounds",[1 1;1 2;1 3], ...
                "targetWaveModeIndices",1, ...
                "waveGuardModeCounts",[1;2;3], ...
                "geostrophicModeCounts",[1;2;3], ...
                "robinLengthRatios",[-1/4;-1/2;Inf], ...
                "trainingGeostrophicModeCount",2, ...
                "primitiveReferenceDegrees",[2;3;4], ...
                "paddingFactors",[2;3], ...
                "terrainScales",[0;1/8;1/4;1/2;1], ...
                "internalModesEVPOrders",[64;128], ...
                "shouldRunTwoDimensionalControl",false, ...
                "cacheDirectory",cacheDirectory};
        end

        function problem = createProblem(providerPath)
            N0 = sqrt(2e-5);
            z = linspace(-1200,0,5)';
            wvt = WVTransformBoussinesq( ...
                [24e3 20e3 1200],[4 8 5], ...
                N2Function=@(z)N0^2+0*z,latitude=45, ...
                shouldAntialias=false,z=z);
            addpath(providerPath,"-end")
            [~,y] = ndgrid((0:wvt.Nx-1)'*wvt.Lx/wvt.Nx, ...
                (0:wvt.Ny-1)'*wvt.Ly/wvt.Ny);
            problem = WVTerrainEnergyGalerkin.fromTopography( ...
                wvt,topographicHeight=2.5*cos(2*pi*y/wvt.Ly));
        end
    end
end
