classdef TestWVTerrainEnergyWaveVortexModalAmbient < matlab.unittest.TestCase
    % Verify the Milestone-10.2.3 flat wave-vortex modal ambient oracle.

    properties
        problem
        firstAudit
        cachedAudit
        cacheDirectory
        providerPath
        horizontalLayout
        stateLayout
    end

    methods (TestClassSetup)
        function createModalAmbientAudit(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            addpath(repositoryRoot);
            if ~isfolder(fullfile(repositoryRoot,"output"))
                mkdir(fullfile(repositoryRoot,"output"));
            end
            testCase.cacheDirectory = string(tempname( ...
                fullfile(repositoryRoot,"output")));
            testCase.providerPath = string(fullfile( ...
                repositoryRoot,"..","internal-modes-evp"));
            testCase.problem = ...
                TestWVTerrainEnergyWaveVortexModalAmbient.createProblem( ...
                testCase.providerPath);
            testCase.horizontalLayout = testCase.problem.horizontalLayout;
            testCase.stateLayout = testCase.problem.stateLayout;
            args = TestWVTerrainEnergyWaveVortexModalAmbient. ...
                reducedArguments(testCase.cacheDirectory);
            testCase.firstAudit = testCase.problem. ...
                auditWaveVortexModalAmbient(args{:});
            testCase.cachedAudit = testCase.problem. ...
                auditWaveVortexModalAmbient(args{:});
        end
    end

    methods (TestClassTeardown)
        function removeCache(testCase)
            if isfolder(testCase.cacheDirectory)
                rmdir(testCase.cacheDirectory,"s");
            end
            if contains(path,testCase.providerPath)
                rmpath(testCase.providerPath)
            end
        end
    end

    methods (Test)
        function outcomeUsesApprovedClassification(testCase)
            allowed = ["wave-vortex-modal-acceleration", ...
                "wave-vortex-modal-equivalent","wave-modal-blocker", ...
                "geostrophic-modal-blocker", ...
                "primitive-reference-blocker","provider-blocker"];
            testCase.verifyTrue(ismember( ...
                testCase.firstAudit.classification,allowed))
            testCase.verifyEqual(testCase.firstAudit.status, ...
                testCase.firstAudit.classification)
            testCase.verifyEqual(testCase.firstAudit.nextScope, ...
                "milestone-10.2.3-stop-for-review")
        end

        function modalFamiliesAndIndependentReferenceArePresent(testCase)
            audit = testCase.firstAudit;
            testCase.verifyEqual(audit.internalModesEVPCommit, ...
                "df86687e91faa31bf65941299062d125a96904b1")
            testCase.verifyEqual(audit.primary.provider.robinLength,Inf)
            testCase.verifyGreaterThan( ...
                audit.primary.primary.numberOfStationaryCoordinates,0)
            testCase.verifyGreaterThan( ...
                audit.primary.primary.numberOfDynamicalCoordinates,0)
            testCase.verifyEqual( ...
                audit.primary.reference.numberOfCoordinates,4)
            testCase.verifyLessThan( ...
                audit.primary.primary.energyHermitianDefect,1e-12)
            testCase.verifyLessThan( ...
                audit.primary.primary.exchangeSkewHermitianDefect,1e-12)
        end

        function independentWaveAndGeostrophicTailsAreReported(testCase)
            audit = testCase.firstAudit;
            testCase.verifySize(audit.convergence.waveProjectorDefect,[3 1])
            testCase.verifySize( ...
                audit.convergence.geostrophicProjectorDefect,[3 1])
            testCase.verifySize(audit.convergence.pairedProjectorDefect,[3 1])
            testCase.verifyEqual([audit.primary.waveSweep.waveModeCount].', ...
                [1;2;3])
            testCase.verifyEqual( ...
                [audit.primary.geostrophicSweep.geostrophicModeCount].', ...
                [1;2;3])
        end

        function cacheIsOptInAndContentAddressed(testCase)
            first = testCase.firstAudit.cache;
            second = testCase.cachedAudit.cache;
            testCase.verifyTrue(first.enabled)
            testCase.verifyGreaterThan(first.numberOfMisses,0)
            testCase.verifyEqual(second.numberOfMisses,0)
            testCase.verifyEqual(second.numberOfHits,first.numberOfMisses)
            testCase.verifyGreaterThan(second.secondsSaved,0)
            testCase.verifyTrue(all(isfile(string({second.records.path}))))
        end

        function publicLayoutsRemainUnchanged(testCase)
            testCase.verifyEqual(testCase.problem.horizontalLayout, ...
                testCase.horizontalLayout)
            testCase.verifyEqual(testCase.problem.stateLayout, ...
                testCase.stateLayout)
        end

        function validationRejectsForbiddenInputs(testCase)
            testCase.verifyError(@() testCase.problem. ...
                auditWaveVortexModalAmbient( ...
                waveGuardModeCounts=[1;2]), ...
                "WVTerrainEnergyGalerkin:InvalidModalAmbientWaveCounts")
            testCase.verifyError(@() testCase.problem. ...
                auditWaveVortexModalAmbient( ...
                internalModesEVPOrders=[96;128]), ...
                "WVTerrainEnergyGalerkin:UnqualifiedModalAmbientEVPOrder")
            testCase.verifyError(@() testCase.problem. ...
                auditWaveVortexModalAmbient(cacheDirectory=tempdir), ...
                "WVTerrainEnergyGalerkin:InvalidModalAmbientCacheLocation")
        end
    end

    methods (Static)
        function args = reducedArguments(cacheDirectory)
            args = { ...
                "trustedModeBounds",[1 0], ...
                "targetWaveModeIndices",1, ...
                "waveGuardModeCounts",[1;2;3], ...
                "geostrophicModeCounts",[1;2;3], ...
                "scatteringOrders",[1;2;3], ...
                "primitiveReferenceDegrees",[2;3;4], ...
                "paddingFactors",[2;3], ...
                "terrainScales",[0;1/8;1/4;1/2;1], ...
                "internalModesEVPOrders",[64;128], ...
                "shouldRunTwoDimensionalControl",false, ...
                "cacheDirectory",cacheDirectory};
        end

        function problem = createProblem(providerPath)
            N0 = sqrt(2e-5);
            z = linspace(-1200,0,5)';
            wvt = WVTransformBoussinesq( ...
                [24e3 20e3 1200],[4 8 5], ...
                N2Function=@(z)N0^2+0*z,latitude=45, ...
                shouldAntialias=false,z=z);
            addpath(providerPath,"-end")
            [~,y] = ndgrid((0:wvt.Nx-1)'*wvt.Lx/wvt.Nx, ...
                (0:wvt.Ny-1)'*wvt.Ly/wvt.Ny);
            problem = WVTerrainEnergyGalerkin.fromTopography( ...
                wvt,topographicHeight=2.5*cos(2*pi*y/wvt.Ly));
        end
    end
end
