classdef TestWVTerrainEnergySlopeCompatibleWaveModeCompression < matlab.unittest.TestCase
    % Verify the Milestone-9.3 slope-compatible wave-coordinate oracle.

    properties
        problem
        audit
        horizontalLayout
        stateLayout
    end

    methods (TestClassSetup)
        function createSlopeCompatibleAudit(testCase)
            addpath(fileparts(fileparts(mfilename("fullpath"))));
            N0 = sqrt(2e-5);
            z = linspace(-1200,0,5)';
            wvt = WVTransformBoussinesq( ...
                [24e3 20e3 1200],[6 10 5], ...
                N2Function=@(z)N0^2+0*z,latitude=45, ...
                shouldAntialias=false,z=z);
            [~,y] = ndgrid((0:wvt.Nx-1)'*wvt.Lx/wvt.Nx, ...
                (0:wvt.Ny-1)'*wvt.Ly/wvt.Ny);
            terrain = 2.5*cos(2*pi*y/wvt.Ly);
            testCase.problem = WVTerrainEnergyGalerkin.fromTopography( ...
                wvt,topographicHeight=terrain);
            testCase.horizontalLayout = testCase.problem.horizontalLayout;
            testCase.stateLayout = testCase.problem.stateLayout;
            testCase.audit = testCase.problem. ...
                auditSlopeCompatibleWaveModeCompression( ...
                trustedModeBounds=[1 0], ...
                supportModeBounds=[1 1;1 2;1 3], ...
                stationaryPolynomialDegree=2, ...
                primitivePolynomialDegrees=[2;3;4], ...
                comparisonPolynomialDegree=6, ...
                modalCounts=[1;2], ...
                robinLengthRatios=[-1/4;Inf], ...
                referenceSlopeFactors=[0;0.5], ...
                dynamics=["hydrostatic";"nonhydrostatic"], ...
                paddingFactors=[2;3], ...
                terrainScales=[0.125;0.25;0.5;1], ...
                internalModesEVPOrders=[64;128]);
        end
    end

    methods (Test)
        function outcomeUsesDeclaredClassification(testCase)
            audit = testCase.audit;
            testCase.verifyTrue(ismember(audit.classification, ...
                ["hydrostatic-slope-acceleration", ...
                "nonhydrostatic-slope-acceleration", ...
                "slope-modal-equivalent", ...
                "per-wavenumber-slope-incompatible"]))
            testCase.verifyEqual(audit.status,audit.classification)
            testCase.verifyEqual(audit.nextScope, ...
                "milestone-10-only-if-separately-authorized")
            testCase.verifyEqual(audit.robinInterpretation.validation, ...
                "selected-values-frozen")
        end

        function bothDynamicsAndDirichletControlsArePresent(testCase)
            specifications = [testCase.audit.candidates.specification];
            testCase.verifyTrue(all(ismember( ...
                ["hydrostatic","nonhydrostatic"], ...
                [specifications.dynamics])))
            testCase.verifyTrue(any([specifications.controlName] ...
                == "hydrostatic-dirichlet"))
            testCase.verifyTrue(any([specifications.controlName] ...
                == "nonhydrostatic-dirichlet"))
            testCase.verifyTrue(any([specifications.controlName] ...
                == "hydrostatic-slope-compatible"))
            testCase.verifyTrue(any([specifications.controlName] ...
                == "nonhydrostatic-slope-compatible"))
        end

        function localDescriptorsUseHomogeneousClassification(testCase)
            results = arrayfun(@(candidate) ...
                [candidate.audit.details{:}],testCase.audit.candidates, ...
                "UniformOutput",false);
            results = [results{:}];
            testCase.verifyTrue(all(isfinite( ...
                [results.maximumWaveDescriptorResidual])))
            testCase.verifyTrue(all(isfinite( ...
                [results.maximumWaveBackwardError])))
            testCase.verifyTrue(all(isfinite( ...
                [results.maximumWaveBottomResidual])))
        end

        function trainingParametersAreFrozenByDynamics(testCase)
            selected = testCase.audit.selectedByDynamics;
            testCase.verifyEqual(numel(selected),2)
            testCase.verifyTrue(all(isfinite([selected.trainingScore]) ...
                |isinf([selected.trainingScore])))
            testCase.verifyTrue(all(ismember( ...
                [selected.robinLengthRatio], ...
                testCase.audit.robinLengthRatios)))
        end

        function publicLayoutsRemainUnchanged(testCase)
            testCase.verifyEqual(testCase.problem.horizontalLayout, ...
                testCase.horizontalLayout)
            testCase.verifyEqual(testCase.problem.stateLayout, ...
                testCase.stateLayout)
        end
    end
end
