classdef TestWVTerrainEnergyProductionPhysicalStateContract < matlab.unittest.TestCase
    % Verify the Milestone-10.1 production physical-state contract.

    properties
        problems
        audits
        horizontalLayouts
        stateLayouts
    end

    methods (TestClassSetup)
        function createProductionContractAudits(testCase)
            addpath(fileparts(fileparts(mfilename("fullpath"))));
            antialiasSettings = [false true];
            nConfigurations = numel(antialiasSettings)+1;
            testCase.problems = cell(nConfigurations,1);
            testCase.audits = cell(nConfigurations,1);
            testCase.horizontalLayouts = cell(nConfigurations,1);
            testCase.stateLayouts = cell(nConfigurations,1);
            for iSetting = 1:numel(antialiasSettings)
                problem = TestWVTerrainEnergyProductionPhysicalStateContract. ...
                    createProblem(antialiasSettings(iSetting));
                testCase.problems{iSetting} = problem;
                testCase.horizontalLayouts{iSetting} = problem.horizontalLayout;
                testCase.stateLayouts{iSetting} = problem.stateLayout;
                testCase.audits{iSetting} = ...
                    problem.auditProductionPhysicalStateContract( ...
                    trustedModeBounds=[1 0], ...
                    supportModeBounds=[1 0;1 1;1 2], ...
                    waveModeIndices=1, ...
                    apvModeIndices=[0;1], ...
                    primitivePolynomialDegrees=[8;16;24], ...
                    paddingFactors=[2;3]);
            end
            iVariable = nConfigurations;
            problem = TestWVTerrainEnergyProductionPhysicalStateContract. ...
                createProblem(false,true);
            testCase.problems{iVariable} = problem;
            testCase.horizontalLayouts{iVariable} = problem.horizontalLayout;
            testCase.stateLayouts{iVariable} = problem.stateLayout;
            testCase.audits{iVariable} = ...
                problem.auditProductionPhysicalStateContract( ...
                trustedModeBounds=[1 0], ...
                supportModeBounds=[1 0;1 1;1 2], ...
                waveModeIndices=1, ...
                apvModeIndices=[0;1], ...
                primitivePolynomialDegrees=[8;16;24], ...
                paddingFactors=[2;3]);
        end
    end

    methods (Test)
        function contractPassesForEveryControlConfiguration(testCase)
            for iAudit = 1:numel(testCase.audits)
                audit = testCase.audits{iAudit};
                testCase.verifyEqual(audit.status, ...
                    "complete-production-state-contract")
                testCase.verifyTrue(audit.isCompatible)
                testCase.verifyEqual(audit.nextScope, ...
                    "milestone-10.2-complete-internal-wave-coverage")
            end
        end

        function degreeOfFreedomBudgetClosesExactly(testCase)
            audit = testCase.audits{1};
            testCase.verifyEqual(audit.numberOfProductionCoordinates,16)
            testCase.verifyEqual( ...
                audit.numberOfIndependentRealDegreesOfFreedom,16)
            counts = audit.degreeOfFreedomBudget;
            expected = table( ...
                ["apv-balanced";"bottom-inversion";"inertial"; ...
                "internal-wave";"mda";"mean-bottom-compatible"], ...
                [4;2;4;4;1;1], ...
                VariableNames=["family","numberOfComplexCoordinates"]);
            testCase.verifyEqual(counts.family,expected.family)
            testCase.verifyEqual(counts.numberOfComplexCoordinates, ...
                expected.numberOfComplexCoordinates)
            testCase.verifyEqual(sum(counts.numberOfComplexCoordinates), ...
                audit.numberOfProductionCoordinates)
        end

        function layoutCarriesTheCompletePhysicalContract(testCase)
            audit = testCase.audits{1};
            layout = audit.productionLayout;
            testCase.verifyEqual(layout.index,(1:height(layout)).')
            testCase.verifyFalse(any(layout.family == "unresolved"))
            testCase.verifyTrue(all(strlength(layout.units) > 0))
            testCase.verifyTrue(all(isfinite(layout.nativeHorizontalIndex)))
            testCase.verifyTrue(all(isnan(layout.nativeCoefficientIndex) ...
                ==(layout.component == "etaB")))
            testCase.verifyEqual(audit.conjugateCoordinateIndex( ...
                audit.conjugateCoordinateIndex),(1:height(layout)).')
            for iCoordinate = 1:height(layout)
                partner = audit.conjugateCoordinateIndex(iCoordinate);
                if layout.component(iCoordinate) == "Ap"
                    testCase.verifyEqual(layout.component(partner),"Am")
                elseif layout.component(iCoordinate) == "Am"
                    testCase.verifyEqual(layout.component(partner),"Ap")
                end
                testCase.verifyEqual(layout.family(partner), ...
                    layout.family(iCoordinate))
                testCase.verifyEqual(layout.j(partner),layout.j(iCoordinate))
            end
        end

        function nativeStatesCloseInThePrimitiveOracle(testCase)
            for iAudit = 1:numel(testCase.audits)
                audit = testCase.audits{iAudit};
                primary = audit.primary;
                tolerance = audit.requiredTolerance;
                testCase.verifyLessThan(primary.roundTripDefect, ...
                    tolerance.roundTrip)
                testCase.verifyLessThan(primary.energyNormalizationDefect, ...
                    tolerance.energy)
                testCase.verifyLessThan(primary.maximumEndpointDefect, ...
                    tolerance.endpoint)
                testCase.verifyLessThan(primary.maximumZeroAPVDefect, ...
                    tolerance.zeroAPV)
                testCase.verifyLessThan(primary.conjugacyDefect, ...
                    tolerance.conjugacy)
                testCase.verifyLessThan(primary.maximumNativeMatchDefect, ...
                    tolerance.nativeMatch)
                testCase.verifyLessThan( ...
                    primary.maximumPhysicalEmbeddingDefect, ...
                    tolerance.embedding)
                testCase.verifyGreaterThan( ...
                    primary.scaledEnergyReciprocalConditionNumber,1e-3)
            end
        end

        function independentRefinementsConverge(testCase)
            for iAudit = 1:numel(testCase.audits)
                audit = testCase.audits{iAudit};
                embedding = audit.verticalConvergence. ...
                    maximumPhysicalEmbeddingDefect;
                testCase.verifyTrue(audit.verticalConvergence.converges)
                testCase.verifyLessThan(embedding(end),embedding(1)/4)
                testCase.verifyLessThan( ...
                    audit.supportConvergence.maximumReferenceGramDefect, ...
                    audit.requiredTolerance.support)
                testCase.verifyLessThan( ...
                    audit.paddingConvergence.maximumReferenceGramDefect, ...
                    audit.requiredTolerance.padding)
            end
        end

        function guardsNeverEnterTheProductionLayout(testCase)
            audit = testCase.audits{1};
            testCase.verifyEqual( ...
                sort(audit.productionHorizontalLayout.kMode),[-1;0;1])
            testCase.verifyEqual( ...
                audit.productionHorizontalLayout.lMode,[0;0;0])
            for iGuard = 1:numel(audit.guardLayouts)
                guard = audit.guardLayouts{iGuard};
                testCase.verifyFalse(any(abs(guard.kMode) <= 1 ...
                    & abs(guard.lMode) <= 0))
            end
            testCase.verifyGreaterThan( ...
                audit.primary.numberOfDiscardedPrimitiveCoordinates,0)
        end

        function publicLayoutsRemainUnchanged(testCase)
            for iProblem = 1:numel(testCase.problems)
                testCase.verifyEqual( ...
                    testCase.problems{iProblem}.horizontalLayout, ...
                    testCase.horizontalLayouts{iProblem})
                testCase.verifyEqual(testCase.problems{iProblem}.stateLayout, ...
                    testCase.stateLayouts{iProblem})
            end
        end

        function validationRejectsIncompleteInputs(testCase)
            problem = testCase.problems{1};
            testCase.verifyError(@() ...
                problem.auditProductionPhysicalStateContract( ...
                trustedModeBounds=[1 0], ...
                supportModeBounds=[1 0;1 1], ...
                primitivePolynomialDegrees=[8;16;24]), ...
                "WVTerrainEnergyGalerkin:InvalidProductionSupportBounds")
            testCase.verifyError(@() ...
                problem.auditProductionPhysicalStateContract( ...
                trustedModeBounds=[1 0], ...
                supportModeBounds=[1 0;1 1;1 2], ...
                primitivePolynomialDegrees=[8;16]), ...
                "WVTerrainEnergyGalerkin:InvalidProductionPrimitiveDegrees")
            testCase.verifyError(@() ...
                problem.auditProductionPhysicalStateContract( ...
                trustedModeBounds=[1 0], ...
                supportModeBounds=[1 0;1 1;1 2], ...
                primitivePolynomialDegrees=[8;16;24], ...
                paddingFactors=2), ...
                "WVTerrainEnergyGalerkin:InvalidProductionPaddingFactors")
            testCase.verifyError(@() ...
                problem.auditProductionPhysicalStateContract( ...
                trustedModeBounds=[1 0], ...
                supportModeBounds=[1 0;1 1;1 2], ...
                waveModeIndices=0, ...
                primitivePolynomialDegrees=[8;16;24]), ...
                "WVTerrainEnergyGalerkin:InvalidProductionWaveModeIndices")
        end
    end

    methods (Static)
        function problem = createProblem(shouldAntialias,hasVariableStratification)
            arguments
                shouldAntialias (1,1) logical
                hasVariableStratification (1,1) logical = false
            end
            N0 = sqrt(2e-5);
            z = linspace(-1200,0,5)';
            Nx = 6+6*double(shouldAntialias);
            Ny = 10+6*double(shouldAntialias);
            if hasVariableStratification
                N2Function = @(z) 1e-5+1.5e-5*exp(z/600);
            else
                N2Function = @(z) N0^2+0*z;
            end
            wvt = WVTransformBoussinesq( ...
                [24e3 20e3 1200],[Nx Ny 5], ...
                N2Function=N2Function,latitude=45, ...
                shouldAntialias=shouldAntialias,z=z);
            [~,y] = ndgrid((0:wvt.Nx-1)'*wvt.Lx/wvt.Nx, ...
                (0:wvt.Ny-1)'*wvt.Ly/wvt.Ny);
            terrain = 2.5*cos(2*pi*y/wvt.Ly);
            problem = WVTerrainEnergyGalerkin.fromTopography( ...
                wvt,topographicHeight=terrain);
        end
    end
end
