classdef TestWVTerrainEnergyGlobalTangentStationaryCompression < matlab.unittest.TestCase
    % Verify the Milestone-10.2.5 tangent-scalar compression oracle.

    properties
        problem
        firstAudit
        cachedAudit
        uncachedAudit
        cacheDirectory
        providerPath
        horizontalLayout
        stateLayout
    end

    methods (TestClassSetup)
        function createGlobalTangentAudit(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            addpath(repositoryRoot);
            if ~isfolder(fullfile(repositoryRoot,"output"))
                mkdir(fullfile(repositoryRoot,"output"));
            end
            testCase.cacheDirectory = string(tempname( ...
                fullfile(repositoryRoot,"output")));
            testCase.providerPath = string(fullfile( ...
                repositoryRoot,"..","internal-modes-evp"));
            testCase.problem = ...
                TestWVTerrainEnergyGlobalTangentStationaryCompression. ...
                createProblem(testCase.providerPath);
            testCase.horizontalLayout = testCase.problem.horizontalLayout;
            testCase.stateLayout = testCase.problem.stateLayout;
            argumentsWithCache = ...
                TestWVTerrainEnergyGlobalTangentStationaryCompression. ...
                reducedArguments(testCase.cacheDirectory);
            testCase.firstAudit = testCase.problem. ...
                auditGlobalTangentStationaryCompression( ...
                argumentsWithCache{:});
            testCase.cachedAudit = testCase.problem. ...
                auditGlobalTangentStationaryCompression( ...
                argumentsWithCache{:});
            argumentsWithoutCache = ...
                TestWVTerrainEnergyGlobalTangentStationaryCompression. ...
                reducedArguments("");
            testCase.uncachedAudit = testCase.problem. ...
                auditGlobalTangentStationaryCompression( ...
                argumentsWithoutCache{:});
        end
    end

    methods (TestClassTeardown)
        function removeCache(testCase)
            if isfolder(testCase.cacheDirectory)
                rmdir(testCase.cacheDirectory,"s");
            end
            if contains(path,testCase.providerPath)
                rmpath(testCase.providerPath)
            end
        end
    end

    methods (Test)
        function exactPolynomialFactorizationPasses(testCase)
            factorization = testCase.firstAudit.factorization;
            testCase.verifyEqual(factorization.maximumDimensionDefect,0)
            testCase.verifyLessThan( ...
                factorization.maximumProjectorDefect,1e-12)
            testCase.verifyLessThan(max( ...
                [factorization.results.tangentLiftAPVDefect]),1e-10)
            testCase.verifyTrue(factorization.allRanksStable)
            testCase.verifyTrue(testCase.firstAudit.gates.factorization)
        end

        function rankRevealingLiftSolvePasses(testCase)
            selected = testCase.firstAudit.training.results( ...
                testCase.firstAudit.training.selectedIndex);
            testCase.verifyEqual(selected.liftRankDefect,0)
            testCase.verifyLessThan( ...
                selected.maximumLiftTraceDefect,1e-10)
            testCase.verifyLessThan( ...
                selected.maximumLiftEnergyDefect,1e-10)
            testCase.verifyLessThan( ...
                selected.maximumLiftAPVDefect,1e-10)
            testCase.verifyGreaterThan( ...
                selected.numberOfTangentTraceCoordinates,0)
            testCase.verifyGreaterThan( ...
                selected.numberOfNonTangentTraceCoordinates,0)
        end

        function pinnedProviderIsTheClassifiedBlocker(testCase)
            audit = testCase.firstAudit;
            testCase.verifyEqual(audit.classification, ...
                "global-tangent-provider-blocker")
            testCase.verifyEqual(audit.status,audit.classification)
            testCase.verifyGreaterThan( ...
                audit.training.provider.providerDifference,1e-11)
            testCase.verifyFalse(audit.training.results( ...
                audit.training.selectedIndex).providerPasses)
        end

        function cacheIsOptInAndContentAddressed(testCase)
            first = testCase.firstAudit.cache;
            second = testCase.cachedAudit.cache;
            disabled = testCase.uncachedAudit.cache;
            testCase.verifyTrue(first.enabled)
            testCase.verifyGreaterThan(first.numberOfMisses,0)
            testCase.verifyEqual(second.numberOfMisses,0)
            testCase.verifyEqual(second.numberOfHits,1)
            testCase.verifyGreaterThan(second.secondsSaved,0)
            testCase.verifyTrue(isfile(second.path))
            testCase.verifyFalse(disabled.enabled)
            testCase.verifyEqual(disabled.path,"")
        end

        function publicLayoutsRemainUnchanged(testCase)
            testCase.verifyEqual(testCase.problem.horizontalLayout, ...
                testCase.horizontalLayout)
            testCase.verifyEqual(testCase.problem.stateLayout, ...
                testCase.stateLayout)
        end

        function validationRejectsForbiddenInputs(testCase)
            testCase.verifyError(@() testCase.problem. ...
                auditGlobalTangentStationaryCompression( ...
                cacheDirectory=tempdir), ...
                "WVTerrainEnergyGalerkin:InvalidGlobalTangentCacheLocation")
            testCase.verifyError(@() testCase.problem. ...
                auditGlobalTangentStationaryCompression( ...
                internalModesEVPOrders=[96;128]), ...
                "WVTerrainEnergyGalerkin:InvalidGlobalTangentEVPOrders")
            testCase.verifyError(@() testCase.problem. ...
                auditGlobalTangentStationaryCompression( ...
                supportModeBounds=[1 1;1 2]), ...
                "WVTerrainEnergyGalerkin:InvalidGlobalTangentSupport")
        end
    end

    methods (Static)
        function args = reducedArguments(cacheDirectory)
            args = { ...
                "trustedModeBounds",[1 0], ...
                "supportModeBounds",[1 1;1 2;1 3], ...
                "targetWaveModeIndices",1, ...
                "interiorGeostrophicModeCounts",[1;2;3], ...
                "stationaryReferenceDegree",2, ...
                "primitiveReferenceDegrees",[2;3;4], ...
                "paddingFactors",[2;3], ...
                "terrainScales",[0;1/8;1/4;1/2;1], ...
                "internalModesEVPOrders",[64;128], ...
                "shouldRunTwoDimensionalControl",false, ...
                "cacheDirectory",cacheDirectory};
        end

        function problem = createProblem(providerPath)
            N0 = sqrt(2e-5);
            z = linspace(-1200,0,5)';
            wvt = WVTransformBoussinesq( ...
                [24e3 20e3 1200],[4 8 5], ...
                N2Function=@(z)N0^2+0*z,latitude=45, ...
                shouldAntialias=false,z=z);
            addpath(providerPath,"-end")
            [~,y] = ndgrid((0:wvt.Nx-1)'*wvt.Lx/wvt.Nx, ...
                (0:wvt.Ny-1)'*wvt.Ly/wvt.Ny);
            problem = WVTerrainEnergyGalerkin.fromTopography( ...
                wvt,topographicHeight=2.5*cos(2*pi*y/wvt.Ly));
        end
    end
end
