classdef TestWVTerrainEnergyBoundaryCompleteVerticalModeCompression < matlab.unittest.TestCase
    % Verify the Milestone-9.2 boundary-complete modal-compression oracle.

    properties
        problem
        audit
        horizontalLayout
        stateLayout
    end

    methods (TestClassSetup)
        function createCompressionAudit(testCase)
            addpath(fileparts(fileparts(mfilename("fullpath"))));
            N0 = sqrt(2e-5);
            z = linspace(-1200,0,5)';
            wvt = WVTransformBoussinesq( ...
                [24e3 20e3 1200],[6 10 5], ...
                N2Function=@(z)N0^2+0*z,latitude=45, ...
                shouldAntialias=false,z=z);
            [~,y] = ndgrid((0:wvt.Nx-1)'*wvt.Lx/wvt.Nx, ...
                (0:wvt.Ny-1)'*wvt.Ly/wvt.Ny);
            terrain = 2.5*cos(2*pi*y/wvt.Ly);
            testCase.problem = WVTerrainEnergyGalerkin.fromTopography( ...
                wvt,topographicHeight=terrain);
            testCase.horizontalLayout = testCase.problem.horizontalLayout;
            testCase.stateLayout = testCase.problem.stateLayout;
            testCase.audit = testCase.problem. ...
                auditBoundaryCompleteVerticalModeCompression( ...
                trustedModeBounds=[1 0], ...
                supportModeBounds=[1 1;1 2;1 3], ...
                stationaryPolynomialDegree=2, ...
                primitivePolynomialDegrees=[2;3;4], ...
                comparisonPolynomialDegree=6, ...
                modalCounts=[1;2], ...
                robinLengthRatios=[-1/4;Inf], ...
                paddingFactors=[2;3], ...
                terrainScales=[0.125;0.25;0.5;1], ...
                internalModesEVPOrders=[64;128]);
        end
    end

    methods (Test)
        function outcomeUsesDeclaredClassification(testCase)
            audit = testCase.audit;
            testCase.verifyTrue(ismember(audit.classification, ...
                ["modal-acceleration","modal-equivalent", ...
                "modal-incompatible"]))
            testCase.verifyEqual(audit.status,audit.classification)
            testCase.verifyEqual(audit.nextScope, ...
                "milestone-9.3-slope-compatible-wave-coordinates")
            testCase.verifyFalse(audit.robinInterpretation.isHardPhysicalGate)
            testCase.verifyEqual(audit.robinInterpretation.role, ...
                "finite-order-convergence-parameter")
            testCase.verifyEqual( ...
                audit.robinInterpretation.selectionRule, ...
                "train-then-freeze-for-independent-validation")
            testCase.verifyEqual(audit.internalModesEVPCommit, ...
                "df86687e91faa31bf65941299062d125a96904b1")
            testCase.verifyTrue( ...
                audit.providerQualification.isolatedCheckoutRequired)
            testCase.verifyEqual( ...
                audit.providerQualification.qualifiedOrders,[64;128])
            testCase.verifyEqual( ...
                audit.providerQualification.rejectedOrders,[96;192])
        end

        function verticalProblemsHaveTheRequiredEndpointStructure(testCase)
            results = [testCase.audit.details{:}];
            testCase.verifyLessThan( ...
                max([results.maximumEndpointDefect]),1e-10)
            testCase.verifyEqual( ...
                max([results.negativeRobinModeCountDefect]),0)
            testCase.verifyLessThan( ...
                max([results.maximumProviderDefect]),1e-8)
        end

        function reducedFormsRetainPhysicalStructure(testCase)
            results = [testCase.audit.details{:}];
            testCase.verifyLessThan( ...
                max([results.energyHermitianDefect]),1e-12)
            testCase.verifyLessThan( ...
                max([results.exchangeSkewHermitianDefect]),1e-12)
            testCase.verifyLessThan( ...
                max([results.modalEnergyOrthogonalityDefect]),1e-10)
        end

        function stationaryCompletionIsExplicitlyAccountedFor(testCase)
            results = [testCase.audit.details{:}];
            for iResult = 1:numel(results)
                testCase.verifyEqual(results(iResult).actualModalDimension, ...
                    results(iResult).nominalModalDimension ...
                    +results(iResult).stationaryCompletionDimension)
                testCase.verifyLessThanOrEqual( ...
                    results(iResult).actualModalDimension, ...
                    results(iResult).primitiveDimension)
            end
        end

        function everyRequestedControlIsPresent(testCase)
            audit = testCase.audit;
            testCase.verifySize(audit.details, ...
                [numel(audit.modalCounts) ...
                numel(audit.robinLengthRatios) ...
                numel(audit.paddingFactors)])
            testCase.verifyEqual(audit.terrainScales(end),1)
            testCase.verifyEqual(audit.internalModesEVPOrders,[64;128])
        end

        function publicLayoutsRemainUnchanged(testCase)
            testCase.verifyEqual(testCase.problem.horizontalLayout, ...
                testCase.horizontalLayout)
            testCase.verifyEqual(testCase.problem.stateLayout, ...
                testCase.stateLayout)
        end
    end
end
