classdef TestWVTerrainEnergyDensePhysicalEnergyTerrainModes < matlab.unittest.TestCase
    % Verify the Milestone-9 dense mode gate and its scientific blocker.

    properties
        problem
        audit
        flatAudit
        uniformAudit
        variableStratificationAudit
        N0
    end

    methods (TestClassSetup)
        function createReferenceAudits(testCase)
            addpath(fileparts(fileparts(mfilename("fullpath"))));
            testCase.N0 = sqrt(2e-5);
            z = linspace(-1200,0,5)';
            wvt = WVTransformBoussinesq([24e3 20e3 1200],[6 10 5], ...
                N2Function=@(z)testCase.N0^2+0*z,latitude=45, ...
                shouldAntialias=false,z=z);
            [~,y] = ndgrid((0:wvt.Nx-1)'*wvt.Lx/wvt.Nx, ...
                (0:wvt.Ny-1)'*wvt.Ly/wvt.Ny);
            terrain = 20*cos(2*pi*y/wvt.Ly);
            testCase.problem = WVTerrainEnergyGalerkin.fromTopography( ...
                wvt,topographicHeight=terrain);
            testCase.audit = ...
                testCase.problem.auditDensePhysicalEnergyTerrainModes( ...
                trustedModeBounds=[1 0], ...
                supportModeBounds=[1 2;1 3;1 4], ...
                stationaryPolynomialDegree=2, ...
                primitivePolynomialDegrees=[2;3;4], ...
                paddingFactors=[2;3],terrainScales=1);

            flatProblem = WVTerrainEnergyGalerkin.fromTopography( ...
                wvt,topographicHeight=zeros(wvt.Nx,wvt.Ny));
            testCase.flatAudit = ...
                flatProblem.auditDensePhysicalEnergyTerrainModes( ...
                trustedModeBounds=[1 0], ...
                supportModeBounds=[1 0;1 0;1 0], ...
                stationaryPolynomialDegree=4, ...
                primitivePolynomialDegrees=[4;6;8], ...
                paddingFactors=[2;3],terrainScales=1);

            uniformProblem = WVTerrainEnergyGalerkin.fromTopography( ...
                wvt,topographicHeight=20*ones(wvt.Nx,wvt.Ny));
            testCase.uniformAudit = ...
                uniformProblem.auditDensePhysicalEnergyTerrainModes( ...
                trustedModeBounds=[1 0], ...
                supportModeBounds=[1 0;1 0;1 0], ...
                stationaryPolynomialDegree=4, ...
                primitivePolynomialDegrees=[4;6;8], ...
                paddingFactors=[2;3],terrainScales=1);

            variableN2 = @(z) 1e-5+1e-5*exp(z/1000);
            variableTransform = WVTransformBoussinesq( ...
                [24e3 20e3 1200],[6 10 5],N2Function=variableN2, ...
                latitude=45,shouldAntialias=false,z=z);
            variableProblem = WVTerrainEnergyGalerkin.fromTopography( ...
                variableTransform,topographicHeight=terrain);
            testCase.variableStratificationAudit = ...
                variableProblem.auditDensePhysicalEnergyTerrainModes( ...
                trustedModeBounds=[1 0], ...
                supportModeBounds=[1 1;1 2;1 3], ...
                stationaryPolynomialDegree=2, ...
                primitivePolynomialDegrees=[2;3;4], ...
                paddingFactors=[2;3],terrainScales=1);
        end
    end

    methods (Test)
        function physicalEnergyEigensystemIsNumericallyValid(testCase)
            audit = testCase.audit;
            finest = audit.finest;
            testCase.verifyLessThan(finest.energyHermitianDefect,1e-12)
            testCase.verifyLessThan( ...
                finest.exchangeSkewHermitianDefect,1e-12)
            testCase.verifyLessThan(finest.energyAssemblyDefect,1e-12)
            testCase.verifyLessThan(finest.exchangeAssemblyDefect,1e-12)
            testCase.verifyGreaterThan(finest.energyRcond,1e-12)
            testCase.verifyLessThan(finest.maximumEigenResidual,1e-10)
            testCase.verifyLessThan( ...
                finest.dynamicEnergyOrthogonalityDefect,1e-10)
            testCase.verifyLessThan( ...
                finest.stationaryDynamicOrthogonalityDefect,1e-10)
            testCase.verifyLessThan(finest.completenessDefect,1e-10)
            testCase.verifyLessThan(finest.maximumConjugacyDefect,1e-10)
            testCase.verifyLessThan(audit.padding.maximumFrequencyDefect,1e-10)
        end

        function stationarySectorIsOnlyMilestoneEightTangencySpace(testCase)
            finest = testCase.audit.finest;
            testCase.verifyEqual(finest.stationaryBasis, ...
                finest.stationary.trustedBasis)
            testCase.verifyLessThan(finest.stationaryRowDefect,1e-10)
            testCase.verifyGreaterThan( ...
                finest.numberOfUnclassifiedWeakNullDirections,0)
            testCase.verifyGreaterThan( ...
                finest.zeroFrequencyStationaryProjectorDefect,1e-9)
            testCase.verifyGreaterThan( ...
                finest.maximumUnresolvedZeroTrustedParticipation,0)
        end

        function everyNonTangentBottomDirectionIsRetained(testCase)
            finest = testCase.audit.finest;
            testCase.verifyGreaterThan( ...
                finest.numberOfRetainedNonTangentBottomDirections,0)
            testCase.verifyLessThan( ...
                finest.nonTangentBottomRetentionDefect,1e-10)
            testCase.verifyEqual( ...
                finest.numberOfStationaryModes+finest.numberOfDynamicModes, ...
                size(finest.energyMatrix,1))
        end

        function bottomModeClaimIsBlockedByPhysicalResiduals(testCase)
            audit = testCase.audit;
            finest = audit.finest;
            testCase.verifyEqual(audit.status, ...
                "dense-modal-classification-blocker")
            testCase.verifyFalse(audit.isCompatible)
            testCase.verifyGreaterThan(finest.numberOfBoundaryCandidates,0)
            testCase.verifyEqual(finest.numberOfClaimedBoundaryModes,0)
            testCase.verifyGreaterThanOrEqual( ...
                finest.minimumBoundaryFrequencyResolutionRatio,1e3)
            testCase.verifyGreaterThan( ...
                finest.maximumBoundaryCandidateAPVDefect, ...
                audit.requiredTolerance.apv)
            testCase.verifyGreaterThan( ...
                finest.maximumBoundaryCandidateStrongResidual, ...
                audit.requiredTolerance.strong)
            claimed = finest.boundaryModeIndices;
            testCase.verifyTrue(all( ...
                finest.frequencyResolutionRatio(claimed) >= 1e3))
        end

        function flatAndUniformDepthWaveFrequenciesConverge(testCase)
            flatError = TestWVTerrainEnergyDensePhysicalEnergyTerrainModes ...
                .firstModeFrequencyError(testCase.flatAudit,testCase.N0, ...
                1200,24e3,testCase.problem.originatingTransform.f);
            uniformError = TestWVTerrainEnergyDensePhysicalEnergyTerrainModes ...
                .firstModeFrequencyError(testCase.uniformAudit, ...
                testCase.N0,1180,24e3, ...
                testCase.problem.originatingTransform.f);
            testCase.verifyTrue(all(diff(flatError) < 0))
            testCase.verifyTrue(all(diff(uniformError) < 0))
            testCase.verifyLessThan(flatError(end),1e-10)
            testCase.verifyLessThan(uniformError(end),1e-10)
        end

        function variableStratificationHasSameBlocker(testCase)
            variableAudit = testCase.variableStratificationAudit;
            finest = variableAudit.finest;
            testCase.verifyEqual( ...
                variableAudit.status,"dense-terrain-mode-blocker")
            testCase.verifyGreaterThan(finest.maximumEigenResidual,1e-10)
            testCase.verifyLessThan( ...
                finest.dynamicEnergyOrthogonalityDefect,1e-10)
            testCase.verifyLessThan(finest.maximumConjugacyDefect,1e-10)
            testCase.verifyLessThan( ...
                finest.nonTangentBottomRetentionDefect,1e-10)
            testCase.verifyFalse(variableAudit.isCompatible)
            testCase.verifyEqual(finest.numberOfClaimedBoundaryModes,0)
        end

        function validationPreservesPublicLayouts(testCase)
            horizontalBefore = testCase.problem.horizontalLayout;
            stateBefore = testCase.problem.stateLayout;
            testCase.verifyError(@() ...
                testCase.problem.auditDensePhysicalEnergyTerrainModes( ...
                trustedModeBounds=[1 0], ...
                supportModeBounds=[1 2;1 3], ...
                stationaryPolynomialDegree=2, ...
                primitivePolynomialDegrees=[2;3], ...
                paddingFactors=[2;3],terrainScales=1), ...
                "WVTerrainEnergyGalerkin:InvalidDenseModeDegrees")
            testCase.verifyError(@() ...
                testCase.problem.auditDensePhysicalEnergyTerrainModes( ...
                trustedModeBounds=[1 1], ...
                supportModeBounds=[1 1;1 2;1 3], ...
                stationaryPolynomialDegree=2, ...
                primitivePolynomialDegrees=[2;3;4], ...
                paddingFactors=[2;3],terrainScales=1), ...
                "WVTerrainEnergyGalerkin:InsufficientDenseModeGuard")
            testCase.verifyEqual(testCase.problem.horizontalLayout, ...
                horizontalBefore)
            testCase.verifyEqual(testCase.problem.stateLayout,stateBefore)
        end
    end

    methods (Static)
        function relativeError = firstModeFrequencyError( ...
                audit,N0,depth,Lx,f)
            kappa = 2*pi/Lx;
            expected = sqrt((N0^2*kappa^2 ...
                +f^2*(pi/depth)^2)/(kappa^2+(pi/depth)^2));
            relativeError = zeros(size(audit.details,1),1);
            for iRefinement = 1:size(audit.details,1)
                result = audit.details{iRefinement,1,1};
                horizontal = abs(result.horizontalLayout.kMode) == 1 ...
                    & result.horizontalLayout.lMode == 0;
                participation = sum( ...
                    result.horizontalEnergyParticipation(horizontal,:),1).';
                resolved = result.frequency ...
                    >result.absoluteFrequencyUncertainty ...
                    & participation > 0.9;
                computed = max(result.frequency(resolved));
                relativeError(iRefinement) = ...
                    abs(computed-expected)/expected;
            end
        end
    end
end
