classdef TestWVTerrainEnergyCoupledBlockInternalWaveCorrection < matlab.unittest.TestCase
    % Verify the Milestone-10.2.1 exact coupled correction and stop gate.

    properties
        problem
        audit
        horizontalLayout
        stateLayout
    end

    methods (TestClassSetup)
        function createExactCoupledAudit(testCase)
            addpath(fileparts(fileparts(mfilename("fullpath"))));
            testCase.problem = ...
                TestWVTerrainEnergyCoupledBlockInternalWaveCorrection. ...
                createProblem;
            testCase.horizontalLayout = testCase.problem.horizontalLayout;
            testCase.stateLayout = testCase.problem.stateLayout;
            testCase.audit = testCase.problem. ...
                auditCoupledBlockInternalWaveCorrection( ...
                trustedModeBounds=[1 0], ...
                supportModeBounds=[1 1;1 2;1 3], ...
                waveModeIndices=1,apvModeIndices=[0;1], ...
                stationaryPolynomialDegree=3, ...
                primitivePolynomialDegrees=[3;4;5], ...
                paddingFactors=[2;3],maximumOuterIterations=3, ...
                maximumKrylovRestarts=2, ...
                shouldCompareSlopeSeed=false);
        end
    end

    methods (Test)
        function exactCorrectionReachesMachineResidual(testCase)
            primary = testCase.audit.exact.primary;
            testCase.verifyLessThan(primary.maximumCorrectionResidual,1e-10)
            testCase.verifyLessThan( ...
                primary.maximumCorrectionOrthogonalityDefect,1e-10)
            testCase.verifyLessThan(primary.maximumInternalResidual,1e-10)
            testCase.verifyEqual(primary.numberOfIterations,1)
            testCase.verifyEqual( ...
                [primary.history.trialDimension], ...
                repmat(primary.dimension.validatedInternal, ...
                1,numel(primary.history)))
        end

        function refinementEstablishesIsolationStop(testCase)
            testCase.verifyEqual(testCase.audit.classification, ...
                "coupled-block-isolation-blocker")
            testCase.verifyFalse(testCase.audit.exact.isolationPasses)
            testCase.verifyGreaterThan( ...
                max(testCase.audit.exact.nestedProjectorDefect), ...
                testCase.audit.requiredTolerance.nested)
            testCase.verifyFalse(testCase.audit.iterative.wasAttempted)
            testCase.verifyEqual(testCase.audit.nextScope, ...
                "milestone-10.2.1-stop-for-analysis")
        end

        function exactFormsAndBottomPhysicsRemainValid(testCase)
            primary = testCase.audit.exact.primary;
            testCase.verifyLessThan(primary.energyHermitianDefect,1e-12)
            testCase.verifyLessThan( ...
                primary.exchangeSkewHermitianDefect,1e-12)
            testCase.verifyLessThan(primary.maximumInternalBottomDefect,1e-10)
            testCase.verifyLessThan(primary.maximumInternalStrongResidual,1e-3)
            testCase.verifyLessThan(primary.stationaryOrthogonalityDefect,1e-10)
        end

        function dimensionsAndPublicLayoutsArePreserved(testCase)
            economy = testCase.audit.economy;
            testCase.verifyEqual(economy.NJoint, ...
                testCase.audit.exact.primary.dimension.validatedInternal)
            testCase.verifyGreaterThan(economy.NAmbient,economy.NJoint)
            testCase.verifyEqual(testCase.problem.horizontalLayout, ...
                testCase.horizontalLayout)
            testCase.verifyEqual(testCase.problem.stateLayout, ...
                testCase.stateLayout)
        end

        function validationRejectsIncompleteControls(testCase)
            testCase.verifyError(@() testCase.problem. ...
                auditCoupledBlockInternalWaveCorrection( ...
                primitivePolynomialDegrees=[4;6]), ...
                "WVTerrainEnergyGalerkin:InvalidCoupledBlockDegrees")
            testCase.verifyError(@() testCase.problem. ...
                auditCoupledBlockInternalWaveCorrection( ...
                paddingFactors=2), ...
                "WVTerrainEnergyGalerkin:InvalidCoupledBlockPadding")
        end
    end

    methods (Static)
        function problem = createProblem
            N0 = sqrt(2e-5);
            z = linspace(-1200,0,5)';
            wvt = WVTransformBoussinesq( ...
                [24e3 20e3 1200],[6 10 5], ...
                N2Function=@(z)N0^2+0*z,latitude=45, ...
                shouldAntialias=false,z=z);
            [~,y] = ndgrid((0:wvt.Nx-1)'*wvt.Lx/wvt.Nx, ...
                (0:wvt.Ny-1)'*wvt.Ly/wvt.Ny);
            problem = WVTerrainEnergyGalerkin.fromTopography( ...
                wvt,topographicHeight=2.5*cos(2*pi*y/wvt.Ly));
        end
    end
end
