classdef TestWVTerrainEnergyConvergedPhysicalSubspaces < matlab.unittest.TestCase
    % Verify the Milestone-9.1 physical-subspace classification gate.

    properties
        problem
        audit
        horizontalLayout
        stateLayout
    end

    methods (TestClassSetup)
        function createReferenceAudit(testCase)
            addpath(fileparts(fileparts(mfilename("fullpath"))));
            N0 = sqrt(2e-5);
            z = linspace(-1200,0,5)';
            wvt = WVTransformBoussinesq( ...
                [24e3 20e3 1200],[6 10 5], ...
                N2Function=@(z)N0^2+0*z,latitude=45, ...
                shouldAntialias=false,z=z);
            [~,y] = ndgrid((0:wvt.Nx-1)'*wvt.Lx/wvt.Nx, ...
                (0:wvt.Ny-1)'*wvt.Ly/wvt.Ny);
            terrain = 2.5*cos(2*pi*y/wvt.Ly);
            testCase.problem = WVTerrainEnergyGalerkin.fromTopography( ...
                wvt,topographicHeight=terrain);
            testCase.horizontalLayout = testCase.problem.horizontalLayout;
            testCase.stateLayout = testCase.problem.stateLayout;
            testCase.audit = ...
                testCase.problem.auditConvergedPhysicalSubspaces( ...
                trustedModeBounds=[1 0], ...
                supportModeBounds=[1 2;1 3;1 4], ...
                stationaryPolynomialDegree=4, ...
                primitivePolynomialDegrees=[4;6;8], ...
                paddingFactors=[2;3], ...
                terrainScales=[0.125;0.25;0.5;1]);
        end
    end

    methods (Test)
        function physicalSubspaceGatePasses(testCase)
            audit = testCase.audit;
            testCase.verifyEqual(audit.status, ...
                "physical-subspace-classification-oracle")
            testCase.verifyTrue(audit.isCompatible)
            testCase.verifyEqual(audit.nextScope, ...
                "milestone-10-only-if-compatible-and-separately-authorized")
        end

        function nestedTransfersPreserveTheState(testCase)
            defects = cellfun( ...
                @(value)value.maximumDefect,testCase.audit.transfers);
            testCase.verifyLessThan(max(defects),1e-12)
            testCase.verifyLessThan( ...
                testCase.audit.stationary.guardDefect,1e-8)
            testCase.verifyLessThan( ...
                testCase.audit.stationary.paddingDefect,1e-8)
        end

        function stationarySpaceConvergesAndSplitsByAPV(testCase)
            stationary = testCase.audit.stationary;
            testCase.verifyTrue(stationary.isConverged)
            testCase.verifyEqual(stationary.dimension, ...
                stationary.dimension(1)*ones(size(stationary.dimension)))
            testCase.verifyLessThan(stationary.principalSine(end),1e-8)
            testCase.verifyEqual( ...
                size(stationary.apvBearingBasis,2) ...
                +size(stationary.zeroVolumeAPVBasis,2), ...
                stationary.dimension(end))
            testCase.verifyTrue(stationary.apvSplit.rankStable)
            testCase.verifyEqual( ...
                stationary.apvSplit.balancedEnstrophyEigenvalues, ...
                stationary.apvSplit.singularValues.^2)
        end

        function oneInternalWaveSubspaceIsValidated(testCase)
            internal = testCase.audit.internal;
            testCase.verifyGreaterThanOrEqual( ...
                internal.numberOfValidatedTracks,1)
            track = internal.tracks(find([internal.tracks.isValidated],1));
            testCase.verifyLessThan(track.principalSine(end),1e-3)
            testCase.verifyGreaterThanOrEqual( ...
                track.principalSine(1)/track.principalSine(end),4)
            testCase.verifyLessThan(track.frequencyDefect(end),1e-8)
            testCase.verifyLessThan(track.apvDefect(end),1e-8)
            testCase.verifyLessThan(track.bottomDefect(end),1e-8)
            testCase.verifyLessThan(track.strongResidual(end),1e-5)
            testCase.verifyGreaterThanOrEqual( ...
                min(track.strongResidual(1:end-1) ...
                ./track.strongResidual(2:end)),4)
            testCase.verifyLessThan(track.guardDefect,1e-8)
            testCase.verifyLessThan(track.paddingDefect,1e-8)
            testCase.verifyGreaterThanOrEqual( ...
                min(track.frequencyResolutionRatio),1e3)
            testCase.verifyGreaterThanOrEqual( ...
                min(track.blocks{end}.positiveFrequency), ...
                (1-1e-8)*testCase.audit.dense.inertialFrequency)
            testCase.verifyLessThan(max(track.bottomParticipation),1e-8)
        end

        function topographicBoundaryBranchRemainsUnresolved(testCase)
            testCase.verifyFalse(testCase.audit.boundary.isValidated)
            testCase.verifyEmpty( ...
                testCase.audit.classification.topographicBoundaryIndices)
            testCase.verifyGreaterThan( ...
                testCase.audit.boundary.track.guardDefect,1e-8)
        end

        function projectorsGiveACompleteEnergyDecomposition(testCase)
            classification = testCase.audit.classification;
            testCase.verifyEqual(classification.dimensionDefect,0)
            testCase.verifyLessThan( ...
                classification.maximumProjectorDefect,1e-10)
            testCase.verifyLessThan(classification.conjugacyDefect,1e-10)
            testCase.verifyGreaterThan( ...
                classification.dimension.remainder,0)
            testCase.verifyEqual( ...
                nnz(classification.dynamicLabels == "internal-wave"), ...
                numel(classification.internalWaveIndices))
            testCase.verifyEqual( ...
                nnz(classification.dynamicLabels == "unresolved-zero"), ...
                numel(classification.unresolvedZeroIndices))
            testCase.verifyEqual( ...
                nnz(classification.dynamicLabels ...
                == "unresolved-nonzero"), ...
                numel(classification.unresolvedNonzeroIndices))

            n = classification.dimension.state;
            state = complex((1:n)',flip((1:n)'))/n;
            forms = classification.energyForms;
            total = real(state'*testCase.audit.finest.energyMatrix*state);
            resolved = real(state'*(forms.stationary+forms.wave ...
                +forms.remainder)*state);
            testCase.verifyEqual(resolved,total,RelTol=1e-12)
            unresolvedFraction = real(state'*forms.remainder*state)/total;
            testCase.verifyGreaterThanOrEqual(unresolvedFraction,0)
            testCase.verifyLessThanOrEqual(unresolvedFraction,1+1e-12)
        end

        function publicLayoutsRemainUnchanged(testCase)
            testCase.verifyEqual(testCase.problem.horizontalLayout, ...
                testCase.horizontalLayout)
            testCase.verifyEqual(testCase.problem.stateLayout, ...
                testCase.stateLayout)
        end

        function validationRejectsIncompleteRefinement(testCase)
            testCase.verifyError(@() ...
                testCase.problem.auditConvergedPhysicalSubspaces( ...
                trustedModeBounds=[1 0], ...
                supportModeBounds=[1 2;1 3], ...
                stationaryPolynomialDegree=4, ...
                primitivePolynomialDegrees=[4;6], ...
                paddingFactors=[2;3], ...
                terrainScales=[0.125;0.25;0.5;1]), ...
                "WVTerrainEnergyGalerkin:InvalidPhysicalSubspaceDegrees")
            testCase.verifyError(@() ...
                testCase.problem.auditConvergedPhysicalSubspaces( ...
                trustedModeBounds=[1 0], ...
                supportModeBounds=[1 4;1 4;1 4], ...
                stationaryPolynomialDegree=4, ...
                primitivePolynomialDegrees=[4;6;8], ...
                paddingFactors=[2;3], ...
                terrainScales=[0.125;0.25;0.5;1]), ...
                "WVTerrainEnergyGalerkin:InvalidPhysicalSubspaceSupports")
        end
    end
end
