function audit = buildGlobalTangentStationaryCompressionAudit(problem, ...
    trustedBounds,supportBounds,targetWaveIndices,modeCounts, ...
    stationaryDegree,referenceDegrees,paddingFactors,terrainScales, ...
    providerOrders,shouldRunTwoDimensionalControl,cacheDirectory, ...
    quadratureOrder,modeSource)
% Build the Milestone-10.2.5 global tangent stationary oracle.

configuration = struct("trustedBounds",trustedBounds, ...
    "supportBounds",supportBounds,"targetWaveIndices",targetWaveIndices, ...
    "modeCounts",modeCounts,"stationaryDegree",stationaryDegree, ...
    "referenceDegrees",referenceDegrees,"paddingFactors",paddingFactors, ...
    "terrainScales",terrainScales,"providerOrders",providerOrders, ...
    "shouldRunTwoDimensionalControl",shouldRunTwoDimensionalControl, ...
    "quadratureOrder",quadratureOrder,"modeSource",modeSource);
[cached,cache] = loadAuditCache(problem,cacheDirectory,configuration);
if ~isempty(cached)
    audit = cached;
    audit.cache = cache;
    return
end
buildTimer = tic;

factorization = polynomialFactorizationSweep(problem,trustedBounds, ...
    supportBounds,stationaryDegree,referenceDegrees,paddingFactors, ...
    quadratureOrder);
tolerance = struct("factorization",1e-12,"traceRank",1e-11, ...
    "provider",1e-11,"lift",1e-10,"stationary",1e-10, ...
    "projector",1e-8,"frequency",1e-8,"apv",1e-8, ...
    "bottom",1e-10,"strong",1e-5,"drift",1e-8, ...
    "compression",2);
factorizationPasses = all([factorization.results.dimensionDefect] == 0) ...
    && max([factorization.results.projectorDefect]) ...
        <= tolerance.factorization ...
    && max([factorization.results.tangentLiftTraceDefect]) ...
        <= tolerance.factorization ...
    && max([factorization.results.tangentLiftEnergyDefect]) ...
        <= tolerance.factorization ...
    && max([factorization.results.tangentLiftAPVDefect]) ...
        <= tolerance.lift ...
    && max([factorization.results.tangentTraceDefect]) ...
        <= tolerance.traceRank ...
    && max([factorization.results.traceConjugacyDefect]) ...
        <= tolerance.traceRank ...
    && all([factorization.results.rankStable]);

training = struct("wasAttempted",false);
validation = struct("wasAttempted",false);
if ~factorizationPasses
    classification = "global-tangent-factorization-blocker";
    diagnosis = "The polynomial stationary oracle does not admit the proposed factorization within tolerance.";
else
    baselineSupport = supportBounds(ceil(size(supportBounds,1)/2),:);
    baselineDegree = referenceDegrees(ceil(numel(referenceDegrees)/2));
    if modeSource == "analytic"
        training = analyticModalTraining(problem,trustedBounds, ...
            baselineSupport,targetWaveIndices,modeCounts, ...
            stationaryDegree,baselineDegree,paddingFactors(1), ...
            terrainScales,providerOrders(end),quadratureOrder,tolerance);
        if training.analyticControlPasses ...
                && (training.materiallyImproves || training.passes)
            validation = analyticValidation(problem,trustedBounds, ...
                supportBounds,targetWaveIndices, ...
                training.bestUnqualifiedInteriorModeCount, ...
                stationaryDegree,referenceDegrees,paddingFactors, ...
                terrainScales,providerOrders(end),quadratureOrder, ...
                tolerance);
        end
        [classification,diagnosis] = ...
            classifyAnalyticTraining(training,validation,tolerance);
    else
        training = modalTraining(problem,trustedBounds,baselineSupport, ...
            targetWaveIndices,modeCounts,stationaryDegree,baselineDegree, ...
            paddingFactors(1),terrainScales,providerOrders,quadratureOrder, ...
            tolerance);
        [classification,diagnosis] = classifyTraining(training,tolerance);
    end
end

audit = struct;
if modeSource == "analytic"
    audit.scope = ...
        "milestone-10.2.5.1-analytic-global-tangent-attribution";
    audit.nextScope = "milestone-10.2.5.1-stop-for-review";
else
    audit.scope = "milestone-10.2.5-global-tangent-stationary-compression";
    audit.nextScope = "milestone-10.2.5-stop-for-review";
end
audit.status = classification;
audit.classification = classification;
audit.diagnosis = diagnosis;
audit.factorization = factorization;
audit.training = training;
audit.validation = validation;
audit.twoDimensionalControl = struct("wasRequested", ...
    shouldRunTwoDimensionalControl,"wasAttempted",false);
audit.gates = struct("factorization",factorizationPasses, ...
    "training",isfield(training,"passes") && training.passes);
audit.requiredTolerance = tolerance;
audit.trustedModeBounds = trustedBounds;
audit.supportModeBounds = supportBounds;
audit.targetWaveModeIndices = targetWaveIndices;
audit.interiorGeostrophicModeCounts = modeCounts;
audit.stationaryReferenceDegree = stationaryDegree;
audit.primitiveReferenceDegrees = referenceDegrees;
audit.paddingFactors = paddingFactors;
audit.terrainScales = terrainScales;
audit.internalModesEVPOrders = providerOrders;
audit.modeSource = modeSource;
audit.internalModesEVPCommit = ...
    "df86687e91faa31bf65941299062d125a96904b1";
audit.cache = cache;
audit = saveAuditCache(audit,cacheDirectory,configuration,cache, ...
    toc(buildTimer));
end

function training = modalTraining(problem,trustedBounds,supportBounds, ...
    targetWaveIndices,modeCounts,stationaryDegree,referenceDegree,padding, ...
    terrainScales,providerOrders,quadratureOrder,tolerance)
layout = retainedLayout(problem,supportBounds);
[primitive,c] = buildGlobalSmallTerrainPrimitiveAudit(problem, ...
    referenceDegree,quadratureOrder,1e-3,horizontalLayout=layout, ...
    paddingFactor=padding,trustedModeBounds=trustedBounds, ...
    rejectTerrainNyquist=true,evaluationScales=terrainScales, ...
    shouldAuditTangent=false);
catalog = modalCatalog(problem,c,max([modeCounts;targetWaveIndices]), ...
    providerOrders);
flatWaves = waveColumns(c,catalog,targetWaveIndices,trustedBounds);
reference = continueReference(c,primitive,flatWaves,terrainScales, ...
    trustedBounds,referenceDegree,stationaryDegree);
results = repmat(emptyModalCompressionResult,numel(modeCounts),1);
for iCount = 1:numel(modeCounts)
    results(iCount) = modalCompressionResult(c,primitive,catalog, ...
        reference,trustedBounds,referenceDegree,stationaryDegree, ...
        targetWaveIndices,modeCounts(iCount),terrainScales(end));
end

passes = arrayfun(@(value)modalResultPasses(value,tolerance),results);
selected = find(passes,1);
if isempty(selected)
    score = [[results.stationaryRepresentationDefect].' ...
        [results.maximumProjectorDefect].' (1:numel(results)).'];
    [~,order] = sortrows(score,[1 2 3]);
    selected = order(1);
    frozenCount = NaN;
else
    frozenCount = modeCounts(selected);
end
training = struct("wasAttempted",true,"results",results, ...
    "selectedIndex",selected,"frozenInteriorModeCount",frozenCount, ...
    "bestUnqualifiedInteriorModeCount",modeCounts(selected), ...
    "passes",~isnan(frozenCount),"supportModeBounds",supportBounds, ...
    "primitiveReferenceDegree",referenceDegree, ...
    "paddingFactor",padding,"terrainScales",terrainScales, ...
    "provider",catalog.diagnostics);
end

function training = analyticModalTraining(problem,trustedBounds, ...
    supportBounds,targetWaveIndices,modeCounts,stationaryDegree, ...
    referenceDegree,padding,terrainScales,comparisonOrder, ...
    quadratureOrder,tolerance)
layout = retainedLayout(problem,supportBounds);
[primitive,c] = buildGlobalSmallTerrainPrimitiveAudit(problem, ...
    referenceDegree,quadratureOrder,1e-3,horizontalLayout=layout, ...
    paddingFactor=padding,trustedModeBounds=trustedBounds, ...
    rejectTerrainNyquist=true,evaluationScales=terrainScales, ...
    shouldAuditTangent=false);
[analyticCatalog,providerCatalog] = analyticModalCatalog(problem,c, ...
    max([modeCounts;targetWaveIndices]),comparisonOrder);
flatWaves = waveColumns(c,analyticCatalog,targetWaveIndices,trustedBounds);
reference = continueReference(c,primitive,flatWaves,terrainScales, ...
    trustedBounds,referenceDegree,stationaryDegree);
nCount = numel(modeCounts);
results = repmat(emptyModalCompressionResult,nCount,1);
providerResults = repmat(emptyModalCompressionResult,nCount,1);
verticalDifference = zeros(nCount,1);
propagatedDifference = zeros(nCount,1);
for iCount = 1:nCount
    [results(iCount),analyticSubspace] = modalCompressionResult( ...
        c,primitive,analyticCatalog,reference,trustedBounds, ...
        referenceDegree,stationaryDegree,targetWaveIndices, ...
        modeCounts(iCount),terrainScales(end));
    [providerResults(iCount),providerSubspace] = modalCompressionResult( ...
        c,primitive,providerCatalog,reference,trustedBounds, ...
        referenceDegree,stationaryDegree,targetWaveIndices, ...
        modeCounts(iCount),terrainScales(end));
    verticalDifference(iCount) = zeroTraceCatalogDifference( ...
        analyticCatalog,providerCatalog,modeCounts(iCount), ...
        c.quadrature.weight);
    propagatedDifference(iCount) = projectorDefect( ...
        analyticSubspace.stationary,providerSubspace.stationary, ...
        primitive.evaluatedDirections(end).E);
end

physicalPasses = arrayfun( ...
    @(value)modalPhysicalPasses(value,tolerance),results);
selected = find(physicalPasses,1);
if isempty(selected)
    score = [[results.stationaryRepresentationDefect].' ...
        [results.maximumProjectorDefect].' (1:nCount).'];
    [~,order] = sortrows(score,[1 2 3]);
    selected = order(1);
    frozenCount = NaN;
else
    frozenCount = modeCounts(selected);
end
stationaryDefect = [results.stationaryRepresentationDefect].';
monotonic = all(stationaryDefect(2:end) ...
    <=1.01*stationaryDefect(1:end-1));
improvementFactor = stationaryDefect(1) ...
    /max(min(stationaryDefect),realmin);
materiallyImproves = monotonic && improvementFactor >=4;
analyticControl = analyticCatalog.diagnostics.analyticControl;
analyticControl.maximumConjugacyDefect = ...
    analyticScalarConjugacyDefect(c,analyticCatalog,max(modeCounts));
analyticControlValues = cell2mat(struct2cell(analyticControl));
analyticControlPasses = max(analyticControlValues) <=1e-12;

training = struct("wasAttempted",true,"results",results, ...
    "providerResults",providerResults,"selectedIndex",selected, ...
    "frozenInteriorModeCount",frozenCount, ...
    "bestUnqualifiedInteriorModeCount",modeCounts(selected), ...
    "passes",~isnan(frozenCount),"supportModeBounds",supportBounds, ...
    "primitiveReferenceDegree",referenceDegree, ...
    "paddingFactor",padding,"terrainScales",terrainScales, ...
    "comparisonEVPOrder",comparisonOrder, ...
    "analyticControl",analyticControl, ...
    "analyticControlPasses",analyticControlPasses, ...
    "verticalProviderProjectorDefect",verticalDifference, ...
    "propagatedProviderProjectorDefect",propagatedDifference, ...
    "stationaryProjectorImprovementFactor",improvementFactor, ...
    "isMonotonic",monotonic, ...
    "materiallyImproves",materiallyImproves, ...
    "provider",providerCatalog.diagnostics);
end

function validation = analyticValidation(problem,trustedBounds, ...
    supportBounds,targetWaveIndices,count,stationaryDegree, ...
    referenceDegrees,paddingFactors,terrainScales,comparisonOrder, ...
    quadratureOrder,tolerance)
baselineSupport = supportBounds(ceil(size(supportBounds,1)/2),:);
baselineDegree = referenceDegrees(ceil(numel(referenceDegrees)/2));
baselinePadding = paddingFactors(1);
fullScale = terrainScales(end);
support = cell(size(supportBounds,1),1);
for iSupport = 1:size(supportBounds,1)
    support{iSupport} = analyticValidationCase(problem,trustedBounds, ...
        supportBounds(iSupport,:),targetWaveIndices,count, ...
        stationaryDegree,baselineDegree,baselinePadding,fullScale, ...
        comparisonOrder,quadratureOrder);
end
padding = cell(numel(paddingFactors),1);
for iPadding = 1:numel(paddingFactors)
    padding{iPadding} = analyticValidationCase(problem,trustedBounds, ...
        baselineSupport,targetWaveIndices,count,stationaryDegree, ...
        baselineDegree,paddingFactors(iPadding),fullScale, ...
        comparisonOrder,quadratureOrder);
end
reference = cell(numel(referenceDegrees),1);
for iReference = 1:numel(referenceDegrees)
    reference{iReference} = analyticValidationCase(problem, ...
        trustedBounds,baselineSupport,targetWaveIndices,count, ...
        stationaryDegree,referenceDegrees(iReference), ...
        baselinePadding,fullScale,comparisonOrder,quadratureOrder);
end
amplitude = analyticValidationCase(problem,trustedBounds, ...
    baselineSupport,targetWaveIndices,count,stationaryDegree, ...
    baselineDegree,baselinePadding,terrainScales,comparisonOrder, ...
    quadratureOrder);

allCases = [support;padding;reference;{amplitude}];
resultCells = cellfun(@(value)value.results,allCases, ...
    "UniformOutput",false);
allResults = vertcat(resultCells{:});
passes = arrayfun(@(value)modalPhysicalPasses(value,tolerance), ...
    allResults);
validation = struct("wasAttempted",true,"passes",all(passes), ...
    "interiorGeostrophicModeCount",count,"support",{support}, ...
    "padding",{padding},"reference",{reference}, ...
    "amplitude",amplitude, ...
    "maximumStationaryProjectorDefect", ...
        max([allResults.stationaryRepresentationDefect]), ...
    "maximumWaveProjectorDefect", ...
        max([allResults.maximumProjectorDefect]), ...
    "maximumAPVDefect",max([allResults.maximumAPVDefect]), ...
    "maximumBottomDefect",max([allResults.maximumBottomDefect]), ...
    "maximumStrongResidual",max([allResults.maximumStrongResidual]), ...
    "minimumCompressionFactor",min([allResults.compressionFactor]));
end

function value = analyticValidationCase(problem,trustedBounds, ...
    supportBounds,targetWaveIndices,count,stationaryDegree, ...
    referenceDegree,padding,terrainScales,comparisonOrder,quadratureOrder)
layout = retainedLayout(problem,supportBounds);
[primitive,c] = buildGlobalSmallTerrainPrimitiveAudit(problem, ...
    referenceDegree,quadratureOrder,1e-3,horizontalLayout=layout, ...
    paddingFactor=padding,trustedModeBounds=trustedBounds, ...
    rejectTerrainNyquist=true,evaluationScales=terrainScales, ...
    shouldAuditTangent=false);
[catalog,~] = analyticModalCatalog(problem,c, ...
    max([count;targetWaveIndices]),comparisonOrder);
flatWaves = waveColumns(c,catalog,targetWaveIndices,trustedBounds);
reference = continueReference(c,primitive,flatWaves,terrainScales, ...
    trustedBounds,referenceDegree,stationaryDegree);
results = repmat(emptyModalCompressionResult,numel(terrainScales),1);
for iScale = 1:numel(terrainScales)
    results(iScale) = modalCompressionResult(c,primitive,catalog, ...
        reference,trustedBounds,referenceDegree,stationaryDegree, ...
        targetWaveIndices,count,terrainScales(iScale));
end
value = struct("supportModeBounds",supportBounds, ...
    "primitiveReferenceDegree",referenceDegree, ...
    "paddingFactor",padding,"terrainScales",terrainScales, ...
    "results",results);
end

function [classification,diagnosis] = classifyTraining(training,tolerance)
selected = training.results(training.selectedIndex);
if ~selected.providerPasses
    classification = "global-tangent-provider-blocker";
    diagnosis = "The isolated mixed-boundary provider does not satisfy its endpoint, invariant, or order-convergence gates.";
elseif selected.liftRankDefect > 0 ...
        || selected.maximumLiftTraceDefect > tolerance.lift ...
        || selected.maximumLiftEnergyDefect > tolerance.lift
    classification = "global-tangent-modal-blocker";
    diagnosis = "The mixed-boundary modal space does not support a full-rank physical-energy lift solve.";
elseif training.passes
    classification = "training-pass-validation-pending";
    diagnosis = "A smallest acceptable interior modal count was frozen on the zonal training case; independent validation remains.";
elseif selected.stationaryRepresentationDefect ...
        < 0.5*training.results(1).stationaryRepresentationDefect ...
        || selected.maximumProjectorDefect ...
        < 0.5*training.results(1).maximumProjectorDefect
    classification = "global-tangent-seed";
    diagnosis = "The global tangent modal construction materially improves convergence but does not pass every training gate.";
else
    classification = "global-tangent-modal-blocker";
    diagnosis = "The exact factorization passes, but the mixed-boundary modal construction does not converge on the training case.";
end
end

function [classification,diagnosis] = ...
    classifyAnalyticTraining(training,validation,tolerance)
selected = training.results(training.selectedIndex);
providerDifference = training.propagatedProviderProjectorDefect( ...
    training.selectedIndex);
if ~training.analyticControlPasses
    classification = "analytic-control-blocker";
    diagnosis = "The exact constant-N family does not satisfy its endpoint, equation, normalization, invariant, or conjugacy controls.";
elseif training.passes && providerDifference > tolerance.projector
    classification = "provider-conditioning-blocker";
    diagnosis = "The analytic modal construction passes, but the pinned order-128 provider changes the propagated stationary projector beyond tolerance.";
elseif training.passes && validation.passes ...
        && selected.compressionFactor >= tolerance.compression
    classification = "analytic-modal-acceleration";
    diagnosis = "The exact mixed-boundary family passes the physical gates with factor-two compression; variable-stratification qualification remains separate.";
elseif training.passes && validation.passes
    classification = "analytic-modal-equivalent";
    diagnosis = "The exact mixed-boundary family passes the physical gates without factor-two compression; variable-stratification qualification remains separate.";
elseif training.materiallyImproves || training.passes
    classification = "analytic-modal-seed";
    diagnosis = "The exact mixed-boundary family improves the stationary projector monotonically by at least a factor of four but does not pass every physical gate.";
else
    classification = "analytic-modal-blocker";
    diagnosis = "Removing provider error does not produce a rapidly convergent compressed stationary span on the training problem.";
end
end

function value = modalResultPasses(result,tolerance)
value = modalPhysicalPasses(result,tolerance) ...
    && result.compressionFactor >= tolerance.compression;
end

function value = modalPhysicalPasses(result,tolerance)
value = result.providerPasses ...
    && result.liftRankDefect == 0 ...
    && result.maximumLiftTraceDefect <= tolerance.lift ...
    && result.maximumLiftEnergyDefect <= tolerance.lift ...
    && result.maximumLiftAPVDefect <= tolerance.lift ...
    && result.stationaryRepresentationDefect <= tolerance.projector ...
    && result.stationaryRowDefect <= tolerance.stationary ...
    && result.stationaryBottomTangencyDefect <= tolerance.stationary ...
    && result.stationaryConjugacyDefect <= tolerance.stationary ...
    && result.maximumProjectorDefect <= tolerance.projector ...
    && result.maximumFrequencyDefect <= tolerance.frequency ...
    && result.maximumAPVDefect <= tolerance.apv ...
    && result.maximumBottomDefect <= tolerance.bottom ...
    && result.maximumStrongResidual <= tolerance.strong;
end

function sweep = polynomialFactorizationSweep(problem,trustedBounds, ...
    supportBounds,stationaryDegree,referenceDegrees,paddingFactors, ...
    quadratureOrder)
nSupport = size(supportBounds,1);
nPadding = numel(paddingFactors);
results = repmat(emptyFactorizationResult,nSupport,nPadding);
degree = referenceDegrees(ceil(numel(referenceDegrees)/2));
for iSupport = 1:nSupport
    layout = retainedLayout(problem,supportBounds(iSupport,:));
    for iPadding = 1:nPadding
        [primitive,c] = buildGlobalSmallTerrainPrimitiveAudit( ...
            problem,degree,quadratureOrder,1e-3, ...
            horizontalLayout=layout, ...
            paddingFactor=paddingFactors(iPadding), ...
            trustedModeBounds=trustedBounds, ...
            rejectTerrainNyquist=true,evaluationScales=1, ...
            shouldAuditTangent=false);
        direction = primitive.evaluatedDirections(1);
        exact = constructCompleteStationarySpace(c,direction, ...
            trustedBounds,stationaryDegree,stationaryDegree,1);
        full = factorGlobalTangentStationarySpace( ...
            c,direction,exact,"full");
        trusted = factorGlobalTangentStationarySpace( ...
            c,direction,exact,"trusted");
        result = full.diagnostics;
        result.supportModeBounds = supportBounds(iSupport,:);
        result.paddingFactor = paddingFactors(iPadding);
        result.primitiveReferenceDegree = degree;
        result.trustedProjectorDefect = ...
            trusted.diagnostics.projectorDefect;
        result.trustedDimensionDefect = ...
            trusted.diagnostics.dimensionDefect;
        result.traceRank = full.trace.rank;
        result.numberOfTraceCoordinates = ...
            size(full.trace.tangentBasis,1)-1;
        result.numberOfTangentTraceCoordinates = ...
            size(full.trace.tangentBasis,2);
        result.numberOfNonTangentTraceCoordinates = ...
            size(full.trace.complementBasis,2);
        result.minimumLiftSingularValue = ...
            full.solvers.tangent.minimumSingularValue;
        result.liftConditionNumber = ...
            full.solvers.tangent.conditionNumber;
        results(iSupport,iPadding) = result;
    end
end
sweep = struct("results",results,"referenceDegree",degree, ...
    "maximumProjectorDefect",max([results.projectorDefect]), ...
    "maximumTrustedProjectorDefect", ...
        max([results.trustedProjectorDefect]), ...
    "maximumDimensionDefect",max([results.dimensionDefect]), ...
    "allRanksStable",all([results.rankStable]));
end

function catalog = modalCatalog(problem,c,count,orders)
kappa = hypot(c.horizontalLayout.k,c.horizontalLayout.l);
uniqueKappa = unique(kappa(kappa > 0),"sorted");
high = cell(numel(uniqueKappa),1);
low = cell(numel(uniqueKappa),1);
difference = zeros(numel(uniqueKappa),1);
endpoint = zeros(numel(uniqueKappa),1);
invariant = zeros(numel(uniqueKappa),1);
analytic = zeros(numel(uniqueKappa),1);
for iKappa = 1:numel(uniqueKappa)
    boundaryHigh = buildBoundaryCompleteVerticalReferenceFamily( ...
        problem,uniqueKappa(iKappa),count,Inf,orders(end), ...
        c.quadrature.xi);
    boundaryLow = buildBoundaryCompleteVerticalReferenceFamily( ...
        problem,uniqueKappa(iKappa),count,Inf,orders(end-1), ...
        c.quadrature.xi);
    zeroHigh = buildZeroTraceGeostrophicVerticalFamily(problem, ...
        uniqueKappa(iKappa),count,orders(end),c.quadrature.xi, ...
        c.quadrature.weight);
    zeroLow = buildZeroTraceGeostrophicVerticalFamily(problem, ...
        uniqueKappa(iKappa),count,orders(end-1),c.quadrature.xi, ...
        c.quadrature.weight);
    high{iKappa} = struct("wave",boundaryHigh.wave, ...
        "bottom",boundaryHigh.bottom,"zeroTrace",zeroHigh);
    low{iKappa} = struct("wave",boundaryLow.wave, ...
        "bottom",boundaryLow.bottom,"zeroTrace",zeroLow);
    difference(iKappa) = maximumSubspaceDifference( ...
        high{iKappa},low{iKappa},c.quadrature.weight);
    endpoint(iKappa) = max([zeroHigh.diagnostics.bottomEndpointDefect, ...
        zeroHigh.diagnostics.surfaceEndpointDefect, ...
        boundaryHigh.diagnostics.waveEndpointDefect, ...
        boundaryHigh.diagnostics.bottomAPVDefect, ...
        boundaryHigh.diagnostics.bottomValueDefect]);
    invariant(iKappa) = max([ ...
        zeroHigh.diagnostics.energyDiagonalizationDefect, ...
        zeroHigh.diagnostics.enstrophyDiagonalizationDefect]);
    analytic(iKappa) = zeroHigh.diagnostics. ...
        constantStratificationAnalyticDefect;
end
catalog = struct("kappa",uniqueKappa,"family",{high}, ...
    "diagnostics",struct("providerDifference",max(difference), ...
    "maximumEndpointDefect",max(endpoint), ...
    "maximumInvariantDefect",max(invariant), ...
    "maximumAnalyticDefect",max(analytic),"orders",orders));
end

function [analyticCatalog,providerCatalog] = analyticModalCatalog( ...
    problem,c,count,comparisonOrder)
kappa = hypot(c.horizontalLayout.k,c.horizontalLayout.l);
uniqueKappa = unique(kappa(kappa > 0),"sorted");
analyticFamily = cell(numel(uniqueKappa),1);
providerFamily = cell(numel(uniqueKappa),1);
providerDifference = zeros(numel(uniqueKappa),1);
analyticEndpoint = zeros(numel(uniqueKappa),1);
analyticEquation = zeros(numel(uniqueKappa),1);
analyticNormalization = zeros(numel(uniqueKappa),1);
analyticEnergy = zeros(numel(uniqueKappa),1);
analyticEnstrophy = zeros(numel(uniqueKappa),1);
providerEndpoint = zeros(numel(uniqueKappa),1);
providerInvariant = zeros(numel(uniqueKappa),1);
providerAnalytic = zeros(numel(uniqueKappa),1);
for iKappa = 1:numel(uniqueKappa)
    boundary = buildBoundaryCompleteVerticalReferenceFamily( ...
        problem,uniqueKappa(iKappa),count,Inf,comparisonOrder, ...
        c.quadrature.xi);
    analyticZero = ...
        buildAnalyticZeroTraceGeostrophicVerticalFamily( ...
        problem,uniqueKappa(iKappa),count,c.quadrature.xi, ...
        c.quadrature.weight);
    providerZero = buildZeroTraceGeostrophicVerticalFamily(problem, ...
        uniqueKappa(iKappa),count,comparisonOrder,c.quadrature.xi, ...
        c.quadrature.weight);
    analyticFamily{iKappa} = struct("wave",boundary.wave, ...
        "bottom",boundary.bottom,"zeroTrace",analyticZero);
    providerFamily{iKappa} = struct("wave",boundary.wave, ...
        "bottom",boundary.bottom,"zeroTrace",providerZero);
    providerDifference(iKappa) = subspaceDifference( ...
        analyticZero.F,providerZero.F,c.quadrature.weight);
    analyticEndpoint(iKappa) = max([ ...
        analyticZero.diagnostics.bottomEndpointDefect, ...
        analyticZero.diagnostics.surfaceEndpointDefect]);
    analyticEquation(iKappa) = ...
        analyticZero.diagnostics.differentialEquationDefect;
    analyticNormalization(iKappa) = ...
        analyticZero.diagnostics.normalizationDefect;
    analyticEnergy(iKappa) = ...
        analyticZero.diagnostics.energyDiagonalizationDefect;
    analyticEnstrophy(iKappa) = ...
        analyticZero.diagnostics.enstrophyDiagonalizationDefect;
    providerEndpoint(iKappa) = max([ ...
        providerZero.diagnostics.bottomEndpointDefect, ...
        providerZero.diagnostics.surfaceEndpointDefect]);
    providerInvariant(iKappa) = max([ ...
        providerZero.diagnostics.energyDiagonalizationDefect, ...
        providerZero.diagnostics.enstrophyDiagonalizationDefect]);
    providerAnalytic(iKappa) = providerZero.diagnostics. ...
        constantStratificationAnalyticDefect;
end
analyticControl = struct( ...
    "maximumEndpointDefect",max(analyticEndpoint), ...
    "maximumDifferentialEquationDefect",max(analyticEquation), ...
    "maximumNormalizationDefect",max(analyticNormalization), ...
    "maximumEnergyDiagonalizationDefect",max(analyticEnergy), ...
    "maximumEnstrophyDiagonalizationDefect",max(analyticEnstrophy));
analyticCatalog = struct("kappa",uniqueKappa, ...
    "family",{analyticFamily},"diagnostics",struct( ...
    "providerDifference",0, ...
    "maximumEndpointDefect",max(analyticEndpoint), ...
    "maximumInvariantDefect",max([analyticEnergy analyticEnstrophy], ...
        [],"all"),"maximumAnalyticDefect",0, ...
    "comparisonOrder",comparisonOrder, ...
    "verticalProviderDifference",max(providerDifference), ...
    "analyticControl",analyticControl));
providerCatalog = struct("kappa",uniqueKappa, ...
    "family",{providerFamily},"diagnostics",struct( ...
    "providerDifference",0, ...
    "maximumEndpointDefect",max(providerEndpoint), ...
    "maximumInvariantDefect",max(providerInvariant), ...
    "maximumAnalyticDefect",max(providerAnalytic), ...
    "comparisonOrder",comparisonOrder));
end

function value = zeroTraceCatalogDifference(first,second,count,weight)
value = 0;
for iFamily = 1:numel(first.family)
    value = max(value,subspaceDifference( ...
        first.family{iFamily}.zeroTrace.F(:,1:count), ...
        second.family{iFamily}.zeroTrace.F(:,1:count),weight));
end
end

function value = analyticScalarConjugacyDefect(c,catalog,count)
scalar = zeroTraceModalScalar(c,catalog,count);
nonzero = find(hypot(c.horizontalLayout.k,c.horizontalLayout.l) > 0);
conjugate = zeros(numel(nonzero)*count,1);
for iHorizontal = 1:numel(nonzero)
    kMode = c.horizontalLayout.kMode(nonzero(iHorizontal));
    lMode = c.horizontalLayout.lMode(nonzero(iHorizontal));
    partner = find(c.horizontalLayout.kMode(nonzero) == -kMode ...
        & c.horizontalLayout.lMode(nonzero) == -lMode,1);
    if isempty(partner)
        error("WVTerrainEnergyGalerkin:IncompleteAnalyticConjugateLayout", ...
            "Every analytic mixed-boundary Fourier mode needs its signed conjugate.")
    end
    columns = (iHorizontal-1)*count+(1:count);
    conjugate(columns) = (partner-1)*count+(1:count);
end
fields = ["values" "valuesXi" "valuesX" "valuesY"];
value = 0;
for field = fields
    values = scalar.(field);
    first = values(:,conjugate);
    second = conj(values);
    value = max(value,norm(first-second,"fro") ...
        /max(norm(first,"fro")+norm(second,"fro"),realmin));
end
end

function [result,subspace] = modalCompressionResult( ...
    c,primitive,catalog,reference, ...
    trustedBounds,referenceDegree,stationaryDegree,targetWaveIndices, ...
    count,terrainScale)
iDirection = find(abs(primitive.evaluationScales-terrainScale) ...
    <=100*eps*max(abs(terrainScale),1),1);
if isempty(iDirection)
    error("WVTerrainEnergyGalerkin:UnavailableGlobalTangentTerrainScale", ...
        "terrainScale must be one of the primitive evaluation scales.")
end
direction = primitive.evaluatedDirections(iDirection);
if isfield(reference,"history") && numel(reference.history) > 1
    referenceAtScale = reference.history(iDirection);
else
    referenceAtScale = reference;
end
exact = constructCompleteStationarySpace(c,direction,trustedBounds, ...
    referenceDegree,stationaryDegree,terrainScale);
polynomialFactor = factorGlobalTangentStationarySpace( ...
    c,direction,exact,"full");
zeroScalar = zeroTraceModalScalar(c,catalog,count);
zeroScalar.terrainScale = terrainScale;
[zeroStates,zeroRepresentation] = projectGeostrophicState(c,zeroScalar);
bottomScalar = bottomPivotScalar(c,catalog, ...
    polynomialFactor.trace.selectedHorizontal);
bottomScalar.terrainScale = terrainScale;

tangentSeed = combineScalar(bottomScalar, ...
    polynomialFactor.trace.tangentBasis);
[tangentSeedStates,tangentSeedRepresentation] = ...
    projectGeostrophicState(c,tangentSeed);
[tangentStates,~,tangentSolve] = energyMinimalLifts( ...
    zeroStates,zeroScalar,tangentSeedStates,tangentSeed,direction.E);

nonTangentSeed = combineScalar(bottomScalar, ...
    polynomialFactor.trace.complementBasis);
[nonTangentSeedStates,nonTangentSeedRepresentation] = ...
    projectGeostrophicState(c,nonTangentSeed);
[nonTangentStates,nonTangentScalar,nonTangentSolve] = ...
    energyMinimalLifts(zeroStates,zeroScalar, ...
    nonTangentSeedStates,nonTangentSeed,direction.E);

stationaryMean = stationaryMeanColumns(c,catalog,count);
[stationary,stationaryOrthonormalization] = ...
    energyOrthonormalizeColumns( ...
    [zeroStates tangentStates stationaryMean],direction.E);
if ~isempty(nonTangentStates)
    nonTangentStates = nonTangentStates-stationary ...
        *(stationary'*direction.E*nonTangentStates);
    [nonTangentStates,~, ...
        nonTangentOrthonormalization] = energyOrthonormalize( ...
        nonTangentStates,nonTangentScalar,direction.E);
else
    nonTangentOrthonormalization = emptyOrthonormalization;
end

waves = waveColumns(c,catalog,targetWaveIndices,[Inf Inf]);
mean = inertialMeanColumns(c,catalog,count);
rawAmbient = [waves stationary nonTangentStates mean];
[ambient,ambientRank] = energyOrthonormalizeColumns( ...
    rawAmbient,direction.E);
dense = reducedPhysicalEigensystem( ...
    ambient,stationary,direction);
selected = selectByOverlap(dense.vectors,referenceAtScale.basis, ...
    direction.E,size(referenceAtScale.basis,2));
basis = energyNormalizeColumns(dense.vectors(:,selected),direction.E);
frequency = columnRayleighQuotients( ...
    basis,direction.E,1i*direction.J);
physical = physicalDiagnostics(c,direction,basis,frequency);

stationaryRepresentation = exact.trustedBasis ...
    -stationary*(stationary'*direction.E*exact.trustedBasis);
R = chol((direction.E+direction.E')/2);
stationaryRepresentationDefect = norm(R*stationaryRepresentation,"fro") ...
    /max(norm(R*exact.trustedBasis,"fro"),realmin);
liftAPV = norm(zeroStates'*direction.E*tangentStates,"fro") ...
    /max(norm(zeroStates,"fro")*norm(direction.E,"fro") ...
    *norm(tangentStates,"fro"),realmin);
provider = catalog.diagnostics;
result = emptyModalCompressionResult;
result.interiorGeostrophicModeCount = count;
result.numberOfModalCoordinates = size(ambient,2);
result.numberOfPrimitiveCoordinates = size(direction.E,1);
result.compressionFactor = size(direction.E,1)/size(ambient,2);
result.numberOfStationaryCoordinates = size(stationary,2);
result.numberOfTangentTraceCoordinates = size(tangentStates,2);
result.numberOfNonTangentTraceCoordinates = size(nonTangentStates,2);
result.providerPasses = provider.providerDifference <=1e-11 ...
    && provider.maximumEndpointDefect <=1e-11 ...
    && provider.maximumInvariantDefect <=1e-11 ...
    && (isnan(provider.maximumAnalyticDefect) ...
    || provider.maximumAnalyticDefect <=1e-11);
result.liftRankDefect = tangentSolve.rankDefect ...
    +nonTangentSolve.rankDefect;
result.maximumLiftTraceDefect = max( ...
    tangentSolve.traceDefect,nonTangentSolve.traceDefect);
result.maximumLiftEnergyDefect = max( ...
    tangentSolve.energyDefect,nonTangentSolve.energyDefect);
result.maximumLiftAPVDefect = liftAPV;
result.stationaryRepresentationDefect = ...
    stationaryRepresentationDefect;
result.stationaryRowDefect = normalizedProduct( ...
    direction.J,stationary);
result.stationaryBottomTangencyDefect = normalizedProduct( ...
    direction.R,stationary);
result.stationaryConjugacyDefect = subspaceConjugacyDefect( ...
    stationary,direction.E,c.coordinateConjugateIndex);
result.maximumProjectorDefect = projectorDefect( ...
    basis,referenceAtScale.basis,direction.E);
result.maximumFrequencyDefect = sortedFrequencyDefect( ...
    frequency,referenceAtScale.frequency);
result.maximumRitzResidual = physical.maximumRitzResidual;
result.maximumAPVDefect = physical.maximumAPVDefect;
result.maximumBottomDefect = physical.maximumBottomDefect;
result.maximumStrongResidual = physical.maximumStrongResidual;
result.energyHermitianDefect = norm(direction.E-direction.E',"fro") ...
    /max(norm(direction.E,"fro"),realmin);
result.exchangeSkewHermitianDefect = ...
    norm(direction.J+direction.J',"fro") ...
    /max(norm(direction.J,"fro"),realmin);
result.ambientRankDefect = ambientRank.rankDefect;
result.minimumAmbientSingularValue = ...
    ambientRank.minimumSingularValue;
result.liftDiagnostics = struct("tangent",tangentSolve, ...
    "nonTangent",nonTangentSolve, ...
    "stationaryOrthonormalization",stationaryOrthonormalization, ...
    "nonTangentOrthonormalization",nonTangentOrthonormalization);
result.representation = struct("zeroTrace",zeroRepresentation, ...
    "tangentSeed",tangentSeedRepresentation, ...
    "nonTangentSeed",nonTangentSeedRepresentation);
subspace = struct("stationary",stationary,"dynamical",basis, ...
    "ambient",ambient);
end

function scalar = zeroTraceModalScalar(c,catalog,count)
nGrid = c.nXY*c.nZ;
nColumns = nnz(hypot(c.horizontalLayout.k, ...
    c.horizontalLayout.l) > 0)*count;
scalar = emptyScalar(nGrid,c.nXY,nColumns);
column = 0;
for iHorizontal = 1:c.nK
    k = c.horizontalLayout.k(iHorizontal);
    l = c.horizontalLayout.l(iHorizontal);
    kappa = hypot(k,l);
    if kappa == 0
        continue
    end
    family = catalogFamily(catalog,kappa);
    for iMode = 1:count
        column = column+1;
        F = family.zeroTrace.F(:,iMode);
        Fz = family.zeroTrace.Fz(:,iMode);
        scalar.values(:,column) = kron(F,c.phase(:,iHorizontal));
        scalar.valuesXi(:,column) = kron(Fz,c.phase(:,iHorizontal));
        scalar.valuesX(:,column) = 1i*k*scalar.values(:,column);
        scalar.valuesY(:,column) = 1i*l*scalar.values(:,column);
    end
end
scalar.terrainScale = 1;
end

function scalar = bottomPivotScalar(c,catalog,selected)
nGrid = c.nXY*c.nZ;
nColumns = numel(selected);
scalar = emptyScalar(nGrid,c.nXY,nColumns);
[~,iBottom] = min(c.quadrature.xi);
for iSelected = 1:nColumns
    iHorizontal = selected(iSelected);
    k = c.horizontalLayout.k(iHorizontal);
    l = c.horizontalLayout.l(iHorizontal);
    kappa = hypot(k,l);
    if kappa == 0
        continue
    end
    family = catalogFamily(catalog,kappa);
    F = family.bottom.psi;
    Fz = -(c.wvt.N2Function(c.quadrature.xi)/c.wvt.f) ...
        .*family.bottom.eta;
    normalization = F(iBottom);
    if abs(normalization) <=100*eps*max(abs(F),[],"all")
        error("WVTerrainEnergyGalerkin:GlobalTangentBottomPivotFailure", ...
            "The public bottom inversion has a vanishing streamfunction trace.")
    end
    F = F/normalization;
    Fz = Fz/normalization;
    scalar.values(:,iSelected) = kron(F,c.phase(:,iHorizontal));
    scalar.valuesXi(:,iSelected) = kron(Fz,c.phase(:,iHorizontal));
    scalar.valuesX(:,iSelected) = 1i*k*scalar.values(:,iSelected);
    scalar.valuesY(:,iSelected) = 1i*l*scalar.values(:,iSelected);
    scalar.bottomValues(:,iSelected) = c.phase(:,iHorizontal);
end
scalar.terrainScale = 1;
end

function scalar = emptyScalar(nGrid,nBottom,nColumns)
scalar = struct("values",zeros(nGrid,nColumns), ...
    "valuesXi",zeros(nGrid,nColumns), ...
    "valuesX",zeros(nGrid,nColumns), ...
    "valuesY",zeros(nGrid,nColumns), ...
    "bottomValues",zeros(nBottom,nColumns), ...
    "coefficientBasis",eye(nColumns),"terrainScale",1);
end

function scalar = combineScalar(scalar,transform)
fields = ["values","valuesXi","valuesX","valuesY", ...
    "bottomValues","coefficientBasis"];
for field = fields
    scalar.(field) = scalar.(field)*transform;
end
end

function family = catalogFamily(catalog,kappa)
index = find(abs(catalog.kappa-kappa) ...
    <=100*eps*max(kappa,1),1);
family = catalog.family{index};
end

function difference = maximumSubspaceDifference(high,low,weight)
wave = subspaceDifference(high.wave.F,low.wave.F,weight);
zero = subspaceDifference( ...
    high.zeroTrace.F,low.zeroTrace.F,weight);
bottom = subspaceDifference( ...
    high.bottom.psi,low.bottom.psi,weight);
difference = max([wave zero bottom]);
end

function value = subspaceDifference(first,second,weight)
[first,~,~] = svd(sqrt(weight).*first,"econ");
[second,~,~] = svd(sqrt(weight).*second,"econ");
value = norm(first*first'-second*second',"fro") ...
    /max(norm(first*first',"fro")+norm(second*second',"fro"),realmin);
end

function [states,scalar,diagnostics] = energyMinimalLifts( ...
    zeroStates,zeroScalar,seedStates,seedScalar,E)
if isempty(seedStates)
    states = seedStates;
    scalar = seedScalar;
    diagnostics = emptyLiftDiagnostics;
    diagnostics.rank = size(zeroStates,2);
    return
end
R = chol((E+E')/2);
whitenedZero = R*zeroStates;
[U,S,V] = svd(whitenedZero,"econ");
singularValues = diag(S);
tolerance = max(size(whitenedZero))*eps(max(singularValues))*100;
rankValue = nnz(singularValues > tolerance);
rankDefect = size(zeroStates,2)-rankValue;
if rankDefect > 0
    states = seedStates;
    scalar = seedScalar;
    diagnostics = emptyLiftDiagnostics;
    diagnostics.rank = rankValue;
    diagnostics.rankDefect = rankDefect;
    diagnostics.singularValues = singularValues;
    return
end
correction = -V*((U'*(R*seedStates))./singularValues);
states = seedStates+zeroStates*correction;
scalar = seedScalar;
fields = ["values","valuesXi","valuesX","valuesY", ...
    "bottomValues"];
for field = fields
    scalar.(field) = seedScalar.(field)+zeroScalar.(field)*correction;
end
scalar.coefficientBasis = eye(size(scalar.values,2));
traceScale = norm(seedScalar.bottomValues,"fro");
energyScale = norm(zeroStates,"fro")*norm(E,"fro") ...
    *norm(states,"fro");
diagnostics = struct("rank",rankValue,"rankDefect",0, ...
    "singularValues",singularValues, ...
    "minimumSingularValue",singularValues(end), ...
    "conditionNumber",singularValues(1)/singularValues(end), ...
    "traceDefect",norm(scalar.bottomValues ...
        -seedScalar.bottomValues,"fro")/max(traceScale,realmin), ...
    "energyDefect",norm(zeroStates'*E*states,"fro") ...
        /max(energyScale,realmin));
end

function value = emptyLiftDiagnostics
value = struct("rank",0,"rankDefect",0, ...
    "singularValues",zeros(0,1),"minimumSingularValue",NaN, ...
    "conditionNumber",NaN,"traceDefect",0,"energyDefect",0);
end

function [states,scalar,diagnostics] = energyOrthonormalize(states,scalar,E)
[states,diagnostics,transform] = energyOrthonormalizeColumns(states,E);
fields = ["values","valuesXi","valuesX","valuesY", ...
    "bottomValues"];
for field = fields
    scalar.(field) = scalar.(field)*transform;
end
scalar.coefficientBasis = eye(size(states,2));
end

function [states,diagnostics,transform] = energyOrthonormalizeColumns(states,E)
if isempty(states)
    transform = zeros(0);
    diagnostics = emptyOrthonormalization;
    return
end
R = chol((E+E')/2);
[~,S,V] = svd(R*states,"econ");
singularValues = diag(S);
tolerance = max(size(states))*eps(max(singularValues))*100;
rankValue = nnz(singularValues > tolerance);
transform = V(:,1:rankValue)./singularValues(1:rankValue).';
states = states*transform;
diagnostics = struct("rank",rankValue, ...
    "rankDefect",size(V,2)-rankValue, ...
    "singularValues",singularValues, ...
    "minimumSingularValue",singularValues(rankValue), ...
    "conditionNumber",singularValues(1)/singularValues(rankValue), ...
    "defect",norm(states'*E*states-eye(rankValue),"fro") ...
        /sqrt(rankValue));
end

function value = emptyOrthonormalization
value = struct("rank",0,"rankDefect",0, ...
    "singularValues",zeros(0,1),"minimumSingularValue",NaN, ...
    "conditionNumber",NaN,"defect",0);
end

function [G,diagnostics] = projectGeostrophicState(c,scalar)
H3 = scalar.terrainScale*repmat(c.H,c.nZ,1);
HX3 = scalar.terrainScale*repmat(c.HX,c.nZ,1);
HY3 = scalar.terrainScale*repmat(c.HY,c.nZ,1);
gamma = 1-H3;
gammaX = -HX3;
gammaY = -HY3;
N2 = c.wvt.N2Function(gamma.*c.xiGrid);
if isscalar(N2)
    N2 = repmat(N2,size(c.xiGrid));
end
N2 = N2(:);
u = -gamma.*scalar.valuesY+c.xiGrid.*gammaY.*scalar.valuesXi;
v = gamma.*scalar.valuesX-c.xiGrid.*gammaX.*scalar.valuesXi;
w = c.xiGrid.*(gammaX.*scalar.valuesY-gammaY.*scalar.valuesX);
eta = -c.wvt.f*scalar.valuesXi./(gamma.*N2);
[uColumns,vColumns,wColumns,etaColumns] = componentColumns(c);
raw = zeros(c.nX,size(u,2));
raw(uColumns,:) = weightedFit(c.Ru(:,uColumns),u,c.volumeWeight);
raw(vColumns,:) = weightedFit(c.Rv(:,vColumns),v,c.volumeWeight);
raw(wColumns,:) = weightedFit(c.Rwh(:,wColumns),w,c.volumeWeight);
raw(etaColumns,:) = weightedFit( ...
    c.Reta(:,etaColumns),eta,c.volumeWeight);
G = c.N'*raw;
representedRaw = c.N*G;
represented = [c.Ru*representedRaw,c.Rv*representedRaw, ...
    c.Rwh*representedRaw,c.Reta*representedRaw];
targets = [u,v,w,eta];
diagnostics = struct("rawCoordinateDefect", ...
    relativeDifference(representedRaw,raw), ...
    "maximumDefect",relativeDifference(represented,targets), ...
    "continuityDefect",norm(c.continuity*representedRaw,"fro") ...
        /max(norm(c.continuity,"fro") ...
        *norm(representedRaw,"fro"),realmin));
end

function columns = waveColumns(c,catalog,modeIndices,bounds)
columns = zeros(size(c.N,2),0);
for iHorizontal = 1:c.nK
    if abs(c.horizontalLayout.kMode(iHorizontal)) > bounds(1) ...
            || abs(c.horizontalLayout.lMode(iHorizontal)) > bounds(2)
        continue
    end
    k = c.horizontalLayout.k(iHorizontal);
    l = c.horizontalLayout.l(iHorizontal);
    kappa = hypot(k,l);
    if kappa == 0
        continue
    end
    family = catalogFamily(catalog,kappa);
    for iMode = reshape(modeIndices,1,[])
        for sigma = [-1 1]
            omega = family.wave.omega(iMode);
            h = family.wave.h(iMode);
            F = family.wave.F(:,iMode);
            G = family.wave.G(:,iMode);
            state = struct( ...
                "u",(k*omega-sigma*1i*c.wvt.f*l) ...
                    /(omega*kappa)*F, ...
                "v",(l*omega+sigma*1i*c.wvt.f*k) ...
                    /(omega*kappa)*F, ...
                "w",-1i*kappa*h*G, ...
                "eta",-sigma*kappa*h/omega*G);
            columns(:,end+1) = embedState( ...
                c,iHorizontal,state); %#ok<AGROW>
        end
    end
end
end

function columns = inertialMeanColumns(c,catalog,count)
iHorizontal = find(c.horizontalLayout.kMode == 0 ...
    & c.horizontalLayout.lMode == 0,1);
if isempty(iHorizontal)
    columns = zeros(size(c.N,2),0);
    return
end
family = catalog.family{1};
constant = ones(size(c.quadrature.xi));
columns = zeros(size(c.N,2),0);
profiles = [constant family.wave.F(:,1:min(count, ...
    size(family.wave.F,2)))];
for iProfile = 1:size(profiles,2)
    for sigma = [-1 1]
        state = struct("u",profiles(:,iProfile), ...
            "v",sigma*1i*profiles(:,iProfile), ...
            "w",zeros(size(constant)),"eta",zeros(size(constant)));
        columns(:,end+1) = embedState( ...
            c,iHorizontal,state); %#ok<AGROW>
    end
end
end

function columns = stationaryMeanColumns(c,catalog,count)
iHorizontal = find(c.horizontalLayout.kMode == 0 ...
    & c.horizontalLayout.lMode == 0,1);
if isempty(iHorizontal)
    columns = zeros(size(c.N,2),0);
    return
end
family = catalog.family{1};
constant = ones(size(c.quadrature.xi));
columns = zeros(size(c.N,2),0);
etaProfiles = family.zeroTrace.eta(:,1:min(count, ...
    size(family.zeroTrace.eta,2)));
for iProfile = 1:size(etaProfiles,2)
    state = struct("u",zeros(size(constant)), ...
        "v",zeros(size(constant)),"w",zeros(size(constant)), ...
        "eta",etaProfiles(:,iProfile));
    columns(:,end+1) = embedState(c,iHorizontal,state); %#ok<AGROW>
end
chi = -c.quadrature.xi/c.wvt.Lz;
state = struct("u",zeros(size(chi)),"v",zeros(size(chi)), ...
    "w",zeros(size(chi)),"eta",chi);
columns(:,end+1) = embedState(c,iHorizontal,state);
end

function reference = continueReference(c,primitive,seed,scales,trusted, ...
    fullDegree,trustedDegree)
previous = energyNormalizeColumns(seed,primitive.evaluatedDirections(1).E);
history = repmat(struct("basis",zeros(0), ...
    "frequency",zeros(0,1)),numel(scales),1);
for iScale = 1:numel(scales)
    direction = primitive.evaluatedDirections(iScale);
    stationary = constructCompleteStationarySpace(c,direction, ...
        trusted,fullDegree,trustedDegree,scales(iScale));
    dense = physicalEigensystem(direction,stationary.trustedBasis);
    selected = selectByOverlap(dense.vectors,previous,direction.E, ...
        size(previous,2));
    previous = energyNormalizeColumns( ...
        dense.vectors(:,selected),direction.E);
    history(iScale).basis = previous;
    history(iScale).frequency = columnRayleighQuotients( ...
        previous,direction.E,1i*direction.J);
end
reference = history(end);
reference.history = history;
end

function dense = physicalEigensystem(direction,stationary)
E = direction.E;
R = chol((E+E')/2);
Yg = R*stationary;
if isempty(Yg)
    complement = eye(size(E));
else
    [complete,~] = qr(Yg);
    complement = complete(:,size(Yg,2)+1:end);
end
K = R'\(1i*direction.J/R);
reduced = complement'*K*complement;
[vectors,form] = schur((reduced+reduced')/2,"complex");
frequency = real(diag(form));
[frequency,order] = sort(frequency);
vectors = R\(complement*vectors(:,order));
dense = struct("vectors",energyNormalizeColumns(vectors,E), ...
    "frequency",frequency);
end

function dense = reducedPhysicalEigensystem(X,stationary,direction)
E = direction.E;
H = X'*E*X;
J = X'*direction.J*X;
stationaryCoordinate = H\(X'*E*stationary);
R = chol((H+H')/2);
Yg = R*stationaryCoordinate;
if isempty(Yg)
    complement = eye(size(H));
else
    [complete,~] = qr(Yg);
    complement = complete(:,size(Yg,2)+1:end);
end
K = R'\(1i*J/R);
reduced = complement'*K*complement;
[vectors,form] = schur((reduced+reduced')/2,"complex");
frequency = real(diag(form));
[frequency,order] = sort(frequency);
coordinates = R\(complement*vectors(:,order));
dense = struct("vectors",energyNormalizeColumns(X*coordinates,E), ...
    "frequency",frequency);
end

function selected = selectByOverlap(vectors,reference,E,count)
overlap = abs(vectors'*E*reference).^2;
score = sum(overlap,2);
[~,order] = sort(score,"descend");
selected = sort(order(1:min(count,numel(order))));
end

function diagnostics = physicalDiagnostics(c,direction,basis,frequency)
H = direction.E;
A = 1i*direction.J;
R = chol((H+H')/2);
residual = A*basis-(H*basis).*frequency.';
ritz = vecnorm(R'\residual,2,1).' ...
    ./max(norm(R'\(A/R),2)+abs(frequency),realmin);
trustedRows = find(repmat(c.layout.trustedHorizontalModes,c.nZ,1));
weightedQ = sqrt(c.apvVerticalWeight(trustedRows)) ...
    .*direction.QProjected(trustedRows,:);
apv = vecnorm(weightedQ*basis,2,1).' ...
    /max(norm(weightedQ/R,2),realmin);
bottomResidual = -1i*(direction.B*basis).*frequency.' ...
    -direction.R*basis;
bottomScale = abs(frequency)*norm(direction.B/R,2) ...
    +norm(direction.R/R,2);
bottom = vecnorm(bottomResidual,2,1).'./max(bottomScale,realmin);
strong = strongModeDiagnostics(c,direction,basis,frequency);
diagnostics = struct("maximumRitzResidual",max(ritz,[],"all"), ...
    "maximumAPVDefect",max(apv,[],"all"), ...
    "maximumBottomDefect",max(bottom,[],"all"), ...
    "maximumStrongResidual",strong.maximumResidual);
end

function diagnostics = strongModeDiagnostics(c,direction,C,frequency)
rawState = c.N*C;
pressure = direction.pressureMap*C;
stateTendency = -1i*rawState.*frequency.';
residual = direction.matrices.S*[stateTendency;pressure] ...
    -direction.matrices.F*C;
terms = {direction.matrices.S*[stateTendency;pressure], ...
    -direction.matrices.F*C};
scale = zeros(size(residual,2),1);
for iTerm = 1:numel(terms)
    scale = scale+vecnorm(terms{iTerm},2,1).';
end
defect = vecnorm(residual,2,1).'./max(scale,realmin);
diagnostics = struct("maximumResidual",max(defect,[],"all"));
end

function [coordinate,defect] = embedState(c,iHorizontal,state)
weight = c.quadrature.weight;
uCoefficient = weightedFit(c.spaces.F,state.u,weight);
vCoefficient = weightedFit(c.spaces.F,state.v,weight);
wCoefficient = weightedFit(c.spaces.G,state.w,weight);
etaCoefficient = weightedFit(c.spaces.H,state.eta,weight);
rawBlock = [uCoefficient;vCoefficient;wCoefficient;etaCoefficient];
rawRows = (iHorizontal-1)*c.nXBlock+(1:c.nXBlock);
admissible = c.layout.admissibleRanges{iHorizontal};
localBasis = c.N(rawRows,admissible);
coordinate = zeros(size(c.N,2),1);
coordinate(admissible) = localBasis\rawBlock;
represented = localBasis*coordinate(admissible);
defect = norm(represented-rawBlock)/max(norm(rawBlock),realmin);
end

function coefficient = weightedFit(reconstruction,values,weight)
coefficient = (reconstruction'*(weight.*reconstruction)) ...
    \(reconstruction'*(weight.*values));
end

function [uColumns,vColumns,wColumns,etaColumns] = componentColumns(c)
uColumns = zeros(c.nK*c.nF,1);
vColumns = zeros(c.nK*c.nF,1);
wColumns = zeros(c.nK*c.nG,1);
etaColumns = zeros(c.nK*c.nH,1);
for iK = 1:c.nK
    block = (iK-1)*c.nXBlock;
    uColumns((iK-1)*c.nF+(1:c.nF)) = block+(1:c.nF);
    vColumns((iK-1)*c.nF+(1:c.nF)) = block+c.nF+(1:c.nF);
    wColumns((iK-1)*c.nG+(1:c.nG)) = block+2*c.nF+(1:c.nG);
    etaColumns((iK-1)*c.nH+(1:c.nH)) = ...
        block+2*c.nF+c.nG+(1:c.nH);
end
end

function values = energyNormalizeColumns(values,E)
if isempty(values)
    return
end
R = chol((E+E')/2);
[~,S,V] = svd(R*values,"econ");
singularValues = diag(S);
tolerance = max(size(values))*eps(max(singularValues))*100;
rankValue = nnz(singularValues > tolerance);
values = values*V(:,1:rankValue)./singularValues(1:rankValue).';
end

function value = projectorDefect(first,second,E)
if size(first,2) ~= size(second,2)
    value = Inf;
    return
end
R = chol((E+E')/2);
first = R*energyNormalizeColumns(first,E);
second = R*energyNormalizeColumns(second,E);
value = norm(first*first'-second*second',"fro") ...
    /max(norm(first*first',"fro")+norm(second*second',"fro"),realmin);
end

function value = sortedFrequencyDefect(first,second)
first = sort(real(first));
second = sort(real(second));
if numel(first) ~= numel(second)
    value = Inf;
else
    value = norm(first-second) ...
        /max(norm(first)+norm(second),realmin);
end
end

function value = columnRayleighQuotients(X,H,A)
numerator = sum(conj(X).*(A*X),1);
denominator = sum(conj(X).*(H*X),1);
value = real(numerator./denominator).';
end

function value = normalizedProduct(operator,state)
value = norm(operator*state,"fro") ...
    /max(norm(operator,"fro")*norm(state,"fro"),realmin);
end

function value = subspaceConjugacyDefect(X,H,conjugateIndex)
n = size(H,1);
C = sparse((1:n)',conjugateIndex,1,n,n);
P = X*(X'*H);
value = norm(P*C-C*conj(P),"fro") ...
    /max(2*norm(P,"fro"),realmin);
end

function value = relativeDifference(first,second)
value = norm(first-second,"fro") ...
    /max(norm(first,"fro")+norm(second,"fro"),realmin);
end

function value = emptyModalCompressionResult
value = struct("interiorGeostrophicModeCount",0, ...
    "numberOfModalCoordinates",0,"numberOfPrimitiveCoordinates",0, ...
    "compressionFactor",0,"numberOfStationaryCoordinates",0, ...
    "numberOfTangentTraceCoordinates",0, ...
    "numberOfNonTangentTraceCoordinates",0, ...
    "providerPasses",false,"liftRankDefect",Inf, ...
    "maximumLiftTraceDefect",Inf,"maximumLiftEnergyDefect",Inf, ...
    "maximumLiftAPVDefect",Inf, ...
    "stationaryRepresentationDefect",Inf,"stationaryRowDefect",Inf, ...
    "stationaryBottomTangencyDefect",Inf, ...
    "stationaryConjugacyDefect",Inf,"maximumProjectorDefect",Inf, ...
    "maximumFrequencyDefect",Inf,"maximumRitzResidual",Inf, ...
    "maximumAPVDefect",Inf,"maximumBottomDefect",Inf, ...
    "maximumStrongResidual",Inf,"energyHermitianDefect",Inf, ...
    "exchangeSkewHermitianDefect",Inf,"ambientRankDefect",Inf, ...
    "minimumAmbientSingularValue",NaN,"liftDiagnostics",struct, ...
    "representation",struct);
end

function layout = retainedLayout(problem,bounds)
source = problem.horizontalLayout;
mask = abs(source.kMode) <= bounds(1) ...
    & abs(source.lMode) <= bounds(2);
layout = source(mask,:);
expected = (2*bounds(1)+1)*(2*bounds(2)+1);
if height(layout) ~= expected
    error("WVTerrainEnergyGalerkin:UnavailableGlobalTangentSupport", ...
        "The originating transform does not retain the complete signed rectangle [%d %d].", ...
        bounds(1),bounds(2))
end
end

function value = emptyFactorizationResult
value = struct("numberOfRawCoordinates",0, ...
    "numberOfZeroTraceCoordinates",0, ...
    "numberOfTangentTraceCoordinates",0, ...
    "numberOfNonTangentTraceCoordinates",0, ...
    "numberOfStationaryCoordinates",0, ...
    "numberOfExactStationaryCoordinates",0, ...
    "dimensionDefect",Inf,"projectorDefect",Inf, ...
    "zeroTraceDefect",Inf,"tangentTraceDefect",Inf, ...
    "traceConjugacyDefect",Inf,"rankStable",false, ...
    "tangentLiftTraceDefect",Inf, ...
    "tangentLiftEnergyDefect",Inf,"tangentLiftAPVDefect",Inf, ...
    "stationaryRowDefect",Inf, ...
    "stationaryBottomTangencyDefect",Inf, ...
    "stationaryConjugacyDefect",Inf, ...
    "complementStationaryOrthogonalityDefect",Inf, ...
    "supportModeBounds",[0 0],"paddingFactor",0, ...
    "primitiveReferenceDegree",0,"trustedProjectorDefect",Inf, ...
    "trustedDimensionDefect",Inf,"traceRank",0, ...
    "numberOfTraceCoordinates",0, ...
    "minimumLiftSingularValue",NaN,"liftConditionNumber",NaN);
end

function [audit,cache] = loadAuditCache(problem,directory,configuration)
audit = [];
cache = emptyCacheDiagnostics(directory);
if directory == ""
    cache.numberOfMisses = 1;
    cache.records = cacheRecord("disabled","","",0,0,0);
    return
end
if ~isfolder(directory)
    mkdir(directory);
end
schema = "global-tangent-stationary-cache-v1";
key = cacheKey(problem,configuration,schema);
path = string(fullfile(directory,"audit-"+key+".mat"));
cache.key = key;
cache.path = path;
if ~isfile(path)
    cache.numberOfMisses = 1;
    cache.records = cacheRecord("miss",key,path,0,0,0);
    return
end
try
    loaded = load(path,"entry");
    entry = loaded.entry;
    if entry.schema ~= schema || entry.key ~= key
        cache.numberOfInvalidations = 1;
        cache.numberOfMisses = 1;
        cache.records = cacheRecord("invalidated",key,path,0,0,0);
        return
    end
    audit = entry.audit;
    information = dir(path);
    cache.numberOfHits = 1;
    cache.bytes = information.bytes;
    cache.secondsSaved = entry.buildSeconds;
    cache.records = cacheRecord( ...
        "hit",key,path,information.bytes,entry.buildSeconds, ...
        entry.buildSeconds);
catch
    cache.numberOfInvalidations = 1;
    cache.numberOfMisses = 1;
    cache.records = cacheRecord("invalidated",key,path,0,0,0);
end
end

function audit = saveAuditCache(audit,directory,configuration,cache, ...
    buildSeconds)
if directory == ""
    return
end
schema = "global-tangent-stationary-cache-v1";
key = cache.key;
path = cache.path;
entry = struct("schema",schema,"key",key, ...
    "configuration",configuration,"buildSeconds",buildSeconds, ...
    "created",string(datetime("now","TimeZone","UTC")), ...
    "audit",audit);
temporary = string(tempname(directory))+".mat";
cleanup = onCleanup(@()deleteIfPresent(temporary));
save(temporary,"entry","-v7.3");
movefile(temporary,path,"f");
clear cleanup
information = dir(path);
audit.cache.numberOfMisses = 1;
audit.cache.bytes = information.bytes;
audit.cache.secondsSaved = buildSeconds;
audit.cache.records = cacheRecord( ...
    "miss",key,path,information.bytes,buildSeconds,0);
end

function cache = emptyCacheDiagnostics(directory)
cache = struct("enabled",directory ~= "","directory",directory, ...
    "key","","path","","records",struct([]), ...
    "numberOfHits",0,"numberOfMisses",0, ...
    "numberOfInvalidations",0,"bytes",0,"secondsSaved",0);
end

function record = cacheRecord(status,key,path,bytes,buildSeconds,secondsSaved)
record = struct("status",status,"key",key,"path",path, ...
    "bytes",bytes,"buildSeconds",buildSeconds, ...
    "secondsSaved",secondsSaved);
end

function key = cacheKey(problem,configuration,schema)
engine = java.security.MessageDigest.getInstance("SHA-256");
updateDigest(engine,uint8(char(schema)));
updateDigest(engine,uint8(char(jsonencode(configuration))));
files = [string(mfilename("fullpath"))+".m"; ...
    fullfile(fileparts(fileparts(mfilename("fullpath"))), ...
    "auditGlobalTangentStationaryCompression.m"); ...
    fullfile(fileparts(fileparts(mfilename("fullpath"))), ...
    "auditAnalyticGlobalTangentStationaryCompression.m"); ...
    fullfile(fileparts(mfilename("fullpath")), ...
    "factorGlobalTangentStationarySpace.m"); ...
    fullfile(fileparts(mfilename("fullpath")), ...
    "buildZeroTraceGeostrophicVerticalFamily.m"); ...
    fullfile(fileparts(mfilename("fullpath")), ...
    "buildAnalyticZeroTraceGeostrophicVerticalFamily.m"); ...
    string(which("IMSolverSpectral")); ...
    string(which("IMInternalModes")); ...
    string(which("IMBoundaryCondition"))];
if any(files == "")
    error("WVTerrainEnergyGalerkin:MissingGlobalTangentProvider", ...
        "The isolated InternalModesEVP provider must be on the MATLAB path.")
end
for iFile = 1:numel(files)
    updateDigest(engine,uint8(fileread(files(iFile))));
end
wvt = problem.originatingTransform;
updateDigest(engine,typecast(double([wvt.Lx wvt.Ly wvt.Lz ...
    wvt.Nx wvt.Ny wvt.Nz wvt.f wvt.g wvt.rho0]),"uint8"));
updateDigest(engine,typecast(double(problem.topographicHeight(:)),"uint8"));
z = linspace(-wvt.Lz,0,max(17,2*wvt.Nz+1)).';
N2 = wvt.N2Function(z);
if isscalar(N2)
    N2 = repmat(N2,size(z));
end
updateDigest(engine,typecast(double(N2(:)),"uint8"));
digest = typecast(engine.digest(),"uint8");
key = lower(join(compose("%02x",digest),""));
end

function updateDigest(engine,bytes)
engine.update(bytes);
end

function deleteIfPresent(path)
if isfile(path)
    delete(path);
end
end
