function audit = buildSlopeCompatibleWaveModeCompressionAudit( ...
    problem,trustedBounds,supportBounds,stationaryDegree,degrees, ...
    comparisonDegree,modalCounts,robinLengthRatios,referenceSlopeFactors, ...
    dynamics,paddingFactors,terrainScales,solverOrders,quadratureOrder)
% Build the Milestone-9.3 trained slope-compatible wave-coordinate oracle.

[slopeDirection,rmsSlope,gradientCovariance] = referenceSlopeGeometry(problem);
candidateSpecifications = candidateGrid(dynamics,referenceSlopeFactors, ...
    slopeDirection,rmsSlope);
nCandidate = numel(candidateSpecifications);
candidates = repmat(struct, nCandidate,1);
sharedSetup = [];
for iCandidate = 1:nCandidate
    specification = candidateSpecifications(iCandidate);
    candidates(iCandidate).specification = specification;
    candidatePaddingFactors = paddingFactors(1);
    candidateSharedSetup = sharedSetup;
    if isempty(sharedSetup)
        candidatePaddingFactors = paddingFactors;
    else
        candidateSharedSetup = sharedSetup(1);
    end
    candidateAudit = ...
        buildBoundaryCompleteVerticalModeCompressionAudit( ...
        problem,trustedBounds,supportBounds,stationaryDegree,degrees, ...
        comparisonDegree,modalCounts(end),robinLengthRatios, ...
        candidatePaddingFactors, ...
        terrainScales,solverOrders,quadratureOrder, ...
        specification.waveCoordinateType,specification.referenceSlope, ...
        candidateSharedSetup);
    if isempty(sharedSetup)
        sharedSetup = candidateAudit.sharedSetup;
    end
    candidateAudit = rmfield(candidateAudit,"sharedSetup");
    candidates(iCandidate).training = trainingDiagnostics(candidateAudit);
    candidates(iCandidate).audit = compactCandidateAudit(candidateAudit);
end

selectedByDynamicsCell = cell(numel(dynamics),1);
for iDynamics = 1:numel(dynamics)
    indices = find([candidateSpecifications.dynamics] == dynamics(iDynamics));
    scores = arrayfun(@(value)value.training.score,candidates(indices));
    [~,relativeIndex] = min(scores);
    selectedIndex = indices(relativeIndex);
    specification = candidates(selectedIndex).specification;
    selectedAudit = buildBoundaryCompleteVerticalModeCompressionAudit( ...
        problem,trustedBounds,supportBounds,stationaryDegree,degrees, ...
        comparisonDegree,modalCounts,robinLengthRatios,paddingFactors, ...
        terrainScales,solverOrders,quadratureOrder, ...
        specification.waveCoordinateType,specification.referenceSlope, ...
        sharedSetup);
    selectedAudit = rmfield(selectedAudit,"sharedSetup");
    candidates(selectedIndex).training = trainingDiagnostics( ...
        selectedAudit);
    selectedByDynamicsCell{iDynamics} = selectedCandidate( ...
        selectedAudit,candidates(selectedIndex).training, ...
        candidates(selectedIndex).specification, ...
        selectedIndex,dynamics(iDynamics));
    candidates(selectedIndex).audit = compactCandidateAudit(selectedAudit);
end
selectedByDynamics = vertcat(selectedByDynamicsCell{:});

passing = find([selectedByDynamics.validationPasses]);
if isempty(passing)
    classification = "per-wavenumber-slope-incompatible";
    preferred = struct;
    diagnosis = "Neither trained-and-frozen slope-compatible family satisfies the primitive physical projector, APV, bottom, strong-equation, and compression gates.";
else
    acceleration = passing([selectedByDynamics(passing).compressionFactor] >= 2);
    if isempty(acceleration)
        classification = "slope-modal-equivalent";
        [~,best] = max([selectedByDynamics(passing).compressionFactor]);
        preferred = selectedByDynamics(passing(best));
        diagnosis = "A trained slope-compatible family converges to the primitive physical subspace, but it supplies less than a factor-two reduction.";
    else
        hydro = acceleration([selectedByDynamics(acceleration).dynamics] ...
            == "hydrostatic");
        nonhydro = acceleration([selectedByDynamics(acceleration).dynamics] ...
            == "nonhydrostatic");
        if ~isempty(hydro) && ~isempty(nonhydro)
            hydroCompression = selectedByDynamics(hydro).compressionFactor;
            nonhydroCompression = ...
                selectedByDynamics(nonhydro).compressionFactor;
            if nonhydroCompression > 1.1*hydroCompression
                preferred = selectedByDynamics(nonhydro);
                classification = "nonhydrostatic-slope-acceleration";
            else
                preferred = selectedByDynamics(hydro);
                classification = "hydrostatic-slope-acceleration";
            end
        elseif ~isempty(hydro)
            preferred = selectedByDynamics(hydro);
            classification = "hydrostatic-slope-acceleration";
        else
            preferred = selectedByDynamics(nonhydro);
            classification = "nonhydrostatic-slope-acceleration";
        end
        diagnosis = "The trained-and-frozen preferred slope-compatible family passes the physical gates with at least a factor-two reduction in admissible vertical coordinates.";
    end
end

audit = struct;
audit.scope = "milestone-9.3-slope-compatible-wave-coordinate-oracle";
audit.status = classification;
audit.classification = classification;
audit.isCompatible = classification ~= "per-wavenumber-slope-incompatible";
audit.diagnosis = diagnosis;
audit.gradientCovariance = gradientCovariance;
audit.referenceSlopeDirection = slopeDirection;
audit.rmsReferenceSlope = rmsSlope;
audit.trainingRule = struct( ...
    "paddingFactor",paddingFactors(1), ...
    "modalCount",modalCounts(end), ...
    "score","max(projector/1e-8,bottom/1e-10,apv/1e-8,strong/1e-5)", ...
    "tieTolerance",0.01, ...
    "tieBreakers",["smaller-completed-dimension"; ...
    "lower-physical-energy-Gram-condition"]);
audit.robinInterpretation = struct( ...
    "role","finite-order-convergence-parameter", ...
    "selection","trained-jointly-with-reference-slope", ...
    "validation","selected-values-frozen");
audit.candidates = candidates;
audit.selectedByDynamics = selectedByDynamics;
audit.preferred = preferred;
audit.trustedModeBounds = trustedBounds;
audit.supportModeBounds = supportBounds;
audit.stationaryPolynomialDegree = stationaryDegree;
audit.primitivePolynomialDegrees = degrees;
audit.comparisonPolynomialDegree = comparisonDegree;
audit.modalCounts = modalCounts;
audit.robinLengthRatios = robinLengthRatios;
audit.referenceSlopeFactors = referenceSlopeFactors;
audit.dynamics = dynamics;
audit.paddingFactors = paddingFactors;
audit.terrainScales = terrainScales;
audit.internalModesEVPOrders = solverOrders;
audit.quadratureOrder = quadratureOrder;
audit.nextScope = "milestone-10-only-if-separately-authorized";
end

function [direction,rmsSlope,covariance] = referenceSlopeGeometry(problem)
wvt = problem.originatingTransform;
hx = wvt.diffX(problem.topographicHeight);
hy = wvt.diffY(problem.topographicHeight);
gradient = [hx(:) hy(:)];
covariance = real(gradient'*gradient/size(gradient,1));
[vectors,values] = eig((covariance+covariance')/2,"vector");
[largest,index] = max(real(values));
direction = real(vectors(:,index)).';
direction = direction/max(norm(direction),realmin);
[~,component] = max(abs(direction));
if direction(component) < 0
    direction = -direction;
end
rmsSlope = sqrt(max(largest,0));
end

function specifications = candidateGrid(dynamics,factors,direction,rmsSlope)
specifications = repmat(struct( ...
    "dynamics","","referenceSlopeFactor",0, ...
    "referenceSlope",zeros(1,2), ...
    "waveCoordinateType","","controlName",""),0,1);
for iDynamics = 1:numel(dynamics)
    for iFactor = 1:numel(factors)
        signs = 1;
        if factors(iFactor) > 0
            signs = [-1 1];
        end
        for signValue = signs
            specification = struct;
            specification.dynamics = dynamics(iDynamics);
            specification.referenceSlopeFactor = signValue*factors(iFactor);
            specification.referenceSlope = ...
                signValue*factors(iFactor)*rmsSlope*direction;
            specification.waveCoordinateType = ...
                dynamics(iDynamics)+"-slope";
            if factors(iFactor) == 0
                specification.controlName = dynamics(iDynamics)+"-dirichlet";
            else
                specification.controlName = ...
                    dynamics(iDynamics)+"-slope-compatible";
            end
            specifications(end+1,1) = specification; %#ok<AGROW>
        end
    end
end
end

function diagnostics = trainingDiagnostics(audit)
tolerance = struct("provider",2e-10,"endpoint",2e-10, ...
    "descriptor",1e-11,"structure",1e-12, ...
    "projector",1e-8,"bottom",1e-10,"apv",1e-8,"strong",1e-5);
nRobin = numel(audit.robinLengthRatios);
score = Inf(nRobin,1);
passesLocal = false(nRobin,1);
dimension = Inf(nRobin,1);
conditionNumber = Inf(nRobin,1);
for iRobin = 1:nRobin
    result = audit.details{end,iRobin,1};
    passesLocal(iRobin) = ...
        result.maximumProviderDefect <= tolerance.provider ...
        &&result.maximumEndpointDefect <= tolerance.endpoint ...
        &&result.maximumWaveDescriptorResidual <= tolerance.descriptor ...
        &&result.maximumWaveMomentumResidual <= tolerance.descriptor ...
        &&result.maximumWaveBottomResidual <= tolerance.descriptor ...
        &&result.maximumWaveBackwardError <= tolerance.descriptor ...
        &&result.energyHermitianDefect <= tolerance.structure ...
        &&result.exchangeSkewHermitianDefect <= tolerance.structure;
    if passesLocal(iRobin)
        score(iRobin) = max([ ...
            result.internalProjectorDefect/tolerance.projector, ...
            result.bottomEvolutionDefect/tolerance.bottom, ...
            result.maximumInternalAPVDefect/tolerance.apv, ...
            result.maximumInternalStrongResidual/tolerance.strong]);
    end
    dimension(iRobin) = result.actualModalDimension;
    conditionNumber(iRobin) = result.referenceGramConditionNumber;
end
minimum = min(score);
eligible = find(score <= minimum*(1+0.01));
if isempty(eligible)
    selectedRobin = 1;
else
    [~,order] = sortrows([dimension(eligible) conditionNumber(eligible)],[1 2]);
    selectedRobin = eligible(order(1));
end
diagnostics = struct;
diagnostics.scoreByRobin = score;
diagnostics.localPassesByRobin = passesLocal;
diagnostics.dimensionByRobin = dimension;
diagnostics.conditionNumberByRobin = conditionNumber;
diagnostics.selectedRobinIndex = selectedRobin;
diagnostics.selectedRobinLengthRatio = ...
    audit.robinLengthRatios(selectedRobin);
diagnostics.score = score(selectedRobin);
diagnostics.localPasses = passesLocal(selectedRobin);
end

function selected = selectedCandidate( ...
    audit,training,specification,index,dynamics)
iRobin = training.selectedRobinIndex;
result = audit.details{end,iRobin,1};
padding = paddingDiagnostic(audit.details(end,iRobin,:));
strong = cellfun(@(value)value.maximumInternalStrongResidual, ...
    audit.details(:,iRobin,1));
if numel(strong) >= 3
    finalStrong = strong(end-2:end);
    strongConvergence = all(finalStrong(1:end-1) ...
        ./max(finalStrong(2:end),realmin) >= 4);
else
    strongConvergence = false;
end
tolerance = struct("projector",1e-8,"frequency",1e-8, ...
    "apv",1e-8,"bottom",1e-10,"strong",1e-5, ...
    "padding",1e-8,"stationary",1e-10);
validationPasses = training.localPasses ...
    &&result.stationaryRepresentationDefect <= tolerance.stationary ...
    &&result.stationaryRowDefect <= tolerance.stationary ...
    &&result.internalProjectorDefect <= tolerance.projector ...
    &&result.internalFrequencyDefect <= tolerance.frequency ...
    &&result.maximumInternalAPVDefect <= tolerance.apv ...
    &&result.bottomEvolutionDefect <= tolerance.bottom ...
    &&result.maximumInternalStrongResidual <= tolerance.strong ...
    &&padding <= tolerance.padding ...
    &&strongConvergence;
selected = struct;
selected.dynamics = dynamics;
selected.candidateIndex = index;
selected.specification = specification;
selected.robinIndex = iRobin;
selected.robinLengthRatio = audit.robinLengthRatios(iRobin);
selected.trainingScore = training.score;
selected.validationPasses = validationPasses;
selected.compressionFactor = result.actualCompressionFactor;
selected.paddingProjectorDefect = padding;
selected.strongResidualByCount = strong;
selected.strongConvergencePasses = strongConvergence;
selected.result = result;
end

function compact = compactCandidateAudit(audit)
compact = struct;
compact.waveCoordinateType = audit.waveCoordinateType;
compact.referenceSlope = audit.referenceSlope;
compact.modalCounts = audit.modalCounts;
compact.robinLengthRatios = audit.robinLengthRatios;
compact.paddingFactors = audit.paddingFactors;
compact.classification = audit.classification;
compact.details = cell(size(audit.details));
for iDetail = 1:numel(audit.details)
    result = audit.details{iDetail};
    compact.details{iDetail} = struct( ...
        "modalCount",result.modalCount, ...
        "robinLengthRatio",result.robinLengthRatio, ...
        "paddingFactor",result.paddingFactor, ...
        "internalProjectorDefect",result.internalProjectorDefect, ...
        "internalFrequencyDefect",result.internalFrequencyDefect, ...
        "maximumInternalAPVDefect",result.maximumInternalAPVDefect, ...
        "bottomEvolutionDefect",result.bottomEvolutionDefect, ...
        "maximumInternalStrongResidual", ...
        result.maximumInternalStrongResidual, ...
        "actualModalDimension",result.actualModalDimension, ...
        "actualCompressionFactor",result.actualCompressionFactor, ...
        "referenceGramConditionNumber", ...
        result.referenceGramConditionNumber, ...
        "energyHermitianDefect",result.energyHermitianDefect, ...
        "exchangeSkewHermitianDefect", ...
        result.exchangeSkewHermitianDefect, ...
        "stationaryRepresentationDefect", ...
        result.stationaryRepresentationDefect, ...
        "stationaryRowDefect",result.stationaryRowDefect, ...
        "maximumProviderDefect",result.maximumProviderDefect, ...
        "maximumEndpointDefect",result.maximumEndpointDefect, ...
        "maximumWaveDescriptorResidual", ...
        result.maximumWaveDescriptorResidual, ...
        "maximumWaveMomentumResidual", ...
        result.maximumWaveMomentumResidual, ...
        "maximumWaveBottomResidual", ...
        result.maximumWaveBottomResidual, ...
        "maximumWaveBackwardError", ...
        result.maximumWaveBackwardError, ...
        "maximumWaveFlatFrequencyDefect", ...
        result.maximumWaveFlatFrequencyDefect, ...
        "maximumWaveBottomDisplacement", ...
        result.maximumWaveBottomDisplacement);
end
end

function defect = paddingDiagnostic(results)
results = results(:);
reference = results{1}.internalWaveProjector;
defect = 0;
for iResult = 2:numel(results)
    defect = max(defect,norm(reference ...
        -results{iResult}.internalWaveProjector,"fro") ...
        /max(norm(reference,"fro"),realmin));
end
end
